Feature/#100 카테고리 목록 조회 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #101
Opened 2023-08-05 05:57 UTC by woo-chang

## 🔥 연관 이슈

close: #100

## 📝 작업 요약

가게 카테고리 목록 조회 기능을 구현하였습니다.

## 🔎 작업 상세 설명

ID 오름차순으로 정렬된 가게 카테고리 목록 조회 기능을 구현하였습니다.

## 🌟 리뷰 요구 사항

> 5분
> 매우매우 간단한 기능입니다 :)

2023-08-06 05:05 UTC, Kim0914 requested changes
고생했습니다 ㅎㅎ
코멘트 남겼는데 확인부탁해요 !

추가적으로 브랜치 명 컨벤션이 맞지 않는 것 같습니다.

![image](https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/68818952/f8064424-753f-4cd1-9ce3-9dcc48268a3e)

브랜치 명을 `Feature#숫자_어떤_작업_일까` 구조로 가져가기로 했었는데
체크부탁드려요 !

2023-08-06 05:05 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreController.java
> +    public ResponseEntity<CategoryResponses> getCategories() {
카테고리 조회를 위한 API를 열어둘 필요가 있을까요?!

현재 서버와 클라이언트에서 카테고리는 모두 정적인 데이터로 관리되는 것 같습니다 ㅎㅎ (카테고리가 추가되는 요소도 현재로서는 없어보이고, 추가한다고 하더라도 디비에 직접 넣을 것 같아보이네요 ~)

서로가 필요한 카테고리를 가지고 검색할 때 필터링만 하는 용도로만 사용될 것 같은데
이 API를 작성해주신 이유가 궁금하네요 😀

2023-08-06 05:05 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/CategoryRepositoryTest.java
> +    void 카테고리_목록을_ID를_기준으로_오름차순으로_정렬하여_조회한다() {
위 API 커멘트에 보충해서 카테고리 조회 기능에 대한 테스트는 Repository 계층 테스트만으로도 충분해 보여요 ㅎㅎ

2023-08-06 09:35 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreController.java
> +    public ResponseEntity<CategoryResponses> getCategories() {
모두 정적인 데이터로 관리되는 부분은 맞습니다! 하지만 각각 따로 데이터로 관리하면 클라이언트만 업데이트한다거나 서버만 업데이트하는 경우 데이터가 어긋날 수 있기 때문에 클라이언트에서는 카테고리 목록을 조회해서 사용하는 것 데이터 정합성 측면에서 좋아보였습니다 :)

2023-08-06 09:38 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/CategoryRepositoryTest.java
> +    void 카테고리_목록을_ID를_기준으로_오름차순으로_정렬하여_조회한다() {
`application` 계층은 무엇을 테스트하려는지 의도가 보이지 않아 삭제하였습니다 😙

2023-08-06 09:48 UTC, woo-chang commented
> 고생했습니다 ㅎㅎ 코멘트 남겼는데 확인부탁해요 !
> 
> 추가적으로 브랜치 명 컨벤션이 맞지 않는 것 같습니다.
> 
> ![image](https://user-images.githubusercontent.com/68818952/258622569-f8064424-753f-4cd1-9ce3-9dcc48268a3e.png)
> 
> 브랜치 명을 `Feature#숫자_어떤_작업_일까` 구조로 가져가기로 했었는데 체크부탁드려요 !

깜빡하고 빠져먹을 것 같습니다 🥲 다음부터는 잘 지키도록 하겠습니다! 애플 로그인 기능도 빠져있는 점 양해바랍니다 🙇🏻‍♂️

2023-08-07 07:14 UTC, Kim0914 approved these changes
프론트와 API를 사용한다고 협의된 사항이므로 approve하겠습니다 !

2023-08-07 07:14 UTC, merged