Feature/#86 리뷰 작성 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #110
Opened 2023-08-10 14:33 UTC by Kim0914

## 🔥 연관 이슈

close: #86 

## 📝 작업 요약

리뷰 작성 기능을 구현했습니다.

## 🔎 작업 상세 설명

(상세 설명 추가 예정)

## 🌟 리뷰 요구 사항

> 리뷰 예상 시간 및 집중 리뷰 부분을 작성해주세요.

2023-08-14 17:42 UTC, woo-chang requested changes
안녕하세요 리뷰어 다즐입니다 🔥
굉장히 복잡한 로직이 많이 들어가있고 신경쓸 부분이 많은 기능인데
꼼꼼히 잘 작성해주신 느낌이 들었습니다.

무엇보다 코드가 깔끔하고 가독성이 너무 좋아서 리뷰하기 너무 좋았습니다.
코드가 많았음에도 지금까지 한 리뷰중에 가장 편하게 리뷰했던 경험이었습니다 👍
그래서 그런지 리뷰가 엄청 많네요 .. ㅎ

읽어보시고 반영해주실 부분은 반영해주시고 그레이의 의견이 있는 부분은 커멘트 달아주시면 저도 읽어보고 다시 한번 싱크를 맞춰가는 과정이 진행되면 좋을 것 같아요 👍

정말 정말 수고하셨습니다 ㅎㅎ

---

우선 테스트 코드는 리뷰하지 않았는데 1차 리뷰가 반영되면 테스트 코드도 리뷰하도록 할께요 ~~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                            + "가게 카테고리 정보가 없는 경우, 가게 리뷰 내용이 없는 경우",
모든 예외 상황에 대해서 꼼꼼히 작성해주셨네요 👍
```suggestion
                    description = "1.사진이 4개보다 많은 경우\t\n2.가게 이름 값이 없는 경우\t\n3.가게 주소 필드가 값이 없는 경우"
                            + "\t\n4.가게 경도 값이 없는 경우\t\n5.가게 위도 값이 없는 경우\t\n6.가게 정보 URL이 없는 경우"
                            + "\t\n7.카테고리 정보가 없는 경우\t\n8.가게 리뷰 내용이 없는 경우",
```
<img width="1310" alt="스크린샷 2023-08-15 오전 1 24 47" src="https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/78212016/813f8192-539b-4df2-bfe2-bd95a67fded6">

<img width="331" alt="스크린샷 2023-08-15 오전 1 24 18" src="https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/78212016/849fcc67-f3f5-4288-a3e0-68175251ed87">

숫자로 가독성을 챙겨보는건 어떨까요?! 😀

숫자와 내용 사이에 공백을 주게 되면 `ordered list`로 인식하게 되서 추가적인 공백이 생기게 되서 숫자와 내용 사이는 붙이도록 하였습니다!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
```suggestion
    ResponseEntity<Void> create(ReviewCreateRequest reviewCreateRequest, List<MultipartFile> imageFiles, Member member);
}
```
문서화를 위한 인터페이스이기에 구현체에 대한 정보는 빼는 것은 어떨까요~~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +@Validated
👍

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +            @Size(max = 4, message = "사진의 개수는 최대 4개까지 가능합니다.") List<MultipartFile> imageFiles,
`@ModelAttribute`를 사용할 수 있는데 요청과 이미지 파일을 분리해서 받으신 이유가 궁금합니다 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +        return ResponseEntity.created(URI.create("/v1/reviews/" + reviewId)).build();
리뷰 1개의 상세 내역을 조회하는 `API`가 없을 것 같은데 해당 경로를 내려주신 이유가 궁금합니다 🤔
- 해당 API가 존재하지 않더라도 `Location`을 지정해주는게 좋을까요?!
- `CREATD` 응답을 반환하더라도 `Location`은 주지 않는 방법은 어떨까요?!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        @Schema(description = "가게 이름", example = "맥도날드 강남점", requiredMode = REQUIRED)
`requiredMode`를 통해 필수값을 설정할 수 있군요 👍

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        BigDecimal y,
위도, 경도는 대중적으로 정해져 있는 범위가 있는 값이기에 `DTO`에서 검증해주는 것은 어떨까요?

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        BigDecimal schoolY
위도, 검증이 이루어진다면 여기도 수정이 필요하겠네요 ㅎㅎ

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/dto/reqeust/AppleLoginRequest.java
> +        @Schema(description = "애플 토큰", example = "a1b2c3d4", requiredMode = REQUIRED)
여기도 꼼꼼하게 수정해주셨네요 🙌

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +@Transactional(readOnly = true)
클래스레벨에 해당 어노테이션을 붙이면 메서드에 종종 빼먹는 경우가 있더라구요 ㅎ..

메서드마다 어떤 트랜잭션이 동작하는지 명시적으로 보여주고,
메서드마다 꼼꼼히 확인할 수 있게 각 메서드마다 붙여주는건 어떨까요?!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +    private final PhotoService photoService;
`Repository`와 `Service`에 대한 의존성을 함께 주입받고 있으니 뭔가 어색하긴 하네요 ㅎㅎ

추후에 리팩토링 해봅시다~~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        );
`Request`에 대한 의존성이 너무 전파되면 안되기에 이게 최선이겠죠? 마음 같아서는 정팩메를 사용하고 싶네요 😙

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/dto/StoreCreateDto.java
> +}
```suggestion
public record StoreCreateDto(
        String storeName,
        String category,
        String address,
        BigDecimal storeX,
        BigDecimal storeY,
        String storeUrl,
        String phone,
        String schoolName,
        BigDecimal schoolX,
        BigDecimal schoolY
) {
}
```
개행이 불편해요~~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/dto/StoreCreateDto.java
> +package org.dinosaur.foodbowl.domain.store.dto;
domain 밑에 존재하는 dto는 **controller, service에서 모두 사용**될 수 있는 `request`, `response`에 대한 dto만 두는건 어떨까요?

해당 dto는 Service에서만 사용되는 dto라서 `store/application/dto/StoreCreateDto`로 옮기면 좋을 것 같습니다 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +@Transactional(readOnly = true)
여기도 `ditto`

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Store store = storeService.create(storeCreateDto);
`create` 메서드에서는 이미 존재하는 가게라면 예외를 던지고 있는데, 이미 생성된 가게에 대한 리뷰를 작성하는 경우 예외가 터질 것 같아요!

여기서는 조회 메서드가 호출되고 조회 메서드 내부에서 **생성 및 조회 or 조회**가 되어야 정상적으로 동작할 것 같아요 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        storeRepository.findByAddress_AddressName(storeCreateDto.address()).ifPresent(
주소는 완전히 동일한데(같은 건물, 같은 층) 가게 이름만 다른 경우도 있지 않을까요? 🤔

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        return storeRepository.findByAddress_AddressName(address);
주소는 완전히 동일한데(같은 건물, 같은 층) 가게 이름만 다른 경우도 있지 않을까요? 🤔

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +    private Store convertToStore(StoreCreateDto storeCreateDto) {
세로 가독성을 위해 `create` 메서드 밑에 있으면 더 좋을 것 같아요 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +    private void saveSchool(Store store, String schoolName, BigDecimal schoolX, BigDecimal schoolY) {
여기도 세로 가독성을 위해 위로 한칸 살짝 ㅎㅎ

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +            String schoolName = storeCreateDto.schoolName();
`schoolName`만 따로 뺀 이유가 있을까요?!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/SchoolService.java
> +@Transactional(readOnly = true)
여기도 `ditto`

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        if (images == null) {
개수가 `0`인 경우는 발생하지 않나요? 😀

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        saveImagesIfExists(imageFiles, store, review);
메서드명 굳 👍👍

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +    private void saveImagesIfExists(List<MultipartFile> images, Store store, Review review) {
현재는 `Photo`에 `Review` 의존성이 있어서 이 메서드가 `PhotoService`에서 이루어져야 한다고 생각하는데 어떻게 생각하시나요?

그렇게 된다면 `ReviewService`에서 `PhotoUtils`에 대한 의존성이 없어도 될 것 같습니다 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoUtils.java
> +public interface PhotoUtils {
인터페이스 굳 👍 같이 얘기한대로 네이밍만 조금 수정되면 더 좋을 것 같아요 👍

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +        File directory = loadDirectory(rootDirectory + SLASH + parentDirectory);
한글 가게 이름 디렉토리가 생성될 것 같은데 가게 ID를 활용해보는건 어떨까요? 🤔

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +    private String rootDirectory;
```suggestion
    private final String rootDirectory;
    
    public FileStstemPhotoUtils(@Value("${file.dir}") String rootDirectory) {
        this.rootDirectory = rootDirectory;
    }
```
불변으로 만드는 방법도 존재합니다~~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +    private static final String SLASH = "/";
`/`는 `File.separator`를 활용하는건 어떨까요?!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +        File directory = loadDirectory(rootDirectory + SLASH + parentDirectory);
`rootDirectory`는 `System.getProperty`("user.dir")를 활용해보는건 어떨까요?

System.getProperty("user.dir")를 사용하면 로컬에서 실행할 때는 `src`와 같은 위치의 경로값을 가져오고, `jar` 파일을 가동한 상황이라면 `jar` 파일이 존재하고 있는 경로를 가져옵니다. 따라서 환경 변수로 가져온 경로는 루트 경로로부터 파일 디렉토리만 정해주면 될 것 같아요! 예를 들면 아래와 같습니다.

```java
@Value("${file.dir}")
private String fileDirectory;

String filePath = System.getProperty("user.dir") + File.separator + fileDirectory;
```
`fileDirectory`의 값은 `images` 같은 것이 될 수 있을 것 같네요!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +            }
`null`이거나 비어있을 때 예외 상황으로 판단하지 않은 이유가 궁금합니다 ㅎㅎ

추가적으로 `MultipartFile`이 이미지 파일이 아닌 파일이 들어올 수 있는데 해당 상황에 대한 검증도 있으면 더욱 더욱 좋을 것 같아요!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +    private void validateFileName(String fileName) {
가독성을 위해 올려주시면 감사합니다~~ 🙇🏻‍♂️

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +    private void validateFileName(String fileName) {
파일 이름 검증까지 너무 좋습니다 👍

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +        return fileBaseName + DASH + System.currentTimeMillis() + DOT + extension;
기존 파일명을 가져갈 필요가 있을까요?!

- 네이버처럼 UUID(글자 수 제한) + _ + System.currentTimeMillis() + DOT + jpg와 같은 형식은 어떨까요? 🤓

기존 확장자를 가져갈 필요가 있을까요?!

- 사용자가 어떤 확장자로 보내든 서버에 저장하기에 가장 알맞은 형식 1가지로 저장하는 방법은 어떨까요?! 🤓

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +            throw new FileException(FILE_TRANSFER_ERROR);
발생하는 예외 `e`도 `FileException`에 넘겨줘서 추후에 로그로 확인할 수 있게 하면 더 좋을 것 같아요 ㅎㅎ

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/exception/FileExceptionType.java
> +@RequiredArgsConstructor
`Lombok`을 사용하신다면 생성자 접근 범위를 제한해보는건 어떨까요?!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +    private void saveImagesIfExists(List<MultipartFile> images, Store store, Review review) {
옮긴다면 고민하셨던 `PhotoService`에 대한 책임도 해결될 것 같아요 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        Store store = storeRepository.save(convertToStore(storeCreateDto));
여기도 기존에 학교가 존재하는 상황이라면 예외가 발생해서 리뷰를 작성못할 것 같아요!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/School.java
> +    @Valid
👍

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/Address.java
> +            throw new BadRequestException(INVALID_ADDRESS_ERROR);
도메인 내부에서 활용하기 위한 `InvalidArgumentException`을 만들어두었는데 해당 예외를 활용해보는거 어떨까요?!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/Address.java
> +    public static Address of(String storeAddress, BigDecimal x, BigDecimal y) {
주소 파싱 너무너무 좋아요 👍👍

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/CategoryType.java
> +                .orElseThrow(() -> new BadRequestException(CategoryExceptionType.NOT_FOUND));
여기도 `InvalidArgumentException`을 활용하면 더 좋을 것 같아요 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/Coordinate.java
> +            throw new BadRequestException(INVALID_X_ERROR);
InvalidArgumentException ditto~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/Coordinate.java
> +            throw new BadRequestException(INVALID_Y_ERROR);
InvalidArgumentException ditto~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/Coordinate.java
> +public class Coordinate {
클래스명부터 검증까지 폼 미쳐따 .. 🔥

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/exception/FileExceptionType.java
> +@Getter
`Getter`를 위로 옮겨주시면 감사합니다 🙇🏻‍♂️

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/SchoolName.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Embeddable
```
조금 더 중요한 `@Embeddable`을 밑으로 내리는건 어떨까요?!

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/SchoolName.java
> +            throw new BadRequestException(SchoolExceptionType.INVALID_SCHOOL_NAME_ERROR);
InvalidArgumentException ditto~

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/exception/CategoryExceptionType.java
> +@RequiredArgsConstructor
생성자 접근 범위를 `private`으로 자동으로 만들어주나요? 갑자기 헷갈리네요 ㅎ..

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/exception/CoordinateExceptionType.java
> +    INVALID_Y_ERROR("COORDINATE-100", "위도 값의 크기가 잘못되었습니다.");
동일한 코드 발견

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +    public Optional<Store> findByAddress(String address) {
어디서 사용되는 메서드인가요? 🤔

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/SchoolService.java
> +    public Optional<School> findByName(String name) {
어디서 사용되는 메서드인가요? 🤔

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/exception/FileException.java
> +    }
`Throwable`을 받을 수 있는 생성자도 있으면 좋을 것 같아요 :)

2023-08-14 17:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
`FileException` 처리를 안하고 있어요 선생님 🦅

2023-08-16 04:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
상속 관계의 구조에서는 Bean validation이 필요한 컨트롤러는 동일하게 설정해주어야 합니다!
BeanValidation 레퍼런스에 나와있더라구욥

설정을 제거하면 다음과 같은 예외가 발생합니다.
```java
ConstraintDeclarationException: HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method ReviewController#create(ReviewCreateRequest, List, Member) redefines the configuration of ReviewControllerDocs#create(ReviewCreateRequest, List, Member)
```

2023-08-16 04:39 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +            @Size(max = 4, message = "사진의 개수는 최대 4개까지 가능합니다.") List<MultipartFile> imageFiles,
현재 서비스에서 `@ModelAttribute`를 사용했을 때 크게 장점을 느끼지 못했습니당

ModelAttribute가 새롭게 필드가 추가되었을 때 유연성을 가져갈 수 있을 것 같은데, 지금 상황에서는 RequestPart도 충분하고 가독성을 생각하면 더 직관적이라고 생각해서 RequestPart를 사용했습니다

2023-08-16 04:40 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        @Schema(description = "가게 이름", example = "맥도날드 강남점", requiredMode = REQUIRED)
신기한게 또 NotNull을 보고도 자동으로 넣어주더라구요?
그래도 특정 라이브러리에 의존하는 것보다 명시적으로 넣어주는게 좋을 것 같아서 넣었슴다 ~

2023-08-16 04:41 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +        return ResponseEntity.created(URI.create("/v1/reviews/" + reviewId)).build();
저도 이게 좀 애매한 것 같은데, created 응답으로 location을 안줘도 괜찮을까욥?
HTTP 프로토콜에 좀 어긋나는 것 같아서용. 그래도 없는 API를 보여주는 것보다는 나은 것 같네요 ㅎㅎ

아니면 OK 반환?

2023-08-16 04:42 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        BigDecimal y,
저희 도메인에서 해당 값 검증을 해주기로 컨벤션 정했지 않나용?
그래서 값객체를 도입했다고 생각합니다 ㅎㅎ

Request에서는 Null 검증만 진행하구요 !

2023-08-21 06:19 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
보투게더에서는 어떻게 하셨나요?!!? 궁금하네용

2023-08-21 06:22 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +@Transactional(readOnly = true)
넴넴 좋습니다 ! 반영할게용

2023-08-21 06:28 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +    private final PhotoService photoService;
서비스 계층만 가지는 한 단계 더 추상화된 클래스를 말씀하시는거죵?!

좋습니다 ~

2023-08-21 06:38 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        );
Request가 Controller -> Service 까지 내려온 상황에서 Dto 내부까지 전달하기가 쪼오끔 그렇더라구요..?
그래서 ReviewService 내부에서 생성자로 생성해주는게 낫지 않을까 생각했습니다 ~

2023-08-21 06:53 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +    private Store convertToStore(StoreCreateDto storeCreateDto) {
저는 public 메서드와 private 메서드를 우선 구분하고, 그 이후에 private 메서드가 호출되는 순서로 코드를 작성합니다 ㅎㅎ

코드 작성하실 때 private 메서드라도 public 바로 아래에 두는 것을 선호하시나요 ?! 😀

2023-08-21 07:02 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        storeRepository.findByAddress_AddressName(storeCreateDto.address()).ifPresent(
저희 서비스가 카카오에서 조회한 가게 정보를 받아서 이 가게가 있는지 없는지 서버 내에서 판단을 하는데요 !

이 과정에서 가게를 확실하게 식별할 수 있는 식별자가 없습니다.
그래서 지난번 가게 생성과 관련된 회의를 할 때 주소로 조회하자는 의견이 나왔었습니다.

카카오 API를 살펴보니 `장소 ID`를 제공하는 것 같은데, 이 데이터를 사용하도록 변경해야 할 것 같네요 ~

2023-08-21 07:02 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        return storeRepository.findByAddress_AddressName(address);
`ditto`

2023-08-22 05:55 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Store store = storeService.create(storeCreateDto);
헉 큰일날뻔 했네요 ㅎㅎ

반영했습니다 !

2023-08-22 05:56 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +            String schoolName = storeCreateDto.schoolName();
일관성있게 수정했슴당

2023-08-22 08:49 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +    private void saveImagesIfExists(List<MultipartFile> images, Store store, Review review) {
분리완료 !

2023-08-22 09:02 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +        File directory = loadDirectory(rootDirectory + SLASH + parentDirectory);
`디렉토리 명`이라서 한글이 접근하기 쉽지 않을까 생각했는데, 가게 이름이 변경되면 문제가 생길 것 같군요 ㅎㅎ
가게 ID를 사용하는 것으로 변경했습니다 ~

System.getProperty("user.dir")은 처음 알았네요 ㅎㅎ 좋아요 !

2023-08-22 09:08 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +            }
이미지 4개가 요청으로 들어왔을 때, 하나가 잘못되더라도 나머지는 올바르게 저장되는게 사용자가 느끼기에 더 자연스러울 것 같다는 생각을 했습니다 ! 

예를 들어 사용자가 사진 4개와 함께 리뷰를 작성했다 -> 사진 1개가 문제 있음 -> 사진 3개는 올바르게 저장 -> 사용자는 하나가 안들어갔네? 생각 후 사용자가 스스로 판단해 1개 추가 저장 or 그냥 3개만 냅두기

2023-08-22 09:15 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +        return fileBaseName + DASH + System.currentTimeMillis() + DOT + extension;
파일명은 좋은 것 같네요 ㅎㅎ 굳이 원본 파일을 가져갈 필요는 없을 것 같습니다 !

확장자는 확장자의 원리를 잘 몰라서,,, 🥲 기존 원본 파일 확장자를 임의로 변경했을 때 사이드 이펙트를 예측할 수 없을 것 같아 그대로 저장했습니다.

png, jpg 등 여러 이미지 확장자를 그대로 저장했을 때 문제가 없을 것 같은데 큰 이유가 없다면, 확장자를 임의로 변경해서 불안 요소가 생기는 것보다 낫지 않을까요?!

2023-08-22 09:35 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        Store store = storeRepository.save(convertToStore(storeCreateDto));
74번째 라인에서 학교가 존재하는지 확인 후 없으면 생성하고 있는데...! 어떤 라인을 말씀하시는건가욥??!

2023-08-22 09:45 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/exception/FileException.java
> +    }
추가 완 ~

2023-08-22 09:45 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +    public Optional<Store> findByAddress(String address) {
삭제 완 ~

2023-08-22 09:46 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/exception/CategoryExceptionType.java
> +@RequiredArgsConstructor
아뇽 ㅎㅎ

일관성있게 생성자 직접 추가했습니당

2023-08-22 09:47 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/exception/CoordinateExceptionType.java
> +    INVALID_Y_ERROR("COORDINATE-100", "위도 값의 크기가 잘못되었습니다.");
동일한 코드를 사용한 상태에서, 위도 경도에 따라 메세지를 분리하려고 했는데요... 요렇게 쓰는 느낌이 아니었나욥?

2023-08-22 09:48 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/SchoolService.java
> +    public Optional<School> findByName(String name) {
가게 서비스에서 요청으로 들어온 학교이름에 해당하는 학교가 존재하는지 확인하는 메서드입니닷

2023-08-22 09:49 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
헉..!

2023-08-22 10:39 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
추가했습니다 😀

2023-08-22 14:56 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
말씀하신대로 `Bean Validation`은 인터페이스에도 동일하게 적용해주어야 에러가 발행하지 않더라고요. 덕분에 배워갑니다 ㅎㅎ

`Bean Validation`인 `@Size`를 제외하고는 제거해도 동작하지 않나요? 🤔 보투게더에서도 문서화를 위한 인터페이스이기에 이외의 정보는 최대한 제거하는 방향으로 진행했습니다!

2023-08-22 14:58 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +            @Size(max = 4, message = "사진의 개수는 최대 4개까지 가능합니다.") List<MultipartFile> imageFiles,
답변 감사합니다 좋은 근거인 것 같습니다 👍

2023-08-22 16:04 UTC, woo-chang reviewed
리뷰 반영사항을 너무 꼼꼼히 잘 반영해주셨네요 👍

이전 리뷰의 답변과 추가적인 소소한 리뷰 몇 가지만 더 남겼습니다

거의 다 온 것 같으니 조금만 더 화이팅입니다 ㅎㅎ

---

추가적으로 `Discussion`도 확인 한번만 부탁드릴께요~~

https://github.com/Busan-Dinosaur/Foodbowl-Backend/discussions/113
https://github.com/Busan-Dinosaur/Foodbowl-Backend/discussions/111

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
```suggestion
            @Auth Member member);
}
```
```suggestion
            @Auth Member member
    );
}
```
개행부탁드려요~~

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        @Schema(description = "가게 이름", example = "맥도날드 강남점", requiredMode = REQUIRED)
다른 사람도 이해하기 쉽게 저도 최대한 명시하는 것을 좋아합니다~~

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/Address.java
>      private BigDecimal y;
`Address` 안의 `x`, `y`는 `Coordinate`로 검증하지 않는 이유가 있으신가요? 😀

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        storeRepository.findByAddress_AddressName(storeCreateDto.address()).ifPresent(
완전한 식별자가 될 수 있고, 유니크 컬럼 설정을 통해 인덱스까지 챙겨갈 수 있어서 훨씬 좋은 것 같아요 👍😙

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +    private Store convertToStore(StoreCreateDto storeCreateDto) {
저는 `private` 메서드가 아래에 있어야 어디있는지 찾을 필요없이 바로 아래만 확인하면 되서 훨씬 읽기 편하더라구요!

1개의 public 메서드에서만 사용되는 private 메서드는 public 메서드 아래에 두고, 공용으로 사용되어 2개 이상 public 메서드에서 사용되는 private 메서드는 그레이가 선호하는 것처럼 최하단에 두는 방법은 어떨까요?!

최하단에 두더라도 호출되는 public 메서드의 순서에 따라 private 메서드의 순서도 정해지면 좋을 것 같아요 ㅎㅎ

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +        }
사소하지만 `batch insert`를 적용해보는건 어떨까요?!

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +            }
조금 더 사용자 편의성을 위한 접근 방식이었군요 👍 말씀하신 방법이 더욱 자연스러울 것 같습니다 ㅎㅎ

```java
private static boolean isNotImageFile(MultipartFile file) {
    try (InputStream originalInputStream = new BufferedInputStream(file.getInputStream())) {
        return ImageIO.read(originalInputStream) == null;
    } catch (IOException e) {
        throw new BusinessException(file, "photo", PHOTO_FILE_READ_FAIL);
    } catch (NullPointerException e) {
        throw new BusinessException(file, "photo", PHOTO_NULL_IMAGE_FILE);
    }
}
```

이전에 사용했던 코드인데 `ImageIO.read` 메서드를 통해 이미지 파일인지 검증할 수 있습니다! `MultipartFile`이 이미지 파일이 아니라면 `null`이 반환되게 되는데 이를 통해 이미지 파일인지 검증할 수 있었던 것 같습니다 ㅎㅎ

`NullPointerException`은 필요한지 잘 모르겠네요 🤔

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +        return fileBaseName + DASH + System.currentTimeMillis() + DOT + extension;
확장자를 그대로 저장하지 않았을 때 사이드 이펙트가 발생할 수 있겠네요 🤔

좋은 의견 감사합니다 ㅎㅎ

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoService.java
> +public class ReviewPhotoService {
`StoreSchool`는 `Repository`를 활용하고 `ReviewPhoto`는 `Service`를 만드신 이유가 궁금합니다 :)

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        Store store = storeRepository.save(convertToStore(storeCreateDto));
학교가 DB에 존재하지 않을 때만 생성해서 가게와 연결시켜주고 있는 것으로 이해했습니다!

1. 요청으로 학교 이름이 들어오지 않았을 때, 학교 이름을 찾지도 StoreSchool을 생성하지도 않는다.
2. 요청으로 학교 이름이 들어왔을 때
  1. 학교 이름이 DB에 존재하면, StoreSchool만 생성한다.
  2. 학교 이름이 DB에 존재하지 않으면, School 생성 후 StoreSchool을 생성한다.

현재 로직에서는 1번과 2-2번만 수행하고 있는 것 같아서 2-1번 상황일 때 예외가 발생할 것 같은데 제가 잘못 이해했다면 답변 달아주시면 감사하겠습니다 🙇🏻‍♂️

2023-08-22 16:04 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/exception/CoordinateExceptionType.java
> +    INVALID_Y_ERROR("COORDINATE-100", "위도 값의 크기가 잘못되었습니다.");
추후에 로깅을 도입하여 에러 코드로 로그를 분류하고자할 때 경도에 의한 에러와 위도에 의한 로그가 함께 보여도 괜찮을까요? 에러 코드로 로그를 분류화하려고 했는데 위의 상황이 괜찮다면 저는 좋은 것 같습니다 ㅎㅎ

2023-08-23 04:10 UTC, woo-chang requested changes
테스트도 너무 꼼꼼히 잘 작성해주셨네요 👍👍

코드량이 많았음에도 하나하나 꼼꼼히 읽을 수 있게 작성해주셔서 재밌게 리뷰했습니다~

몇 가지 질문과 커멘트 남겨두었으니 확인 부탁드릴께요 🔥

2023-08-23 04:10 UTC, woo-chang commented on src/main/resources/application.yml
> +      max-request-size: 5MB
1. 파일 크기를 `5MB`로 줄인 이유가 궁금합니다 😙
2. 요청 크기를 `5MB`로 설정하면 사진 1장당 `2MB`라고 했을 때 4장 다 받지 못하는 상황이 발생하지 않을까요? 요청 본문의 데이터 크기도 추가적으로 고려가 필요할 것 같습니다 :)

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/file/FileTestUtils.java
> +public class FileTestUtils {
테스트에서만 사용되는 유틸 클래스인 것 같은데 테스트용 클래스인 `test` 디렉토리로 옮기는건 어떨까요?!

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/file/FileTestUtils.java
> +        }
```suggestion
        for (int i = 0; i < size; i++) {
            MockMultipartFile file = new MockMultipartFile(
                    "images",
                    "foodBowl.jpg",
                    MediaType.TEXT_PLAIN_VALUE,
                    "Hello Images".getBytes()
            );
            multipartFiles.add(file);
        }
```
사소하지만 요런 코드 컨벤션은 어떤가요? 😙

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/file/FileTestUtils.java
> +        }
```suggestion
        for (int i = 0; i < size; i++) {
            MockMultipartFile file = generateMockMultiPartFile();
            multipartFiles.add(file);
        }
```
아래의 메서드도 재활용한다면 이렇게도 할 수 있을 것 같아요 :)

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/file/FileTestUtils.java
> +    }
이렇게 하나하나 지워줘야 하는건가요? 한번에 지울 수 있는 방법이 없나요? 🥲

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +class PhotoLocalUploaderTest extends IntegrationTest {
통합 테스트를 사용하신 이유가 궁금합니다!

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +        List<MultipartFile> multipartFiles = List.of(multipartFile);
잘 만들어주신 `FileTestUtils`를 활용해보는건 어떨까요~~

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +        assertThat(filePaths).isNotEmpty();
지정한 경로에 파일이 있는지에 대한 검증은 필요하지 않을까요? 🤔

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +    @ValueSource(strings = {"foodBowl.zip", "foodBowl.pdf", "foodBowl.docx", "foodBowl.pptx"})
```suggestion
    @ParameterizedTest
    @ValueSource(strings = {"foodBowl.zip", "foodBowl.pdf", "foodBowl.docx", "foodBowl.pptx"})
```
```suggestion
    @ValueSource(strings = {"foodBowl.zip", "foodBowl.pdf", "foodBowl.docx", "foodBowl.pptx"})
    @ParameterizedTest
```
`@Test`가 밑으로 오도록 하는 컨벤션 어떠신가요? ㅎㅎ

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +    @ValueSource(strings = {" "})
```suggestion
    @NullAndEmptySource
    @ValueSource(strings = {" "})
    @ParameterizedTest
```
`ditto`

`@Source`를 여러 개 사용할 수 있나요???

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +    @ValueSource(strings = {"foodBowlZip", "helloWorld", "javaSpring"})
`ditto`

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoServiceTest.java
> +        assertDoesNotThrow(() -> photoService.save(multipartFiles, "parentDirectory"));
반환되는 결과의 개수가 3개인지 비교해보는건 어떨까요 :)

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoRepositoryTest.java
> +        assertThat(savePhoto).isNotNull();
저장 메서드까지 꼼꼼히 테스트해주셨네요 👍

`savePhoto`는 항상 `Null`이 아닐 것 같은데, `ID`가 `Null`이 아닌지 테스트가 필요할 것 같아요 ㅎㅎ

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoRepositoryTest.java
> +class ReviewPhotoRepositoryTest extends PersistenceTest {
무엇인가 빠져있지 않나요~~

2023-08-23 04:10 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoService.java
> +    public void save(Review review, List<Photo> photos) {
어떤 `Service`에서는 저장 시 저장한 객체를 반환한 것도 있는데 어떤 기준으로 반환값을 결정하셨는지 궁금합니다 🤓

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +@WebMvcTest(controllers = ReviewController.class)
요기도 컨벤션으로 맞추면 좋을 것 같은데 `controllers`를 붙이는게 좋을까요?!

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    }
현재 `develop` 브랜치 병합해서 작업하시면 `PresentationTest`의 `mockingAuthMemberInResolver`를 통해 각 테스트마다 mocking한다는 것 명시적으로 나타낼 수 있습니다 ㅎㅎ

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                    objectMapper.writeValueAsBytes(reviewCreateRequest));
생성자 각 인자가 무엇을 의미하는지 설명해주시면 감사합니다 🙇🏻‍♂️

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +            MockMultipartFile multipartFile2 = (MockMultipartFile) FileTestUtils.generateMockMultiPartFile();
`MultipartFile`을 사용하지 않고 형변환을 하신 이유가 궁금합니다!

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                    .willReturn(1L);
`given` 절은 `mockMvc.perfom` 위에다 두는게 어떨까요? 그래야 어떤 서비스 메서드를 mocking하는지 더 잘보이더라구요~

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .characterEncoding(StandardCharsets.UTF_8))
```suggestion
                            .file(request)
                            .file(multipartFile1)
                            .file(multipartFile2)
                            .header("Authorization", "Bearer " + accessToken)
                            .characterEncoding(StandardCharsets.UTF_8))
```
```suggestion
                            .header("Authorization", "Bearer " + accessToken)
                            .characterEncoding(StandardCharsets.UTF_8)
                            .file(request)
                            .file(multipartFile1)
                            .file(multipartFile2))
```
요것도 사소하지만 헤더를 위로 올리는 건 어떠신가요 :)

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                    .willReturn(1L);
`ditto`

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .characterEncoding(StandardCharsets.UTF_8))
`ditto`

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +                "Hello Images".getBytes());
```suggestion
        MockMultipartFile multipartFile =
                new MockMultipartFile("bucket", "foodBowl.jpg", MediaType.TEXT_PLAIN_VALUE, "Hello Images".getBytes());
```

```suggestion
        MockMultipartFile multipartFile = new MockMultipartFile(
                "bucket",
                "foodBowl.jpg",
                MediaType.TEXT_PLAIN_VALUE,
                "Hello Images".getBytes()
        );
```
매개변수가 많거나 길어서 짤리게 되면 위의 2가지 방법 중 적절한 것으로 개행 부탁드립니다 😙

테스트 전반적으로 한번 확인해주시면 감사합니다 ✅

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                    .willReturn(1L);
요것도 정해지면 테스트 전반적으로 확인 부탁드리겠습니다 ✅

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +    @ValueSource(strings = {"foodBowl.zip", "foodBowl.pdf", "foodBowl.docx", "foodBowl.pptx"})
요것도 정해지면 테스트 전반적으로 확인 부탁드리겠습니다 ✅

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .characterEncoding(StandardCharsets.UTF_8))
요것도 정해지면 테스트 전반적으로 확인 부탁드리겠습니다 ✅

2023-08-23 04:10 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        String category,
클라이언트에서 카테고리 목록을 조회함에 따라 `ID`로 올 것 같은데 이 부분은 어떻게 생각하시나요? 🤔

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/SchoolServiceTest.java
> +@SpringBootTest
요것은 무엇인가효 ㅎㅎ

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/SchoolServiceTest.java
> +            assertThat(school).isNotNull();
여기도 `ID`가 `NotNull`인지 검증이 필요할 것 같아요 :)

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    class 리뷰_작성_시_ {
맨 마지막에 `_`를 남겨두시는 이유가 무엇인가요?

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/SchoolServiceTest.java
> +        void 이미_학교가_존재하면_예외_발생() {
어떤 테스트명은은 `동사형`으로 끝나고 여기서는 `명사형`으로 끝나는데 동사형으로 통일시키는건 어떨까요?!

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/SchoolServiceTest.java
> +        void 이미_학교가_존재하면_예외_발생() {
이 부분도 정해지면 전체적으로 확인 부탁드릴께요 ✅

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
> +    }
같은 메서드를 테스트하는 것 같은데 `@Nested`로 묶어도 좋을 것 같아요 ㅎㅎ

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    }
꼼꼼한 테스트 체고 👍👍

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/domain/vo/SchoolNameTest.java
> +class SchoolNameTest {
여기도 무엇인가 빠져있어요~~

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/persister/PhotoTestPersister.java
> +}
불필요한 개행이 들어가있네요 :)

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/persister/PhotoTestPersister.java
> +        }
```suggestion
        public Photo save() {
            Photo photo = Photo.builder()
                            .path(path == null ? String.valueOf(System.currentTimeMillis()) : path)
                            .build()
            return photoRepository.save(photo);
        }
```
이렇게 해주는게 가독성이 더 좋더라구요 👍

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/persister/ReviewTestPersister.java
> +            );
`ditto`

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/persister/ReviewTestPersister.java
> +            );
`Builder`에서 `content`는 안받는 이유가 궁금합니다!

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/persister/SchoolTestPersister.java
> +            );
`ditto`

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/persister/SchoolTestPersister.java
> +            );
`School`에서는 각각 필드 전부 다 안받는 이유가 궁금합니다 :)

2023-08-23 04:10 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/persister/StoreTestPersister.java
> +            );
여기도 동일한 적용사항과 동일한 질문입니다 🤓

2023-08-23 11:23 UTC, Kim0914 commented on src/main/resources/application.yml
> +      max-request-size: 5MB
파일 크기는 프론트와 회의할 때 평균적으로 2MB 정도라고 해서 여유롭게 5MB로 잡았습니다 !

`max-request-size`는 파일 여러개를 모두 합친 **하나의 요청**에 발생하는 파일 크기이군요~ 변경해야겠네요 !

2023-08-23 11:27 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
DTO를 검증하는 `@Valid`외 `@Size` 두개만 있으면 되네요 ㅎㅎ

2023-08-23 11:46 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/exception/CoordinateExceptionType.java
> +    INVALID_Y_ERROR("COORDINATE-100", "위도 값의 크기가 잘못되었습니다.");
저는 경도, 위도 값이 잘못된 상황이 `위치 값을 입력할 때` 요청 값을 잘못 전달하는 상황이라고 생각이 들어요 ~

예를 들어 파일 확장자가 잘못된 경우, 이미지 파일이 아닌 파일이 들어온 경우, 파일 이름이 없는 경우 와 같은 경우들은 크게 분리해도 될 것 같더라구요. 

경도 & 위도는 한 좌표 내에 있는 값이기 때문에 동일한 코드로 찍어줘도 될 것 같아요 !

2023-08-23 11:50 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/FileSystemPhotoUtils.java
> +            }
좋아요 ~ 반영했습니다.

NullPointerException은 굳이 필요없는 것 같아서 (I/O 과정의 예상치 못한 예외만 핸들링 하면 될 것 같음) 추가하지 않았습니다 !

2023-08-23 12:23 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        Store store = storeRepository.save(convertToStore(storeCreateDto));
아하아하 이해했습니다 ㅎㅎ

다음과 같이 수정했습니다 !

```java
private void saveSchool(Store store, String schoolName, BigDecimal schoolX, BigDecimal schoolY) {
        School school = schoolService.findByName(schoolName)
                .orElseGet(() -> schoolService.save(schoolName, schoolX, schoolY));

        storeSchoolRepository.save(StoreSchool.builder()
                .store(store)
                .school(school)
                .build()
        );
    }
```

2023-08-23 12:29 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/domain/vo/Address.java
>      private BigDecimal y;
없..습니다 ㅎㅎ 놓친 부분이에요 ~

추가했습니다 !

2023-08-23 12:36 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +        }
현재 프로덕션 코드내에서 photo는 모두 List로 넘겨주고 받아서 저도 동의합니다 ㅎㅎ

하지만 저희가 `Repository`를 사용하고 있어서 기본적으로 saveAll은 지원하지 않습니다.

생각나는 방법이 2가지가 있는데요 !

1. JPQL로 작성한다
2. QueryDsl을 이용해 batch insert 한다.

위 2가지 방법을 선택하면 구현할 수 있는데, 지금 구현하는 것이 좋을까요 아니면 추후에 고도화할 때 반영하는게 좋을까요?!

2023-08-23 12:56 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoService.java
> +public class ReviewPhotoService {
매핑 테이블을 하는 엔티티까지 서비스로 추가해야될까 고민했는데 일관성 있게 추가해주는 방향으로 수정했습니다 ~

2023-08-23 13:02 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/file/FileTestUtils.java
> +    }
저도 꽤 찾아봤는데, 생성된 파일과 연관된 것들을 모두 삭제하려면 (디렉토리, 디렉토리 내부 파일) 해당 방법을 사용하더라구요 !

테스트에서 file이 위치한 디렉토리부터 하위 항목을 모두 삭제합니당

테스트 코드에서만 사용되는 코드라서 사용해도 무방하지 않나 싶습니다 :)

2023-08-23 13:11 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +class PhotoLocalUploaderTest extends IntegrationTest {
사진을 저장하는 기능 자체에서 PhotoService보다 PhotoUpload의 역할이 더 크다고 생각했습니다 !

또한 리뷰를 저장하는 부분에서도 핵심 기능인 만큼 통합 테스트를 사용하는게 나을 것 같았습니다 ㅎㅎ

다른 의견이 있으면 말씀해주시면 감사하겠습니다 (__)

2023-08-23 13:34 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +    @ValueSource(strings = {" "})
넹 사용할 수 있더라구욥

![image](https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/68818952/29fe6e6c-87d4-43e6-bb72-566290b47e5e)

2023-08-23 13:35 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +    @ValueSource(strings = {"foodBowl.zip", "foodBowl.pdf", "foodBowl.docx", "foodBowl.pptx"})
ValueSource가 아래에 있는게 더 읽기 좋지 않나욥?

어떤 테스트다 -> 어떤 source를 사용할 것이다 처럼 자연스럽게 읽혀서요 !

2023-08-23 13:42 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoService.java
> +    public void save(Review review, List<Photo> photos) {
1. 최상위 서비스 (Review)는 엔티티를 반환하지 않고 PK만 반환하도록 했습니다.
2. 중간 서비스(Store..)는 엔티티를 반환해서 상위 서비스에서 사용할 수 있도록 했습니다.
3. 매핑 테이블(StoreSchool, ReviewPhoto)는 엔티티가 자체가 의미가 없기 때문에 반환할 필요가 없어서 void로 반환했습니당.

2023-08-23 13:47 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoRepositoryTest.java
> +        assertThat(savePhoto).isNotNull();
Repository에서 저장 후 반환하는 엔티티인데 savePhoto가 null이 아닌 경우가 있을까요?!
중간에 사진 저장이 제대로 안된 경우(파일이 100% 제대로 저장를 말씀해 주시는 건가요 ㅎㅎ

ID로 검증하는게 더 꼼꼼하기 때문에 우선 반영하겠습니다 ~

2023-08-23 13:48 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +@WebMvcTest(controllers = ReviewController.class)
저는 항상 명시적인 부분은 꼭 남겨주는 것이 좋다고 생각합니다 ㅎㅎ

컨트롤러 테스트의 경우에는 단일 컨트롤러만 테스트하기 때문에 굳이 없어도 되겠네요 ~

2023-08-23 13:49 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    }
리뷰 모두 마친 다음 conflict 해결하면서 한번에 반영할게요 ~

2023-08-23 13:51 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                    objectMapper.writeValueAsBytes(reviewCreateRequest));
`"request"`: 컨트롤러에서 바인딩되는 필드 명
`""`: 파일명 (json값이기 때문에 필요없음)
`"application/json"`: requestPart로 요청보낼 때 media type
`objectMapper.writeValueAsBytes(reviewCreateRequest)`: json 값

입니다 !

2023-08-23 13:53 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                    .willReturn(1L);
좋아용 ~

2023-08-23 13:57 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +            MockMultipartFile multipartFile2 = (MockMultipartFile) FileTestUtils.generateMockMultiPartFile();
mockMvc의 file 필드에는 `MockMultipartFile`를 명시적으로 받아서 형변환을 했습니다 !

현재 FileTestUtils에서는 서비스 계층에서도 사용할 수 있도록 `MultipartFile`을 반환하고 있습니다.

그래서 다운 캐스팅 했습니다 !

2023-08-23 14:05 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .characterEncoding(StandardCharsets.UTF_8))
![스크린샷 2023-08-23 오후 11 03 42](https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/68818952/0e22ff1a-aa85-4685-b089-111db61e5e0e)

체이닝하는 대상이 바뀌어서 file이 먼저 위치해야 합니다 ㅎㅎ

2023-08-23 14:06 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/SchoolServiceTest.java
> +@SpringBootTest
ㅋㅋㅋ 컷!

2023-08-23 14:11 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    class 리뷰_작성_시_ {
테스트 명을 한글로 작성하는게 띠어쓰기 기준 아닌가욤?
아니면 메서드 명을 시작할 때 `_`로 시작해야하는데 그건 안되서...?

2023-08-23 14:17 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        String category,
저는 아직까지 조금 애매한게 카테고리는 자원의 ID로 주고 받는 것이 아닌 정해진 코드나, 이름으로 주고 받는게 적절하지 않나 생각이 들어요. 왜냐하면, 카테고리라는 의미를 넓게 보면 필터링의 의미도 가진다고 봐요 !

저희 서비스의 지도 상에서 카테고리를 눌러서 보는 것 && 가게에 카테고리를 저장하는 것 -> 필터링을 위함

우리가 필터링을 위해 파라미터 값을 주고 받을 때, 디비 자원의 ID를 주고 받지 않는 것처럼요.

프론트에서 저희 서버가 가지고 있는 카테고리를 모두 조회해서 사용하는 부분은 괜찮은 것 같은데, 카테고리를 주고 받을 때도 PK를 이용해 주고 받아야 할까욥?!

추가적으로 현재 서버 코드 내에도 CategoryType의 enum 객체를 이용해 PK와 매핑하고 있기 때문에 큰 문제가 없을 것 같은데 어떻게 생각하시나요? ㅎㅎ

2023-08-23 14:18 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/SchoolServiceTest.java
> +        void 이미_학교가_존재하면_예외_발생() {
명사형으로 통일합시다 ~

2023-08-23 14:24 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/test/persister/ReviewTestPersister.java
> +            );
내용이 크게 중요하지 않은 것 같아서 놔뒀는데 일관성 있게 넣었습니다 ~

2023-08-23 14:25 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/test/persister/SchoolTestPersister.java
> +            );
`ditto`

2023-08-23 14:27 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/test/persister/StoreTestPersister.java
> +            );
`ditto`

2023-08-24 03:01 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
`@Valid`도 없어도 되지 않나요? (진짜 모름)

2023-08-24 03:15 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +        }
`Repository`가 `saveAll`은 구현체를 자동으로 만들어주지 않나 보네요 🤓 하나 알아갑니다

지금 당장 적용해도 괜찮을 것 같아서 지금 적용해보는건 어떨까요? 구구 코치의 말씀대로 런타임에 오류를 확인할 수 있는 `JPQL`보다는 컴파일 타임에 에러를 발견할 수 있는 `Querydsl`을 통해 구현하는 것이 좋을 것 같아요 ㅎㅎ

2023-08-24 03:17 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +class PhotoLocalUploaderTest extends IntegrationTest {
좋은 의견입니다 👍

2023-08-24 03:19 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +    @ValueSource(strings = {"foodBowl.zip", "foodBowl.pdf", "foodBowl.docx", "foodBowl.pptx"})
설득당했습니다 :)

2023-08-24 03:20 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoService.java
> +    public void save(Review review, List<Photo> photos) {
확인했습니다 좋아요 👍

2023-08-24 03:51 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .characterEncoding(StandardCharsets.UTF_8))
`multipart` 요청을 많이 사용해보지 않았는데, 체이닝하는 대상이 달라지네요 🤓 하나 배워갑니다~~

2023-08-24 03:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/ReviewCreateRequest.java
> +        String category,
카테고리 이름으로 `DB` 조회를 거쳐야하는 상황이라면 모르겠는데 현재는 `Enum`으로 관리하고 있기 때문에 변환에도 큰 리소스가 들 것 같지 않네요! 설득당했습니다 👍

2023-08-24 03:56 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    class 리뷰_작성_시_ {
<img width="365" alt="스크린샷 2023-08-24 오후 12 56 03" src="https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/78212016/f9a945c7-6747-459d-aeec-012fc9b863e9">

요렇게 나오는데 마지막에 공백이 필요한지 궁금했습니다!

2023-08-24 04:03 UTC, woo-chang approved these changes
너무너무 수고하셨습니다 🙇🏻‍♂️
꼼꼼히 잘 반영해주셔서 `approve` 하도록 하겠습니다!
커멘트 답변 한번씩만 더 확인해주시고 필요한 부분만 반영해주시면 감사합니다 ㅎㅎ

2023-08-24 06:00 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    class 리뷰_작성_시_ {
그러네요?! 빼도 되겠습니다 ㅎㅎ

2023-08-24 06:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +}
`@Valid`는  Bean Validation이 아니어서 상관없을 것 같았는데, 제거하니까 예외가 발생하더라구요 🥲

`HV000151: A method overriding another method must not redefine the parameter constraint configuration, but method ReviewController#create(ReviewCreateRequest, List, Member) redefines the configuration of ReviewControllerDocs#create(ReviewCreateRequest, List, Member)`

2023-08-24 06:17 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploaderTest.java
> +        assertThat(filePaths).isNotEmpty();
요 부분을 누락했었네용?

바로 추가했습니다 ㅎㅎ

2023-08-24 06:53 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +    }
반영완료 ^^

2023-08-24 08:11 UTC, merged