Feature/#118 리뷰 삭제 기능
Busan-Dinosaur/Foodbowl-Backend pull request #158
Opened 2023-08-29 09:56 UTC by Kim0914

## 🔥 연관 이슈

close: #118 

## 📝 작업 요약
- 리뷰 삭제 기능을 구현했습니다.

## 🔎 작업 상세 설명

- 리뷰 삭제 흐름은 다음과 같습니다.

1. 요청으로 들어온 리뷰가 존재하는지 확인
2. 리뷰 작성자와 일치하는지 확인
3. 리뷰와 관련된 사진 삭제
4. 리뷰와 관련된 리뷰 포토 삭제
5. 리뷰와 관련된 포토 삭제
6. 리뷰 삭제

## 🌟 리뷰 요구 사항

> 20분 !

2023-08-29 14:26 UTC, woo-chang requested changes
전반적으로 깔끔하게 잘 구현해주셨네요 👍👍

궁금한 점과 소소한 커멘트 남겨두었으니 확인 부탁드립니다 🙇🏻‍♂️

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +            @ApiResponse(responseCode = "204", description = "리뷰 삭제 성공"),
```suggestion
            @ApiResponse(
                    responseCode = "204",
                    description = "리뷰 삭제 성공"
            ),
```
개행 주는 것이 다른 코드와 컨벤션도 맞고 가독성도 좋더라구요 😀

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                            """,
나의 리뷰가 아닌 경우도 `BadRequestException`이 발생하는 것으로 되어있기에 이 부분도 추가하면 좋을 것 같아요 :)

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .orElseThrow(() -> new BadRequestException(NOT_FOUND_ERROR));
`NotFoundException`이 발생해야하지 않을까요?! 🤓

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        if (review.isNotOwnerOf(member)) {
```suggestion
        if (!review.isOwnerOf(member)) {
```
긍정문 메서드로 만들고 `!`를 붙이는 방법도 있는데, 부정 메서드를 선택하신 이유가 궁금합니다!

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .orElseThrow(() -> new BadRequestException(NOT_FOUND_ERROR));
`ExceptionType`마다 `ERROR POSTFIX`를 붙이시는 것 같은데 이 부분도 통일하면 좋을 것 같아서 붙이는 것이 좋으신가요? 이유도 함께 설명해주시면 감사합니다 ㅎㅎ

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        reviewRepository.delete(review);
많이 고민하신만큼 깔끔한 코드가 나온 것 같네요 👍

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/domain/Review.java
> +        return !Objects.equals(this.member, member);
도메인의 필드를 검증할 때 도메인에서 예외를 발생시키는 방법과 `boolean` 값을 반환 후 `Service`에서 예외를 발생시키는 방법 2가지가 있는데, 어떤 기준으로 2가지 방법 중에서 선택하시는지 궁금합니다 :)

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/exception/ReviewExceptionType.java
> +@RequiredArgsConstructor
직접 생성자를 정의하는 것으로 통일성을 맞춰보는건 어떨까요?!

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoRepository.java
> +public interface ReviewPhotoRepository extends Repository<ReviewPhoto, Long>, ReviewPhotoCustomRepository {
`ReviewPhotoCustomRepository`를 따로 분리해서 사용하는 방법도 있을텐데 `ReviewPhotoRepository`가 같이 구현하도록 하신 이유가 궁금합니다 🤔

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoCustomRepositoryImpl.java
> +    }
구현하신 이유가 `Repository`의 `deleteBy`나 `deleteAllBy`를 사용하면 `select` 이후 `delete` 쿼리가 각각 나가는 것 때문에 그런 것인 것으로 이해했습니다 👍

어떤 이유 때문에 그렇게 구현되어 있는지 아시나요? 🤔

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoCustomRepositoryImpl.java
> +    }
여기도 동일한 이유로 `Querydsl`로 구현했다고 이해하면 될까요?!

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoRepository.java
> +    List<ReviewPhoto> findAllByReview(Review review);
`RCUD` 순서 맞춰주시면 감사합니다 ㅎㅎ

테스트, 서비스, 컨트롤러에서도 전체적으로 확인해주시면 감사합니다 🙇🏻‍♂️

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalManager.java
> +    }
테스트에서는 잘 동작하지만 개발 서버에서는 잘 동작하지 않을 수도 있을 것 같다는 생각이 드네요 🤔

현재 `DB`에 저장되어 있는 `path`는 `URL`이 붙은 `https://justdoeat.shop/static/images/1/image.png`와 같은 형태입니다. 스프링 애플리케이션은 도커 컨테이너 내부에서 돌아가고 있기에 해당 경로에 삭제 요청을 하게 되면 호스트의 실제 이미지 경로에 접근하게 되고 아마 권한 부족으로 삭제되지 않을 것 같아요!

따라서 호스트와 볼륨으로 연결한 도커 컨테이너 내부 디렉토리에 접근해서 삭제 요청을 해야하는데 그러려면 앞의 `URL`을 제거하고, `System.getProperty("user.dir") + URL이 제거된 path`로 파일 경로를 다시 만들어서 삭제를 진행해야할 것 같은데 이 부분에 대해서 어떻게 생각하시나요 :)

2023-08-29 14:26 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalManager.java
> +        }
없는 경로에 대해 삭제 요청을 하면 예외가 발생하나요??

2023-08-29 14:26 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/application/PhotoServiceTest.java
> +                .fetch();
테스트용 쿼리 좋은 것 같습니다 👍👍

2023-08-29 14:26 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoRepositoryTest.java
> +        List<Photo> photos = List.of(savePhoto1, savePhoto2);
저는 `1`, `2` 숫자보다 `A`, `B` 영어 사용하는 것이 더 직관적이었는데 이 부분은 어떻게 생각하시나요?

사실 테스트라 큰 의미가 없긴 하지만 ,, ㅎ

2023-08-29 14:26 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoRepositoryTest.java
> +    void 리뷰_사진_엔티티를_삭제한다() {
위의 테스트에는 `리뷰 사진 데이터`라 되어있고 여기는 `리뷰 사진 엔티티`라 되어있어 통일성 맞춰주면 좋을 것 같아요 :)

2023-08-29 14:26 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoServiceTest.java
> +    void 리뷰_사진_매핑_정보를_삭제한다() {
여기는 `리뷰 사진 매핑 정보`라 되어있네요 ㅎㅎ

2023-08-29 14:26 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/domain/ReviewTest.java
> +    void 리뷰_작성자와_동일하면_false_반환한다() {
동일한 메서드를 테스트하고 있기에 `@Nested`로 묶어주면 좋을 것 같아요~~

2023-08-31 13:06 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        if (review.isNotOwnerOf(member)) {
큰 이유는 없고 클린 코드에 대해서 학습할 때 `!`는 최대한 자제하는 방향으로 배워서 `!`를 최대한 자제하고 있습니다 !

2023-08-31 13:10 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/exception/ReviewExceptionType.java
> +@RequiredArgsConstructor
모두 반영했습니다 ~

2023-08-31 13:16 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/domain/Review.java
> +        return !Objects.equals(this.member, member);
리뷰 작성자와 요청으로 들어온 사용자가 불일치하는 경우 서비스 계층에서 예외를 발생시키는 것이 서비스의 책임이라고 생각했습니다 !

만약 도메인 필드의 값을 변경하는 과정이었다면 도메인 내부에서 예외를 발생시키는 방법을 선택했을 것 같습니다 ㅎㅎ

2023-08-31 13:18 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .orElseThrow(() -> new BadRequestException(NOT_FOUND_ERROR));
`NOT_OWNER`라고 했을 때 이게 예외인지 아닌지 명시하고 싶었는데, 예외 패키지에 있으니 굳이 명시할 필요가 없을 것 같네요 ~~
떼는 방향으로 수정할게요 !

2023-08-31 13:35 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                            """,
놓친 부분이었네요 ㅎㅎ 감사합니다 !

2023-08-31 13:43 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoRepository.java
> +public interface ReviewPhotoRepository extends Repository<ReviewPhoto, Long>, ReviewPhotoCustomRepository {
이 부분도 고민을 꽤 했었는데요 !

우선, 현재 영속화 계층에서 `Repository` 인터페이스를 사용하고 있어서 별도로 분리하지 않았습니다. `JPARepository`나 `CRUDRepository`를 사용하는 경우 기존에 존재하고 있는 메서드가 있기 때문에 queryDsl로 구현하면 메서드 명이 겹쳐서 혼란스럽더라구요..

현재 저희는 기본적으로 구현된 메서드들이 존재하지 않기 때문에 `ReviewPhotoRepository`가 구현해서 사용해도 혼란스럽지 않았습니다 !

추가적으로 영속화 계층의 구현된 클래스 종류를 서비스 계층에서 자세히 몰라도 되지 않을까 생각했습니다 ㅎㅎ

아직까지 QueryDsl 경험이 많지 않아서 큰 불편함을 느끼지 못했는데요 !
불편함을 느끼면서 분리의 필요성을 느낀다면 이 또한 좋은 경험일 것 같습니다 😄

2023-08-31 13:43 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoCustomRepositoryImpl.java
> +    }
넵 ! 맞습니다 ㅎㅎ

2023-08-31 13:54 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoRepository.java
> +    List<ReviewPhoto> findAllByReview(Review review);
확인했습니다 !

2023-08-31 14:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalManager.java
> +        }
`file.exists()`를 작성한 이유는 exists 함수가 file 내에 path가 잘 들어있는지 확인을 합니다.
그렇기 때문에 path가 제대로 들어가지 않은 경우, file.delete()를 호출하는 불필요한 I/O를 막기 위함임니다 !

2023-08-31 14:08 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoRepositoryTest.java
> +        List<Photo> photos = List.of(savePhoto1, savePhoto2);
좋아요 ㅎㅎ

2023-09-02 06:27 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoCustomRepositoryImpl.java
> +    }
조심스레 추측해보면 `cascade`나 `orphanRemove`와 같이 영속성과 관련된 제약 조건이 걸려있는 경우, 영속성 컨텍스트가 다른 엔티티의 생명 주기까지 관리하기 때문에 가져오지 않을까 생각합니다 ㅎㅎ

2023-09-02 06:28 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalManager.java
> +    }
앗 그때 변경했던 것을 깜빡했었네요 ㅎㅎ

바로 반영하겠습니다 ~

2023-09-04 07:37 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .orElseThrow(() -> new NotFoundException(NOT_FOUND));
`new NotFoundException(NOT_FOUND)`만 봤을 때는 어떤 것을 찾지 못했는지에 대한 정보가 담겨있지 않아서 읽는 입장에서 헷갈릴수도 있는 부분인 것 같아요!

static import를 하지 않고 `ReviewExceptionType`를 나타내는 방법이나 `REVIEW_NOT_FOUND`로 명시해주는 방법 등으로 이를 개선해보는건 어떨까요? 😙

2023-09-04 07:37 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/domain/Review.java
> +        return !Objects.equals(this.member, member);
도메인의 필드를 유효하지 않도록 하는 상황에서는 도메인에서 예외를 발생시키고, 도메인의 값은 유효하지만 비즈니스적으로 유효하지 않을 때는 서비스에서 예외를 발생시킨다는 말로 이해했습니다!

좋은 근거인 것 같아요 ㅎㅎ

2023-09-04 07:37 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoRepository.java
> +public interface ReviewPhotoRepository extends Repository<ReviewPhoto, Long>, ReviewPhotoCustomRepository {
> 우선, 현재 영속화 계층에서 Repository 인터페이스를 사용하고 있어서 별도로 분리하지 않았습니다. JPARepository나 CRUDRepository를 사용하는 경우 기존에 존재하고 있는 메서드가 있기 때문에 queryDsl로 구현하면 메서드 명이 겹쳐서 혼란스럽더라구요..

> 아직까지 QueryDsl 경험이 많지 않아서 큰 불편함을 느끼지 못했는데요 !
불편함을 느끼면서 분리의 필요성을 느낀다면 이 또한 좋은 경험일 것 같습니다 😄

좋은 근거인 것 같습니다 ✅

Querydsl을 사용할 때 `implements/extends`를 선호하지 않는 이유로는 매번 해당 구조로 만들어야한다는 번거로움이 존재한다고 합니다. 또한 하나의 Repository를 사용한다는 장점을 날리면서도 분리하는 이유는 implements를 하게 되면 해당 `Entity`에 종속되는 구현이 되어버립니다.

프로젝트가 커짐에 따라 특정 엔티티만 조회하는 것이 아닌 다른 엔티티와 조인해서 데이터를 가져오게 되는 상황이 많이 발생하게 되는데 이때 어떤 Entity의 Repository에 implements를 시켜야할지에 대한 모호함이 남게 됩니다. 이런 경우는 implements 방식을 사용하지 않고 별도의 구현체를 두어 `JpaQueryFactory`를 서비스에 특화된 로직에 적극적으로 활용한다고 합니다.

해당 기능은 위와 같이 엔티티가 모호하고 서비스에 특화된 쿼리가 발생할 때 분리해서 구현해봐도 좋을 것 같네요 :)

2023-09-04 07:37 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/ReviewPhotoCustomRepositoryImpl.java
> +    }
저도 비슷한 이유라고 생각이 드네요! 시간이 된다면 자세히 알아봐도 좋을 흥미로운 주제네요 🤔

2023-09-04 07:37 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewRepository.java
> +    Optional<Review> findById(Long id);
요기도 `RCUD` 순서가 달라용 ㅎㅎ

2023-09-04 07:37 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoRepositoryTest.java
> +        List<Photo> photos = List.of(savePhoto1, savePhoto2);
의미있는 변수명을 사용하니 훨씬 읽기 좋아진 것 같아요 👍

2023-09-04 07:38 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoServiceTest.java
> +    void 리뷰_사진_매핑_정보를_삭제한다() {
서비스에서는 `리뷰 사진 매핑 정보`로 그대로 두신 이유가 있으신가요?! 🤓

2023-09-04 07:40 UTC, woo-chang reviewed
수정 사항에 대하여 꼼꼼하게 잘 반영해주신 것 같습니다 👍

소소한 수정 사항과 몇 가지 코멘트 달아두었는데 한번만 더 확인해주시면 감사합니다 ㅎㅎ

2023-09-04 12:30 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoServiceTest.java
> +    void 리뷰_사진_매핑_정보를_삭제한다() {
서비스 계층 테스트라 엔티티라고 부르기도 그렇고, 객체라고 부르기도 그렇고..?

애매해서 그냥 데이터 내용을 담는 매핑 정보라고 적었습니당

2023-09-04 12:32 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .orElseThrow(() -> new NotFoundException(NOT_FOUND));
예외 타입을 저는 static import하고 우창씌는 그대로 나둬서 이 부분 이야기해보려고 했는데요 ㅎㅎ

ERROR라는 단어를 삭제했으니 static import를 하지 않는게 좋아보이네요 ~

2023-09-04 14:40 UTC, woo-chang approved these changes
마지막까지 꼼꼼히 굳굳 확인했습니다 😎

2023-09-04 14:43 UTC, merged