Feature/#99 리뷰 수정 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #167
Opened 2023-09-12 12:17 UTC by Kim0914

## 🔥 연관 이슈

close: #99 

## 📝 작업 요약

리뷰 수정 기능을 구현했습니다.

## 🔎 작업 상세 설명

- 리뷰 수정 시 삭제가 필요한 사진 ID를 받습니다.
- 리뷰 수정 시 새롭게 추가하는 사진을 받습니다.
- 해당 사진들을 검증 후, 리뷰를 수정합니다.

## 🌟 리뷰 요구 사항

> 30분

2023-09-14 02:41 UTC, woo-chang requested changes
기능부터 테스트까지 너무 꼼꼼하게 구현해주셨네요 👍

몇 가지 질문과 커멘트 남겨두었으니 확인 부탁드릴께요 :)

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/dto/request/ReviewUpdateRequest.java
> +        Long reviewId,
리뷰 아이디를 `@PathVariable`로 받도록 구현하지 않고 `Request`에 포함시킨 이유가 있나요? 🤔

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Set<Photo> deletePhotos = new HashSet<>();
`deletePhotoIds`를 `Set`으로 변환하는건 어떨까요?!

현재 삭제 ID에 대한 개수 검증이 되고 있지 않아 악의적인 요청으로 삭제 ID를 중복해서 여러 개 요청보내면 아래 `for`문의 성능이 급격하게 저하될 수도 있을 것 같다는 생각이 들었습니다!

이를 통해 중복된 삭제 요청은 제거할 수 있어 `deletePhotos`는 `List`로 가져갈 수 있을 것 같아요 🤓

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Set<Photo> deletePhotos = new HashSet<>();
중복된 삭제 요청은 저희가 예외를 발생시키지 않기로 했지만, 존재하지 않는 ID에 대한 삭제 요청은 잘못된 요청으로 볼 수 있을 것 같아요!

해당 검증을 통해 혹시 모를 사이드 이펙트(예를 들어 다른 리뷰의 사진을 삭제한다는 등)를 막을 수도 있을 것 같은데 이 부분에 대해서는 어떻게 생각하시나요 🤔

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        }
사진이 4개밖에 저장되지 않아 최대 4x4 경우의 수이지만 `Set<Long> deletePhotoIds`를 메서드로 넘겨서 아래와 같이 코드를 작성하면 아주아주 미세하게나마 성능 개선이 가능할 것 같은데 어떻게 생각하시나요 ㅎㅎ ..
```java
return currentPhotos.stream()
            .fiter(photo -> deletePhotoIds.contains(photo.getId()))
            .toList();
```

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoService.java
> +    }
`JPA`로 구현하게 되면 `review`로 조회한 뒤 각각 `delete` 쿼리가 나가도록 구현되겠죠?

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        photoService.delete(deletePhotos);
2개의 메서드는 매번 동시에 수행될 것 같은데 분리되어 있어 조금 어색한 느낌이 드네요 😃

조금 개선해볼 수 없을까요?

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/domain/vo/Content.java
> +        if (value == null || value.isBlank()) {
2개를 한번에 수행할 수 있는 `io.micrometer.common.util.StringUtils`의 `isBlank` 메서드를 찾게 되었는데 요거 사용해도 괜찮을까요? 🤔

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewPhotoCustomRepositoryImpl.java
> +    }
👍

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +    })
`404` 예외가 없어용 !

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                            5.리뷰 ID가 양수가 아닌 경우
현재 리뷰에 존재하지 않는 사진 ID도 포함되어야 할 것 같아요 :)

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/presentation/PositiveList.java
> +    String message() default "List elements must be positive";
메시지를 영어로 한 이유가 있으신가요 ? 🤓

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/presentation/PositiveList.java
> +    Class<? extends Payload>[] payload() default {};
`group`과 `payload`는 언제 사용되는지 설명해주시면 감사합니다 ㅎㅎ

2023-09-14 02:41 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/presentation/PositiveListValidator.java
> +        }
`null`일 때 유효한다고 판단한 이유가 궁금합니다 ! 😀

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewServiceTest.java
> +
테스트 너무 꼼꼼합니다 👍 존재하지 않는 리뷰일 때 테스트도 있으면 더욱 체고 👍

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/domain/vo/ContentTest.java
> +    }
생성 테스트는 `@Nested`로 묶어도 좋을 것 같아요 :)

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/PositiveListValidatorTest.java
> +    private ConstraintValidatorContext context;
`@Mock`을 사용하신 이유가 궁금합니다 ㅎㅎ

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/PositiveListValidatorTest.java
> +    }
하나로 묶고 `List`가 `null`일 때의 테스트도 있으면 좋을 것 같아요 :)

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .file(multipartFile5)
각각 줘야하나요? `List`로 전달할 수 있는 방법이 없는거겠죠? 🥲

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewPhotoRepositoryTest.java
> +            softly.assertThat(reviewPhotoRepository.findAllByReview(review)).contains(reviewPhoto);
`containsExactly`를 사용하지 않은 이유가 있나요?!

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewPhotoRepositoryTest.java
> +    void 리뷰에_해당하는_사진_엔티티들을_삭제한다() {
`Querydsl` 구현체에 대한 테스트는 `ReviewRepository`에 작성해야할까요 `ReviewCustomRepositoryImpl`에 작성해야할까요? 😎

2023-09-14 02:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewPhotoRepositoryTest.java
> +        Photo deleteTargetPhoto2 = photoTestPersister.builder().save();
```suggestion
        Photo deleteTargetPhotoA = photoTestPersister.builder().save();
        Photo deleteTargetPhotoB = photoTestPersister.builder().save();
```
컨벤션에 맞게 늘 먹던걸루

2023-09-16 06:37 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/dto/request/ReviewUpdateRequest.java
> +        Long reviewId,
큰 이유는 없고 어차피 body에 필요한 데이터들을 담아서 보내기 때문에 한번에 받도록 했었는데, PathVariable로 나타내주는 편이 클라이언트가 봤을 때도 더 명확해 보이긴 하네요 ㅎㅎ

2023-09-16 06:58 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Set<Photo> deletePhotos = new HashSet<>();
* deletePhotoIds를 Set으로 변환하는건 어떨까요?! -> 좋습니다 ㅎㅎ

* 존재하지 않는 ID에 대한 삭제 요청은 잘못된 요청 -> 이 경우를 아래 메서드로 검증하고 있는데 다른 검증을 의미하시나요?
```java
private Photo extractDeletePhoto(List<Photo> currentPhotos, Long deletePhotoId) {
        return currentPhotos.stream()
                .filter(photo -> isSamePhoto(deletePhotoId, photo))
                .findAny()
                .orElseThrow(() -> new BadRequestException(ReviewExceptionType.INVALID_PHOTO));
    }
```

2023-09-16 06:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewPhotoService.java
> +    }
넵 그럴 것 같습니다 ~

2023-09-16 07:04 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/domain/vo/Content.java
> +        if (value == null || value.isBlank()) {
`io.micrometer.common.util.StringUtils` 이 패키지는 사용해본적이 거의 없는데, 일반적으로 다른 사람들이 읽기 편한 `value == null || value.isBlank()`가 좀 더 낫지 않을까용?

2023-09-16 07:08 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        photoService.delete(deletePhotos);
이미 만들어놓은 메서드가 있었네요? 고거 사용하는걸로 변경했슴다 ~

2023-09-16 07:20 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +    })
complete !

2023-09-16 07:21 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/presentation/PositiveList.java
> +    String message() default "List elements must be positive";
스프링에서 제공하는 다른 어노테이션들도 기본으로 영어로 제공해서 따라했씀다 🫠

2023-09-16 07:22 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/presentation/PositiveListValidator.java
> +        }
리스트의 각 원소들을 검증하는게 목적이라고 생각해서 null은 `@NotNull`이 처리해줘야할 검증이라고 생각했어요 !

2023-09-16 07:29 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/presentation/PositiveList.java
> +    Class<? extends Payload>[] payload() default {};
Custom Constraint Annotation을 만들때 필수 값들입니다 !

Bean Validation을 진행하는 어노테이션들에서 공통적으로 확인할 수 있는 부분인데요 !
group은 어떤 클래스(상황)에 적용할 지 나타냅니다.

예를 들어 insert와 update에 필요한 검증 조건이 다르다면 아래와 같이 사용할 수 있습니다 ㅎㅎ
```java
@DecimalMin(value = "0.0", groups = Insert.class)  
@DecimalMax(value = "100.0", groups = Update.class)  
private final BigDecimal discountPercent;
```

payload는 예외 메세지 이외에 추가적인 정보가 필요할 때 사용한다고 하는데 잘 사용하지 않는다고 합니다...

2023-09-16 07:36 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/PositiveListValidatorTest.java
> +    private ConstraintValidatorContext context;
검증기 내부에 isValid 메서드를 테스트 하려고 했습니다 !

override하는 isValid 파라미터 중 하나가 `ConstraintValidatorContext`이 필요하고, 현재 구현한 `PositiveListValidator`에서는 context를 사용하지 않고 있기 때문에 Mock 객체로 만들어서 주입시켰습니다 ~

2023-09-16 07:37 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/PositiveListValidatorTest.java
> +    }
List가 null인 경우는 해당 검증 어노테이션의 책임이라고 생각하지 않아서 pass했습니다 !

2023-09-16 07:39 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .file(multipartFile5)
넵... maybe?
각각 주는게 더 명시적이지도 않나용?!

2023-09-16 07:40 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewPhotoRepositoryTest.java
> +            softly.assertThat(reviewPhotoRepository.findAllByReview(review)).contains(reviewPhoto);
반영완 !

2023-09-16 07:44 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewPhotoRepositoryTest.java
> +    void 리뷰에_해당하는_사진_엔티티들을_삭제한다() {
`ReviewPhotoRepository` 를 말씀하신거겠죠? 😁

그게 조금 애매하긴 했는데, 애플리케이션 내에서 `ReviewPhotoRepository`를 통해 구현 메서드를 사용하고 있어서 `ReviewPhotoRepository`에다가 작성했는데 테스트는 구분해줘도 좋겠네요 ~

2023-09-16 09:28 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +            @Positive(message = "ID는 양수만 가능합니다.") Long id,
프로젝트 전체적으로 나타낼 수 있는 정보들에 대해서는 명시적으로 나타내기로 했기에 `reviewId`로 하는건 어떨까요? 😀

`message`에서도 어떤 `ID`인지 드러나면 정보가 더욱 풍부해질 것 같아요 :)

마지막으로 `Docs`에서는 매개변수 사이 개행이 들어가는 컨벤션인 것 같아서 개행이 필요해보여요 !

2023-09-16 09:28 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +            mockMvc.perform(multipart(HttpMethod.PATCH, "/v1/reviews/{id}", 1L)
테스트에서도 동일하게 `reviewId`로 드러내면 좋을 것 같아요 !

2023-09-16 09:28 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Set<Photo> deletePhotos = new HashSet<>();
로직이 깔끔하게 수정된 부분 확인했습니다 👍 훨씬 읽기도 좋아진 것 같네요 ㅎㅎ

위의 로직으로도 충분히 처리할 수 있지만, 존재하지 않는 `ID`가 들어온 상황은 클라이언트에서 유효하지 않은 요청으로 보고 예외를 터뜨리는게 좋지 않을까라는 것이 저의 의견입니다 🥸 이 부분에 대해서는 어떻게 생각하시나요?!

2023-09-16 09:30 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/domain/vo/Content.java
> +        if (value == null || value.isBlank()) {
설득당했습니다 ~ 동의합니다 ㅎㅎ

2023-09-16 09:32 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                    description = "존재하지 않는 리뷰 ID",
존재하지 않는 리뷰 정도로도 충분할 것 같아요 ㅎㅎ

2023-09-16 09:32 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                            5.리뷰 ID가 양수가 아닌 경우
https://github.com/Busan-Dinosaur/Foodbowl-Backend/pull/167#discussion_r1327938063

2023-09-16 09:33 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/presentation/PositiveList.java
> +    Class<? extends Payload>[] payload() default {};
설명 감사합니다 배워갑니다 ㅎㅎ

2023-09-16 09:40 UTC, woo-chang reviewed
수정사항 확인했고 몇 가지 남은 부분에 대해 다시 한번 리뷰했습니다 🤓

확인 부탁드릴께요 ㅎㅎ

2023-09-16 09:40 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                            3.삭제 사진 ID에 음수가 포함된 경우제
1. `경우제` 오타가 있습니다!
2. 리뷰 ID가 양수가 아닌 경우 `@Positive`에 의해 `400` 응답이 발생하지 않을까요?! 삭제하신 이유가 궁금합니다!

2023-09-17 06:21 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +            mockMvc.perform(multipart(HttpMethod.PATCH, "/v1/reviews/{id}", 1L)
상위 URL이 다른 도메인(follow) 같은 경우에는 나타내주는게 맞는 것 같은데, 자신 도메인을 나타내는 URL을 테스트에서까지 reviewId로 나타낼 필요가 있을까요..?

우선 반영했습니다 ~

2023-09-17 06:27 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                            3.삭제 사진 ID에 음수가 포함된 경우제
실수로 지워버린 것 같네용;; 추가했습니다 ~

2023-09-17 07:57 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Set<Photo> deletePhotos = new HashSet<>();
철저한 검증은 나쁜게 없으니 ㅎㅎ

자바 애플리케이션 단으로 처리할 수도 있기 때문에 추가하겠슴다 ~

2023-09-17 08:39 UTC, woo-chang approved these changes
확인했습니다 😎 마지막까지 꼼꼼히 작업하시느라 수고하셨습니다 👍

2023-09-17 08:40 UTC, merged