Feature/#166 신고하기 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #168
Opened 2023-09-14 09:20 UTC by woo-chang

## 🔥 연관 이슈

* close: #166

## 📝 작업 요약

신고하기 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 멤버, 리뷰에 대한 신고가 가능합니다.
- 존재하지 않는 멤버, 리뷰에 대한 신고는 불가능합니다.
- 스스로 본인에 대한 신고는 불가능합니다.
- 이미 신고한 대상에 대한 신고는 불가능합니다.

`Q`
신고 후에 해당 신고 ID를 사용할 일이 없기에 아무 것도 반환하지 않도록 구현하였습니다. 그렇기에 신고 등록 후 검증할 수 있는 방법이 없어 예외를 던지지 않는 것을 확인하도록 검증하였는데 애매한 것 같아서 이 부분에 대해 좋은 의견이 있으시면 알려주세요 😙

## 🌟 리뷰 요구 사항

> 30분
> 신고가 안되는 상황에 대해 생각하며 리뷰해주시면 감사합니다 :)

2023-09-17 15:24 UTC, Kim0914 requested changes
안녕하세요 대즐씨 😀

신고하기 구현 잘해주셨네요 ㅎㅎ
EnumMap도 인상깊습니다 !

궁금한 부분과 생각해 볼만한 부분 코멘트로 남겼어요.
확인부탁드릴게요 🙇🏻

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    }
Optional의 `ifPresent()`를 사용할 수 있겠네요 ㅎㅎ

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    }};
enumMap 사용 좋은데요?

해당 BlameTarget 객체에게 메서드를 할당하지 않은건 의존성 때문이겠죠?! 😙

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    private boolean existMember(Long targetId) {
`isExistMember`가 좀 더 명확한 것 같네요 !

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    private boolean existReview(Long targetId) {
`ditto`

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +        boolean existTarget = reportCheck.get(blameRequest.blameTarget()).test(blameRequest.targetId());
```suggestion
        boolean existTarget = reportCheck.get(blameRequest.blameTarget())
        .test(blameRequest.targetId());
```

애플리케이션 코드에는 한 줄에 점 하나가 어떨까요?!

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +        boolean blameMe = reportMe.get(blameRequest.blameTarget()).test(blameRequest.targetId(), member);
`ditto`

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +        boolean existTarget = reportCheck.get(blameRequest.blameTarget()).test(blameRequest.targetId());
`existTarget`이라서 한눈에 들어오지 않는 것 같아요..!

`isExistTarget`은 어떤지 제안드려봅니당

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    private void validateDuplicate(BlameRequest blameRequest, Member member) {
사용자의 관점에서 이미 신고한 게시글 or 회원을 다시 신고할 수도 있지 않을까 생각이 드네요 ㅎㅎ(ex, 신고 내용을 잘못 입력했거나, 신고 내용을 보충하고 싶거나)

기획적인 부분인 것 같은데 확인된 부분인지 궁금합니다 ~

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/domain/vo/Description.java
> +        if (StringUtils.isBlank(value)) {
이전 리뷰에서 `value == null || value.isBlank()`로 사용하기로 했는데 맞춰보는건 어떨까욥?

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/exception/BlameExceptionType.java
> +    BLAME_ME("BLAME-100", "스스로에 대해 신고할 수 없습니다."),
```suggestion
    BLAME_ME("BLAME-100", "본인을 신고할 수 없습니다."),
```

사소하지만 요건 어떤가욧?

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameController.java
> +public class BlameController {
docs를 `implement` 하지 않아도 될까용?!

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameControllerDocs.java
> +                    blameTarget에 회원을 신고하는 경우 MEMBER를, 리뷰를 신고하는 경우 REVIEW값을 등록합니다.
친절한 설명 구웃 !

2023-09-17 15:24 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/blame/application/BlameServiceTest.java
> +            assertThatNoException().isThrownBy(() -> blameService.blame(request, loginMember));
`assertDoesNotThrow()`랑 어떤 차이가 있나요? (정말 궁금증)

2023-09-17 15:24 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameControllerTest.java
> +                    """;
오 이렇게도 되나요? 신기하네요 ㅎㅎ

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/dto/request/BlameRequest.java
> +        BlameTarget blameTarget,
String으로 blameTarget을 받아서 BlameTarget.from()과 같은 메서드를 이용해서 enum 객체를 추출하면서 올바르지 않은 value이면 예외를 발생시킬 수도 있을 것 같은데, 직접 enum을 받도록 해주신 이유가 궁금합니다 !

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/dto/request/BlameRequest.java
> +        BlameTarget blameTarget,
`@NotNull`이 없어도 괜찮나용?

2023-09-17 15:24 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameControllerTest.java
> +    class 신고_시 {
신고 타겟이 없으면 예외가 발생하는 테스트도 필요하지 않을까요?! 🤓

2023-09-17 15:24 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameControllerDocs.java
> +    ResponseEntity<Void> blame(BlameRequest blameRequest, Member loginMember);
컨트롤러에 implements 하고 테스트 해봤는데 여기는 `@Valid`를 안붙여도 잘 돌아가네요..!

bean validation이 없어서 그런가 생각했는데 reviewCreateRequest도 bean validation이 없거든용...

`@RequestPart`일때만 필요한건가 싶기도 하네요....

왜 때문인지 아시나요?!?!

2023-09-17 23:37 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    }
한번에 처리할 수 있어서 깔끔한 것 같네요 :)

2023-09-17 23:38 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    }};
맞습니다 ! 각 로직마다 필요한 의존성이 존재해서 메서드 참조 형태로 구현하였습니다 🤓

2023-09-17 23:40 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +        boolean existTarget = reportCheck.get(blameRequest.blameTarget()).test(blameRequest.targetId());
좋습니다 ㅎㅎ

2023-09-17 23:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    private void validateDuplicate(BlameRequest blameRequest, Member member) {
기획자와의 얘기가 필요한 부분인 것 같네요 ! 확인해보겠습니다 🧐

2023-09-17 23:47 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameController.java
> +public class BlameController {
헉 놓치고 지나갔던 부분인데 감사합니다 🙇🏻‍♂️👍

2023-09-17 23:52 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/blame/application/BlameServiceTest.java
> +            assertThatNoException().isThrownBy(() -> blameService.blame(request, loginMember));
<img width="583" alt="스크린샷 2023-09-18 오전 8 50 51" src="https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/78212016/1221b1f9-7f6e-4eca-9fea-dbc381118de3">

`assertDoesNotThrow`는 Junit에서 제공하는 기능이고 `assertThatNoException`은 assertJ에서 제공하는 기능인 것 같습니다 ! assertAll -> assertSoftly로 수정한만큼 assertJ 기능을 활용하는건 어떠신가요? 😀

2023-09-17 23:53 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameControllerTest.java
> +                    """;
`JSON` 형태의 `String` 값을 넣어주면 파싱을 자동으로 해주는 것 같습니다 ㅎㅎ

2023-09-18 00:32 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/presentation/BlameControllerDocs.java
> +    ResponseEntity<Void> blame(BlameRequest blameRequest, Member loginMember);
컨트롤러에 `@Validated`가 붙어있는지 여부에 대한 차이라고 생각이 듭니다 !

`@Validated` 어노테이션을 붙이게 되면 스프링 AOP가 동작하게 되는데, 메서드에 붙어있는 `Valid` 어노테이션을 보고 동작하기에 인터페이스와 같은 시그니처에도 동일하게 붙여줘야 인식할 수 있지 않을까라는 생각이 드네요 :)

2023-09-19 02:15 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/application/BlameService.java
> +    private void validateDuplicate(BlameRequest blameRequest, Member member) {
아직 기획이 명확히 정해지지 않은 상태이기 때문에 제한을 초기에는 강하게 가져가는 것으로 결정했습니다 !

제한을 풀었다가 다시 제한을 거는 것보다 제한을 강하게 가져간 뒤 제한을 느슨하게 수정하는 것이 훨씬 편한 방법이기에 우선은 가장 빡빡한 제한으로 구현해두고 추후에 기획이 완벽히 정해지면 수정하고자 합니다 :)

2023-09-19 02:18 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/blame/dto/request/BlameRequest.java
> +        BlameTarget blameTarget,
이 부분에 대해 고민해보았는데, `ArgumentResolver`를 통해 `Enum` 예외를 처리하게 되면 커스텀 예외를 처리할 수 없다는 단점이 존재하더라구요 🥲

따라서 `dto`에서는 최소한의 입력에 대한 검증을 진행 후 비즈니스 로직에서 `Enum` 값에 대한 검증을 하도록 수정하였습니다 !

2023-09-19 04:37 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/blame/application/BlameServiceTest.java
> +            assertThatNoException().isThrownBy(() -> blameService.blame(request, loginMember));
어떤 걸 사용해도 테스트 목적에 맞다면 문제 없을 것 같아요 ~

2023-09-19 13:19 UTC, Kim0914 approved these changes
반영해주신 부분 확인했습니다 ㅎㅎ

고생많으셨어요 !

2023-09-19 13:19 UTC, merged