Feature/#148 회원 프로필 이미지 수정 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #173
Opened 2023-09-23 15:44 UTC by woo-chang

## 🔥 연관 이슈

* close: #148

## 📝 작업 요약

회원 프로필 이미지 수정 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 사진 저장과 삭제를 목록으로 처리하던 부분을 각각 개별로 처리하도록 수정하였습니다.
  - 수정한 이유는 추후에 저장과 삭제 로직이 비동기로 처리될 수도 있기에 목록으로 처리하게 된다면 목록으로 처리하는 로직 자체가 하나의 동기 로직이 되어버려 개별로 처리할 수 없다는 단점을 고려하여 수정하였습니다! 혹시 추가적인 의견 있다면 말해주시면 감사합니다 :)
- 프로필 이미지 수정 기능을 구현하였습니다.
  - 멤버 프로필 이미지가 존재하는 경우 프로필 이미지를 삭제 후 로직이 시작됩니다.
  - 요청에 이미지 파일이 존재하지 않으면 해당 로직은 종료되게 됩니다.
  - 요청에 이미지 파일이 존재한다면 새로운 썸네일을 생성하고 해당 썸네일을 프로필로 지정합니다.

## 🌟 리뷰 요구 사항

> 30분
> 프로필 이미지 수정에 분기 처리가 존재하여 이 부분에 대해 집중적으로 리뷰해주시면 감사합니다 :)

2023-09-25 11:14 UTC, Kim0914 requested changes
안녕하세요 ^^ 리뷰어 gray입니다.

프로필 이미지 수정 기능 구현 잘해주셨네요 ㅎㅎ
저도 프로필 이미지를 어서 수정해보고싶네요.

궁금한 부분 코멘트로 남겼어요 !

2023-09-25 11:14 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/member/application/MemberService.java
> +        }
개인적인 생각인데 기존 프로필 이미지를 삭제하는 기능을 따로 두는건 어떤가요?
`수정`이라는 기능에서 수정과 삭제 2가지 기능을 처리하고 있는 것 같아요 !

카톡이나 인스타의 경우 아래와 같이 로직이 나뉘는데요,
현재 프로필이 존재하는 경우 -> 현재 프로필 삭제하기 / 현재 프로필 수정하기
현재 프로필이 존재하지 않는 경우 -> 사진 추가하기

현재 수정에서 2가지 기능을 하고 있는 부분이 사용자의 상태에 따라 클라이언트가 구분해서 보여줘야 하는 기능이라고 생각해요. 서버는 수정, 삭제 API를 구분한 상태로요 !

어떻게 생각하시나요 ㅎㅎ

2023-09-25 11:14 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberController.java
> +            consumes = {MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE}
여기서 Json 타입이 필요한가욤?!

2023-09-25 11:14 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberController.java
> +            @RequestPart(name = "thumbnail", required = false) MultipartFile thumbnail,
리뷰 업로드 시 이미지 request name이 `images`라서 헷갈리지 않게 docs로 클라이언트에게 잘 전달해야될 것 같네요 !

2023-09-25 11:14 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +    public Photo save(MultipartFile file, String workingDirectory) {
List로 추가, 삭제되는 부분을 모두 단건 추가, 삭제로 변경해주셨네요 !

목록으로 처리하게 된다면 목록으로 처리하는 로직 자체가 하나의 동기 로직이 되어버린다고 말씀해주셨는 정확히 어떤 의미인지 이해가 잘 안되네요 🥲🥲

비동기로 처리하게되면 해당 메서드 자체가 별도의 스레드에서 동작할 것 같은데, 목록으로 처리했을 때 어떤 문제점이 있나요?!

2023-09-25 11:14 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoManager.java
> +    String upload(MultipartFile image, String parentDirectory);
다수의 이미지 업로드와 삭제를 단건 업로드와 삭제로 변경해주셨는데, 비즈니스 요구사항에 따라 필요하다면 두 가지 방법 모두 다 사용하는게 적절하지 않나요?!

기존에 존재하는 List 형식의 업로드, 삭제를 삭제한 이유가 있을까요??

2023-09-25 11:14 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoCustomRepository.java
> +    long deleteByPhoto(Photo photo);
여기도 동일합니다 !!

기존의 bulk로 삭제해서 성능상으로 이점을 가져갈 수 있는 부분인데, 삭제하고 단건 쿼리만 사용할 필요가 있을까요?!
필요하다면 두 가지 방법 모두 구현하는게 맞지 않을까요?!

2023-09-25 11:14 UTC, Kim0914 commented on src/main/resources/application.yml
> +      max-request-size: 25MB
5MB가 늘어난 것은 프로필 이미지 크기를 추가해주신거겠죵?!

2023-09-25 11:14 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberThumbnailRepositoryTest.java
> +        void 썸네일이_존재한다면_멤버_썸네일을_반환한다() {
아래 테스트와 테스트 명이 바뀐걸까요..?! ㅎㅎ

2023-09-26 00:49 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberController.java
> +            consumes = {MediaType.MULTIPART_FORM_DATA_VALUE, MediaType.APPLICATION_JSON_VALUE}
늘 사용했던 `JSON`으로 인해 혹시 몰라 놔뒀는데 필요없는 타입인 것 같네요 ㅎㅎ

2023-09-26 00:50 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberController.java
> +            @RequestPart(name = "thumbnail", required = false) MultipartFile thumbnail,
클라이언트로부터 받을 때는 `image`로 받고 서버에서는 `thumbnail`로 처리해도 좋을 것 같아요 ! 수정하였습니다 😀

2023-09-26 00:59 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +    public Photo save(MultipartFile file, String workingDirectory) {
말씀해주신대로 **List 단위로 생성과 삭제 로직을 비동기로 처리**할 수도 있습니다 ! 저는 **각각의 사진 저장과 삭제를 비동기로 진행**하는 것까지 고려했습니다 🥸

사진을 3장 생성하는 경우를 예로 들어볼께요. 3장의 사진 목록을 매개변수로 전달하여 비동기로 처리하게 되면 사진 생성 로직 자체는 비동기로 동작합니다. 다시 말해서 **별개의 1개 스레드가 생성**되게 될 것 같아요. 하지만 비동기 동작 내부에서는 사진 3장이 순차적으로(동기적) 생성됩니다.

각각의 사진 저장 로직을 비동기로 처리하게 되면 3장의 사진이 있는 경우 **3개의 별도 스레드가 동작**하게 될 것 같아요. 사진 저장은 다른 사진 저장에 영향을 받지 않고 독립적인 동작이기에 각각 비동기로 처리하는 것 까지 고려하였는데 이 부분에 대해서는 어떻게 생각하시는지 궁금합니다.

하지만 이렇게 처리하게 되면 스레드를 많이 소비하기에 스레드에 대한 리소스가 많이 발생할 수도 있겠다는 생각이 들어요. 하지만 현재 사진 저장 개수가 정해져있고 스레드 설정을 통해 적절히 해결할 수 있는 문제라 생각이 들어요. 스레드 소비를 감당할 수 없는 상황이 온다면 서버 인스턴스 또는 컨테이너 증설도 고려해볼 수 있을 것 같아요 :)

2023-09-26 01:38 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoManager.java
> +    String upload(MultipartFile image, String parentDirectory);
https://github.com/Busan-Dinosaur/Foodbowl-Backend/pull/173#discussion_r1336516058

위의 커멘트와 더불어 한 가지 더 고려한 점이 있습니다 🤓

그 전에 궁금한 점이 존재하는데, `S3`에 사진 저장 시에도 사진 목록을 통해 한번에 저장하고 삭제하는 기능이 존재하나요?

저희는 `PhotoManager` 인터페이스를 두고 `LocalManager`와 `S3Manager` 구현체를 구현하기로 했는데, `S3` 구현체에는 해당 기능이 없음에도 목록으로 저장하고 삭제하는 메서드 시그니처가 존재하면 어색할 것 같다는 생각도 들었어요. 단건 저장과 삭제가 존재한다면 이를 사용하는 로직에서도 충분히 목록 처리가 가능할 것 같은데 목록 처리에 대한 메서드가 필요한 이유가 궁금해요 :0

2023-09-26 01:40 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoCustomRepository.java
> +    long deleteByPhoto(Photo photo);
각각 삭제가 별도로 처리된다면 데이터 삭제도 별도로 저장되어야 한다고 생각했어요. 위의 코멘트를 읽어보시고 다시 한번 커멘트 남겨주시면 감사합니다 ㅎㅎ

2023-09-26 01:43 UTC, woo-chang commented on src/main/resources/application.yml
> +      max-request-size: 25MB
최악의 상황을 고려하여 정확히 `5MB` 크기의 이미지 `4장`이 들어오면 요청 헤더나 본문 데이터 크기는 고려되지 않기에 에러가 발생할 수 있다고 생각했어요. 이를 고려하여 여유 공간을 설정해주었습니다!

2023-09-26 01:46 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberThumbnailRepositoryTest.java
> +        void 썸네일이_존재한다면_멤버_썸네일을_반환한다() {
매의 눈 🦅 꼼꼼히 읽고 계신지 테스트였는데 통과하셨네요 ㅎㅎ

2023-09-26 01:52 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/member/application/MemberService.java
> +        }
수정 로직을 구현하면서 계속 걸렸던 부분이었는데 정확히 짚어주셨네요 😀

하나의 `API`에 수정, 삭제 2가지 역할이 존재하니 구현하기도 어렵고, 로직도 복잡해더라구요. 인스타처럼 대기업은 이를 알고 사전에 분리하는 작업을 거쳤군요 ㅎㅎ 예시까지 들어서 설명해주셔서 더욱 이해하기 쉬웠습니다 👍

수정과 삭제 로직을 분리하도록 수정해보도록 할께요 :)

2023-09-28 11:19 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoManager.java
> +    String upload(MultipartFile image, String parentDirectory);
S3에 한번에 업로드하는 기능은 존재하지 않습니다 !

저는 PhotoManager 클래스는 사용자(개발자)가 이미지 업로드를 하기 쉽도록 유틸성 함수를 제공하는 역할이라고 생각합니다.
그래서 위에서 `비즈니스 요구사항에 따라 필요하다면 두 가지 방법 모두 다 사용`이라는 코멘트를 남겼던 것이구요 ~

우리가 List의 `addAll`나 Map의 `putAll`혹은 JPA의 `deleteAll`과 같이 리스트를 넘겨줘야하는 상황에서는 리스트를 처리할 수 있는 메서드를 직관적으로 사용하는 것처럼요. 실제 내부에서는 iterator로 단건을 여러번 호출 하는것과는 동일하게 동작할지라도 비즈니스 요구사항에 따라 필요한 메서드들은 열어두는게 좋지 않을까요?!

지금 상황이라면 단건 업로드하는 upload 메서드를 만들어두고, 리스트를 업로드하는 메서드는 단건 upload를 여러번 호출하게끔? 🙂

어떻게 생각하시는지 궁금하네용 ㅎㅎ

2023-09-28 11:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +    public Photo save(MultipartFile file, String workingDirectory) {
요즘 비동기를 찾아보면서 가장 많이 듣는 이야기가 비동기는 정말 많이 고려해보고 꼼꼼히 테스트한 후 도입해야한다 ! 라는 말이더라구요 ㅎㅎ

우선, 가장 궁금한 점은 `비동기 동작 내부에서 사진 3장이 순차적으로(동기적) 생성`될 때 어떤 문제가 발생하나요? 
여기서 발생할 수 있는 문제가 각각의 사진들을 별도의 스레드로 모두 분리했을 때 해결될 수 있는 문제인지가 궁금합니다 ㅎㅎ

이론적으로 생각했을 때는 별도의 스레드로 동작시켜도 문제없을 것 같다는 생각이 들지만 서버의 자원(스레드)을 추가적으로 사용한다는 점은 매우매우 신중하게 고려해야하지 않을까라는 생각이 드네요 !

현재 서비스에서 이미지 최대 업로드 개수가 4개인데, 동시에 10개의 요청이 발생하면 최악의 경우 40개의 스레드가 이미지 처리만을 위해 사용될 것 같아요. 더 최악의 경우를 가정해서 100개의 요청이라면 400개의 스레드가 이미지 처리만...?

결론적으로 지금 상황에서 비동기를 고려한 로직이 코드에 들어가도 괜찮은가?를 고려해보면 좋을 것 같네요 ~

2023-09-28 11:33 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/persistence/PhotoCustomRepository.java
> +    long deleteByPhoto(Photo photo);
여기도 동일한데요 ! ㅎㅎ

현재 상황에서는 batch delete를 하는게 명확히 성능적으로 이득을 볼 수 있는 부분이 아닌가 싶어서요 !

그래서 지금처럼 필요하다면 `long deleteByPhoto(Photo photo);` `long deleteAllByPhoto(List<Photo> photos);` 둘 다 사용하고, 비동기를 도입하기 충분한 검토가 이뤄졌다면 그 때 고려해도 되지 않을까 생각해요 ~

2023-09-28 12:42 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +    public Photo save(MultipartFile file, String workingDirectory) {
기술 도입에 있어서 장단점을 명확히 알아보고 테스트 이후 도입해야한다는 것은 너무 동의합니다 ㅎㅎ

사진 3장을 동시에 저장했을 때 발생하는 문제보다는 비동기 기술 도입하는 이유에 대해 더 고민해봤던 것 같아요. 저희가 비동기를 고려하고 있는 이유는 사진 저장이 지연 시간이 가장 큰 IO 작업이기 때문입니다. 해당 로직을 동기로 처리하게 되면 사용자에게 느린 응답을 제공할 뿐더러, 비용이 비싼 자원 중 하나인 커넥션을 물고 있는 시간이 증가하게 됩니다. 이는 서비스로서의 단점일 뿐더러 커넥션을 물고 있기 때문에 애플리케이션 전체적인 성능에 영향을 줄 수 있다고 생각해요!

그렇기에 이에 대한 처리를 더욱 극대화하고자 각각 사진 저장을 개별로 처리하고자 했던 것입니다. 비동기 기술을 도입하는 순간 3장을 순차적으로 처리하는 것과 개별로 처리하는 것에서는 동일한 문제가 발생하고 동일하게 해결할 수 있다고 생각해요. 말씀하신 것처럼 100개의 요청이 동시에 발생한다면 400개의 스레드를 소비하는 것과 동일하게 400개 요청이 들어오면 사진 저장을 목록으로 처리할 때도 동일한 문제 상황이 발생하게 됩니다. 그런 상황이 발생할만큼 트래픽이 활발한 상황이라면 이미지 저장을 위한 서버를 분리해보거나 애플리케이션 스케일 아웃 방법으로 해결할 수 있다고 생각해요. 이를 사전에 막기 위해서는 모니터링 시스템을 구축해서 애플리케이션을 지속적으로 모니터링 하는 것도 좋겠네요 ㅎㅎ

2023-09-28 12:51 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoManager.java
> +    String upload(MultipartFile image, String parentDirectory);
비동기 기술과 함께 고려하다보니 고민이 계속해서 이어졌던 것 같아요. 마지막까지 남아있던 고민은 목록으로 처리하는 메서드 자체적으로 비동기, 동기 구현이 정해져있다면 비동기 목록 처리, 동기 목록 처리 2가지 기능이 필요하지 않을까에 대한 고민이 있었어요. 하지만 목록 처리 구현을 사용하고 싶지 않은 상황에서는 단건 처리를 순회하며 원하는 방식으로 구현할 수 있겠다는 결론에 도달하게 되었어요.

결론적으로 유틸성 클래스인 `PhotoManager`에는 목록으로 처리하는 기능이 있으면 좋을 것 같습니다 👍

2023-09-28 13:34 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoManager.java
> +    String upload(MultipartFile image, String parentDirectory);
최종적으로 `PhotoManger`에는 단건 처리만 존재하고, `PhotoService`에 목록 처리가 있는 것으로 구현하였습니다 🤓

2023-09-28 14:10 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoService.java
> +    public Photo save(MultipartFile file, String workingDirectory) {
좋습니다 !! 

제가 우려했던 부분은 `싱글 스레드가 10번 I/O 작업` vs `10개 스레드가 I/O 작업`이 후자가 반드시 I/O 효율이 좋지는 않다는 점이었습니다 ~

최근에 CPU와 스레드와 관련된 내용의 글을 읽은 적이 있었는데, **CPU 코어의 수 보다 많은 스레드가 생성되어 I/O를 처리하는 경우, 싱글 스레드가 여러번 작업을 처리하는 것이 I/O 효율이 더 좋다라는 결과를 보여주는 내용**이 있더라구요 ㅎㅎ 이 내용도 100% 들어맞는 내용은 아니지만 흥미로운 내용이더라구요 ~

2023-09-28 14:13 UTC, Kim0914 approved these changes
변경해주신 부분 모두 확인했습니다 ~!

비동기관련해서 소소한 코멘트 하나 확인해주세용 ㅎㅎ

이만 approve 하겠습니둥 ~

2023-09-28 14:29 UTC, merged