Feature/#103 팔로우한 유저의 리뷰를 조회하는 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #179
Opened 2023-09-25 16:28 UTC by woo-chang

## 🔥 연관 이슈

* close: #103

## 📝 작업 요약

팔로우한 유저의 리뷰를 조회하는 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 경도, 위도, 경도 증가값, 위도 증가값을 통해 사각형을 만들고 해당 범위안에 있는 팔로잉 멤버들이 작성한 리뷰 목록을 조회하는 기능입니다.
- 멤버 이미지 경로는 `fetch join`으로 가져오지 않고, `default batch fetch size`를 통해 `MemberThumbnail`, `Thumbnail` 총 2번의 조회로 가져오도록 하였습니다.
- 리뷰 작성자의 팔로워 수는 리뷰 작성자들의 목록의 `IN`절 쿼리로 1번의 쿼리로 가져오도록 하였습니다.
- 리뷰 사진 목록도 위와 비슷하게 리뷰 목록의 `IN`절 쿼리로 1번의 쿼리로 가져오도록 하였습니다.
- 가게 북마크 여부는 로그인 멤버로부터 `Bookmark` 목록을 조회하는데 `fetch join`을 통해 `Store`와 함께 가져오도록 하여 1번의 쿼리로 로그인 멤버가 북마크하고 있는 모든 가게 ID 목록을 조회할 수 있도록 하였습니다

## 🌟 리뷰 요구 사항

> 1시간
> 생각보다 복잡한 로직들이 있어서 많이 어려웠습니다 🥲
> 작업 상세 설명 중 설명이 부족한 부분이 있다면 언제든지 질문 환영입니다 :)

2023-09-28 13:59 UTC, Kim0914 requested changes
반가워요 그레이입니다 ㅎㅎ

코드를 가독성 좋게 너무너무 잘 짜주셨네요 !
특히 스트림과 queryDsl을 활용한 코드가 인상깊었습니다 👍

코멘트 몇 개 남겨봤는데 확인부탁드려요 😀
고생많았습니다 ~

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/CoordinateRequest.java
> +        BigDecimal deltaY
증가값이 양수인지에 대한 검증은 없어도 될까요?ㅎㅎ

아래 로직으로 들어가면 subtract, add를 수행하는데 혹시나?!

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryImpl.java
> +                        ltLastReviewId(lastReviewId),
여기서 궁금한게 하나 있슴다 ~
리뷰 조회 시 첫 번째 조회는 lastReviewId가 없으니 page 개수만큼 조회되고 응답으로 마지막 리뷰 ID를 전달한다고 이해했습니당.

그 이후의 요청에 lastReviewId를 담아서 클라이언트가 보내는데 lastReviewId 보다 작은 리뷰들을 조회하면, 첫 번째 조회이후에는 항상 같은 리뷰들만 조회되지 않나요?!!

orderBy 이전에 where 조건이 적용되나요??

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryImpl.java
> +        return jpaQueryFactory.selectDistinct(review)
(제가 생각해볼때는..?)  review는 항상 1의 입장이라서 중복 row가 나오지 않을 것 같은데`selectDistinct`를 사용해주신 이유가 궁금합니다 ㅎㅎ

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .collect(Collectors.toMap(
중요한건 아니지만 `Collectors` static import 해주면 좋겠네요 ~

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewPhotoCustomRepositoryImpl.java
> +                .orderBy(reviewPhoto.createdAt.asc())
`reviewPhotoId`로 정렬할 수 있을 것 같은데, 생성 시간을 기준으로 정렬해주신 이유가 궁금합니다 ㅎㅎ

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .collect(Collectors.groupingBy(
애플리케이션 단에서 적절한 `groupBy` 너무 좋네요 ㅎㅎ

요기도 static import 해주면 좋을 것 같아요 !

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                ));
스트림 괴수이시군요?

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .collect(Collectors.toSet());
요기도 !

static import가 가독성이 떨어진다고 생각하면 말씀주십쇼 ~

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Map<Long, List<String>> reviewIdPhotoPathsGroup = getReviewPhotoPathsGroup(reviews);
그냥 의견이 궁금해서 남겨봅니다 ㅎㅎ

리뷰 조회 시 사진 조회는 필수적으로 이뤄지는데요 !
항상 사진을 불러오려면 항상 추가적으로 쿼리가 나가고 있는건 아마 잘 알고 계실거라고 생각합니당.

Review에 Photo를 양방향 매핑해서 조회 시에만 사용하도록 할 수 있을 것 같은데 어떤가요?!

저는 개인적으로 생성, 삭제, 수정 시에 관리 포인트가 늘어날 것 같아서, 아직까지 성능 문제는 잘 모르겠어서 보류이긴합니다 !

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/member/domain/Member.java
> +    @OneToMany(mappedBy = "member", fetch = FetchType.LAZY)
`OneToMany`로 변경한 이유가 궁금하네요 ~

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/PaginationReviewResponse.java
> +@Schema(description = "리뷰 목록 페이지 조회 응답")
```suggestion
@Schema(description = "내 팔로잉의 리뷰 조회 응답")
```
말이 조금 어려운 것 같아서..ㅎㅎ

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/ReviewContentResponse.java
> +        @Schema(description = "리뷰 이미지 경로 목록")
example이 빠진 것 같아요 ~

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/ReviewPageInfo.java
> +                reviews.get(size - 1).getId(),
결과가 항상 정렬되어 있음이 보장되어 있겠죠?!

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryImpl.java
> +                        ltLastReviewId(lastReviewId),
아 이해했어요 ~

첫 번째 조회에는 해당 파라미터가 없으니 최신순으로 조회하면

reviewIds: 10, 9, 8, 7
lastReviewId = 7 이고

다음 요청은 7미만의 리뷰들만 조회하는거군요 ㅎㅎ

맞나용?

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +            @Valid CoordinateRequest coordinateRequest,
`@RequestParam`이나 `@RequestBody`를 안적어주면 어떻게 바인딩되나요?! 궁금하네요 ㅎㅎ

2023-09-28 13:59 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +                            .param("deltaY", "3.12"))
이렇게 넣으면 자동으로 객체에 바인딩 되나 보네요? 신기합니다

2023-09-28 13:59 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +        void 경도가_존재하지_않으면_400_응답을_반환한다() throws Exception {
저의 가게 검색 PR에 남겨주신 코멘트에 대한 질문이기도 한데요 !

파라미터 값이 누락되는 경우도 모두 테스트를 하는게 좋을까요?

파라미터가 누락되는 예외는 핸들링하는 부분이 프레임워크 자체적으로 해주는 부분이라 테스트를 하는게 맞는지 궁금하더라구요 ㅎㅎ

예외 메시지도 저희가 커스텀한게 아닌 프레임워크가 자제척으로 생성하는 메시지이기도 하구요 !

2023-09-28 13:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                lastReviewId,
`lastReviewId`가 존재하는 리뷰인지 확인하는 검증이 없어도 될까용?

해당 대상을 조회해서 사용하는게 아니라서 애매하네요

2023-09-30 13:51 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/CoordinateRequest.java
> +        BigDecimal deltaY
양수값인지 음수값인지에 따라 만들어지는 범위가 달라지고,

의도와 다른 결과를 조회할 수 있기에 해당 검증이 추가되는 것이 좋은 것 같아요👍

2023-09-30 13:54 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryImpl.java
> +                        ltLastReviewId(lastReviewId),
두번째로 이해하신 내용이 맞습니다 :)

데이터가 적을 때는 Offset 방법과 No Offset 방법에서 큰 속도 차이가 발생하지 않지만, 데이터가 증가하고 Offset 범위가 커짐에 따라 속도 차이가 발생할 수 있기에 우선적으로 No Offset 방식으로 구현해 보았습니다!

2023-09-30 14:03 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryImpl.java
> +        return jpaQueryFactory.selectDistinct(review)
리뷰 작성자가 내가 팔로우하고 있는 회원임을 알기 위해서는 팔로우 테이블과 조인이 필요하고 코드에서도 이를 확인할 수 있어요. 멤버와 팔로우는 `1:N` 관계이기 때문에 동일한 리뷰에 대해서 팔로우 데이터만 다른 여러 개의 `row`가 발생할 수 있고 이에 따라 `distinct` 처리를 해주었습니다 !

2023-09-30 14:05 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewPhotoCustomRepositoryImpl.java
> +                .orderBy(reviewPhoto.createdAt.asc())
`AI`를 사용하고 있고 `PK`로 인덱스가 걸려있기에 `ID`로 정렬하는 것이 훨씬 좋아보이네요 ㅎㅎ

2023-09-30 14:07 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                .collect(Collectors.toSet());
깔끔하니 너무 좋습니다 😎

2023-09-30 14:15 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Map<Long, List<String>> reviewIdPhotoPathsGroup = getReviewPhotoPathsGroup(reviews);
리뷰 조회 시 필수적으로 사진 조회는 이루어지는 것에 저도 동의합니다 ! 말씀해주신 양방향 문제도 충분히 고려해볼만한 부분이구요 😀

사진 경로 목록 조회를 별도의 쿼리로 진행한 이유는 다음과 같아요. 현재 저희는 `Review` <- `ReviewPhoto` -> `Photo`의 의존성 구조로 되어있어요. 그렇기에 Review에서는 ReviewPhoto와 양방향 연관관계를 맺게 되는데 실질적인 경로는 Photo에 존재하기 때문에 다시 한번 Photo를 조회해야하는 상황이 발생하게 됩니다.

`default batch fetch size` 설정을 사용한다하더라도 2번의 쿼리는 필수적으로 나가게 되는 상황입니다. 2번의 쿼리가 나가는 상황이 조금 비효율적이라 생각했어요. `ReviewPhoto`와 `Photo`는 1:1이기 때문에 join에 있어서도 `eq_ref` 타입의 실행계획이 발생할 것으로 생각되기에 1번의 쿼리로 해결하는 것이 좋다고 판단했어요.

위의 근거를 바탕으로 구현해보기로 했고 구현하였을 때 가독성도 나쁘지 않은 것 같아서 저도 아직 양방향 매핑하는 것에 대해 보류인 쪽에 가까운 것 같아요 🥸

2023-09-30 14:22 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/member/domain/Member.java
> +    @OneToMany(mappedBy = "member", fetch = FetchType.LAZY)
https://loosie.tistory.com/788

위의 링크를 참고하시면 더욱 좋을 것 같습니다! `default batch fetch size`를 통해 조회된 작성자들의 썸네일을 IN절을 통해 한번에 조회하려고 했으나, 각각 조회 쿼리가 나가는 문제를 확인했습니다. 해당 문제는 `@OneToOne`의 주인이 아닌쪽에서는 해당 데이터가 존재하는지 알 수 없기에 지연 로딩을 할 수 없다는 문제였습니다.

이를 해결하기 위해서는 `@OneToMany`로 변경이 불가피했고, 그에 따라 애플리케이션 코드 레벨로 썸네일을 1개만 등록할 수 있도록 하고 1개만 조회할 수 있도록 수정하였습니다 :)

2023-09-30 14:24 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/ReviewPageInfo.java
> +                reviews.get(size - 1).getId(),
조회 쿼리를 통해 정렬되어 있음을 보장하고 있습니다 !

2023-09-30 14:29 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +            @Valid CoordinateRequest coordinateRequest,
`dto`로 파라미터를 매핑하고 싶은 경우 `@RequestParam`를 적지 않아도 변수명을 통해 매핑이 수행됩니다 🤓

2023-09-30 14:35 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +        void 경도가_존재하지_않으면_400_응답을_반환한다() throws Exception {
처음에는 꼼꼼하게 모두 테스트하는 것이 좋다고 생각하였으나, 말씀해주신대로 프레임워크가 제공하는 기능이기 때문에 모든 상황에서 테스트할 필요가 없다고 생각합니다!

<img width="911" alt="스크린샷 2023-09-30 오후 11 32 56" src="https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/78212016/e0c892a3-89aa-459d-b748-4cbef43a1b88">

`@NotNull`을 붙였음에도 프레임워크가 제공해주는 메시지가 보여서 무엇때문인지 궁금했었는데, `GlobalExceptionHandler`에서 상속한 `ResponseEntityExceptionHandler`에서 예외처리를 진행하고 있더라구요. 그래서 해당 메서드를 `@Override`해서 커스텀하려고 했으나 `deprecated` 되어서 오버라이드도 수행할 수 없었습니다.

따라서 해당 상속을 제거하고 직접 예외 처리를 구현할 수 있도록 수정하였더니 원하는 메시지를 확인할 수 있었습니다. 저희 커스텀 예외 메시지만 내려주기 위해서는 해당 상속을 제거하는 것도 괜찮은 방법이라 생각하는데 이 부분에 대해서는 어떻게 생각하시나요 ?!

2023-09-30 14:38 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                lastReviewId,
리뷰 ID가 1, 3, 5, 7, 9가 존재하는 상황에서 `8`을 입력하더라도 1, 3, 5, 7 리뷰를 조회할 수 있는 상황이 발생할 수 있을 것 같아요!

양수 ID 검증을 통해 최소한의 조회는 하고 있기에 해당 리뷰가 존재하는지에 대한 여부는 검증하지 않아도 될 것 같다고 생각하는데 어떻게 생각하시나요? 🧐

2023-09-30 15:04 UTC, woo-chang commented
추가적으로 `GeoConfig` 코드를 보면 `JVM` 설정을 변경해주는 것을 확인할 수 있습니다 !

해당 설정은 좌표 간 거리 계산을 위한 `JTS` 라이브러리를 사용할 때 `(y, x)`가 아닌 `(x, y)`로 인식하도록 하는 설정입니다. 해당 설정을 애플리케이션 실행 시에 `-D` 인자를 통해 설정할 수도 있고 `GeoConfig` 처럼 코드 레벨로도 설정할 수 있습니다.

저는 실행시에만 확인하기보다는 코드 레벨로 명확하게 명시하고 해당 애플리케이션 코드를 보는 사람은 누구든 확인할 수 있게 코드 레벨로 설정하는 것이 좋은 것 같아 코드 레벨로 남겨두었는데, 이 부분에 대한 커멘트도 해주시면 감사합니다 ㅎㅎ

2023-10-01 09:43 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        Map<Long, List<String>> reviewIdPhotoPathsGroup = getReviewPhotoPathsGroup(reviews);
좋아요 ~~

아직까지 매핑 테이블 없이 양방향연결 or 지금처럼 매핑 테이블 구조 사용 중에 정말 어떤 방식이 최적화된 방식인지는 감이 잘 안오더라구요 ㅎㅎ (사실 지금도 크게 맞아본 적이 없어서)

우-창님이 말씀해주신 내용을 토대로 생각해보니 지금은 현 구조를 유지하는게 좋을 것 같네요 :)

2023-10-01 10:35 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +        void 경도가_존재하지_않으면_400_응답을_반환한다() throws Exception {
상속을 제거하는 것은 반대입니다 ! 
`ResponseEntityExceptionHandler`의 상속을 제거할만큼 이 상황에서 커스텀 예외 메시지의 가치가 있는지 고민해보면 좋을 것 같아요.

우선 이 테스트가 꼭 필요한 테스트인지 의문이 드는 것 같아요. 우리가 컨트롤러의 `@PathVariable` 값 검증을 테스트할 때 **음수**, **양수**, **범위**의 검증 테스트를 하고 `@PathVariable` 파라미터가 없는 상황은 가정하지 않는 것처럼 `파라미터 자체가 없는 것은` 프레임워크의 검증 책임이 아닐까 생각이 드는 것 같습니다. 프레임워크가 제공하는 메세지도 충분하다는 생각이 드네요 !

`@RequestBody`의 `@NotNull`과는 별개로요 ! `@RequestBody`의 `@NotNull`은 검증이 필요한 부분이라고 생각합니다.

그래서 꼭 이 검증이 필요하다고 생각되면 지금정도면 충분하다는 생각이 드네요 😀


추가로 ~~~~
`BindingException`이 deprecate되고 `MethodArgumentNotValid~`로 다 대체되었는데 저게 남아있는 건 스프링 자체의 버그라고합네다.. 6월 말에 다시 merge 됐더라구용
<img width="1192" alt="image" src="https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/68818952/5b4eb349-550b-4b6d-aa61-30e23885f245">

2023-10-01 10:38 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +                lastReviewId,
검증하지 않아도 괜찮을 것 같아요 ~

2023-10-01 12:07 UTC, Kim0914 requested changes
리뷰 반영에 리팩토링까지?!
너무너무 고생많으셨네요 ㅎㅎ

추가로 몇 가지 더 궁금한 점이 있어서 코멘트로 남겼습니다 !
확인부탁드려요 👍

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkQueryService.java
> +public class BookmarkQueryService {
cqrs 준비 들어가는건가용?

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkQueryService.java
> +@Transactional(readOnly = true)
메서드단에 붙여주기로 컨벤션 설정했던 것 같아요 !

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowCustomRepository.java
> +    }
결국 팔로우 수를 사용하기 위해서는 어떤 계층에서 Map<Long, Long> 형태로 변환되어야 할 것 같은데요 !
현재는 해당 기능을 dto에서 변환하고 있어서 어떤 계층에서 해주는 것이 적절한지 우~창님의 생각이 궁금하네용

제가 생각하는 각각 계층에서의 포인트를 남겨볼게요 !

* dto에서 변환한다.
Map 형태로 제공하는 것은 view(클라이언트)의 관점이기 때문에 dto에서 변경해야한다.

* 서비스 계층에서 변환한다.
사용자(백엔드 개발자)가 사용하기 위해서는 Map 형태로 변환되어야한다.
List<Dto>를 Map으로 변환하면서 `(exist, replace) -> replace`를 처리해주는 코드는 애플리케이션의 책임이다. 
다른 계층에서 사용할 수도 있기 때문에 서비스 계층에서 변환한다.

* CustomRepository 계층에서 변환한다.
결국 사용자(백엔드 개발자)가 사용하기 위해서는 Map 형태로 변환되어야한다.
List<Dto>로 Repository에서 반환하는 것은 가공되지 않은 데이터로 반환하는 것이기 때문에 Map으로 가공해서 반환한다.

2023-10-01 12:07 UTC, Kim0914 commented on build.gradle
> +    implementation 'org.geotools:gt-epsg-hsql:29.2'
`29.2`버젼은 최신 버젼인가요?!

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/dto/ReviewToPhotoPathDto.java
> +    }
여기도 동일하게 고려해볼 수 있겠네요 ㅎㅎ

Dto의 책임인지 아닐지 !

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/ReviewResponse.java
> +                                PointUtils.generate(deviceX, deviceY),
이전 커밋에는 거리를 계산해주지 않았던 것 같은데 추가된 이유가 궁금해요 !!

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/DeviceCoordinateRequest.java
> +        BigDecimal deviceY
`사용자 위치 좌표` vs `디바이스 좌표` ?? 🤓

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(BindException.class)
스프링에서 Deprecated 시켜서 없애도 될 것 같아요 ~

2023-10-01 12:07 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
이거는 위에 코멘트로 남겼씁니다 ~

2023-10-01 12:07 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/global/util/PointUtilsTest.java
> +        assertThat(Math.round(result / 10) * 10).isEqualTo(15480);
일직선 상 거리로 보여주기로 결정되었나요?!

2023-10-01 12:41 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
> +        void 경도가_존재하지_않으면_400_응답을_반환한다() throws Exception {
좋은 의견 감사합니다 ㅎㅎ

어디까지 검증이 필요한지는 끊임없이 고민하게 되는 부분인 것 같아요 😂 설명해주신 말을 듣고 조금 더 명확해진 것 같습니다 :)

예외 메시지는 해당 메시지를 처리하는 클라이언트와도 얘기가 필요한 부분이라고 생각해요. 클라이언트에서 예외 발생 시 별도의 예외 메시지를 생성해서 사용하는 경우는 상관없지만, 저희 프로젝트처럼 클라이언트에서 서버에서 내려준 예외를 그대로 사용자에게 보여주는 상황에서는 프레임워크가 제공하는 예외 메시지를 그대로 사용할 수 없을 것 같아요. 물론 매개변수 전달은 코드 레벨에서 발생하는 예외 상황이기에 사용자가 해당 예외를 보는 상황은 거의 없다고 판단되지만, 커스텀 예외 처리도 상황에 가장 알맞은 방법을 선택하면 될 것 같네요 ㅎㅎ

코드를 읽어볼 때 전부 대체되었다는 설명을 읽었는데 정확한 이유를 확인하지 못했어요. PR을 직접 확인해보시고 이유를 설명해주셔서 감사합니다 🙇🏻‍♂️ 저희가 사용하고 있는 스프링 버전이 해당 PR이 merge 되기 전 버전이라 이전의 버그가 남아있는 것 같아요. 추후에 스프링 부트 버전업도 고민해볼 수 있겠네요!

마지막으로 상속으로 인해 얻는 편의가 크다고 판단되기에 다시 살리는 방향으로 수정하도록 할께요 ~~

2023-10-01 13:03 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkQueryService.java
> +public class BookmarkQueryService {
이후에 개발되는 리뷰 목록 조회 기능에서도 동일한 기능들을 재사용할 것 같아 서비스 분리를 통해 재사용할 수 있도록 미리 구현해보았습니다 😀 기능 개발과 리팩토링을 함께하다보니 코드 리뷰하는데 어려움을 드렸던 것 같네요 🥲

2023-10-01 13:06 UTC, woo-chang commented on build.gradle
> +    implementation 'org.geotools:gt-epsg-hsql:29.2'
넵넵 확인했을 때 가장 최신 버전을 사용하였습니다!

2023-10-01 13:49 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkQueryService.java
> +public class BookmarkQueryService {
좋아용 !

2023-10-01 13:50 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowCustomRepository.java
> +    }
각각의 계층에서의 관점을 잘 설명해주셨네요 ㅎㅎ

결국 변환 책임은 어디있는지에 대한 것이 관건인 것 같아요 ! 저는 아래의 흐름대로 생각했던 것 같아요 :)

- `Repository` 계층에서는 특정 조건에 알맞은 **데이터를 조회하는 책임**이 있다. 데이터를 조회하는 것이 가장 큰 핵심이기 때문에 객체의 관점에서보다는 데이터 관점에 알맞은 형태를 반환해야한다고 생각했어요. 따라서 컬럼으로 이루어진 데이터 관점에서 `Map` 형태보다는 `row` 형태의 목록을 반환하는 것이 적합하다고 생각해요. 따라서 해당 책임이 상위 계층인 `Service`로 우선 넘어가게 됩니다.
- `Service` 계층에서는 **요구사항에 알맞게 로직을 처리하여 적절한 결과**를 만들어내는 책임이 있다. 로직을 처리하기 위해서는 조회한 데이터를 원하는 형태로 변환이 필요해요. **그렇기에 Service에서 변환을 처리하는 것이 가장 적절하다고 생각합니다.** 하지만 해당 계층에서 가장 중요한 요소는 로직을 처리하는 과정이라고 생각해요. 여기서 모든 데이터의 변환이 발생하면 실질적인 로직보다 변환 로직이 더 많아지는 상황이 발생할 수도 있다고 생각해요. 그렇기에 데이터 변환 책임을 `DTO`로 넘겼습니다.
- 변환하는데 복잡한 로직이 없는 이상 `DTO`에 변환 로직이 있어도 된다고 생각해요. 결국 가장 큰 장점은 서비스 계층에서의 코드 가독성과 유연성일 것 같아요. `(exist, replace) -> exist`로 변환 방법이 변한다고 하더라도 로직이 모여있는 서비스 코드를 수정하는 것이 아니라 DTO 변환 코드만 수정함으로 Service에서는 DTO를 그대로 사용하기만 하면 됩니다.
- 엔티티를 응답 객체로 바꿀 때도 서비스에서 필요한 값만 하나씩 전달해서 바꾸는 방법이 있지만, 해당 방법을 사용하지 않는 이유와 비슷한 이유라고 생각합니다 😀

2023-10-01 13:51 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/dto/ReviewToPhotoPathDto.java
> +    }
위의 코멘트에 답변 남겼습니다 ~

2023-10-01 13:52 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/ReviewResponse.java
> +                                PointUtils.generate(deviceX, deviceY),
단톡방에서 프론트 개발자분께서 서버에서 거리 계산을 원하신다고 말씀해주셔서 수정하였습니다 !

2023-10-01 13:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/request/DeviceCoordinateRequest.java
> +        BigDecimal deviceY
사용자 위치 좌표가 더욱 명확하네요 👍

2023-10-01 13:56 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/global/util/PointUtilsTest.java
> +        assertThat(Math.round(result / 10) * 10).isEqualTo(15480);
이 부분도 프론트분과 얘기가 필요한 부분인 것 같네요 !

실제 지도에 존재하는 도로를 반영하여 거리를 계산하려면 외부 API를 사용해야할 것 같아요. 서버에서 모든 것을 구현하기에는 구현할 수 있을지도 모를뿐더러, 구현 가능하다 하더라도 너무 많은 비용이 드는 작업이라 생각해요 🥲

도로에서 거리까지 고려가 필요한지도 고민이 필요한 부분인 것 같은데 이 부분에 대해서 어떻게 생각하시나요?!

2023-10-01 14:01 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/global/util/PointUtilsTest.java
> +        assertThat(Math.round(result / 10) * 10).isEqualTo(15480);
저희 서비스가 길찾기 기능을 제공해주는 것이 아니라서 보다 정확한 거리를 보여줄 필요는 없다고 생각해요 ㅎㅎ
저는 일직선 거리만으로도 충분한 것 같습니다 !

2023-10-01 14:03 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/global/util/PointUtilsTest.java
> +        assertThat(Math.round(result / 10) * 10).isEqualTo(15480);
여담이지만 ㅎㅎ
네이버 지도에서 장소 검색했을 때 나타나는 거리와, 길찾기를 했을 때 나타나는 거리도 다르더라구요 ~~
장소 검색 거리는 분명 직선거리인 것 같고, 길찾기 거리는 실제 운행 거리인 것 같았어요 !
그래서 지금도 너무너무 충분한 것 같습니다 ~

2023-10-01 14:09 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowCustomRepository.java
> +    }
확실한 근거를 가진 정성스러운 답변 너무 감사합니다 🙇🏻

변환 과정을 서비스에서 처리하느냐, DTO에서 처리하느냐가 가장 큰 관심사인 것 같더라구요 !
서비스 계층에서 처리하면 한 Layer에서 모든 코드를 확인할 수 있다는 장점이 있었고, DTO에서 처리하면 서비스는 변경하지 않고 DTO만 변경하면 된다는 장점이 있는 것 같네요 👍

2023-10-01 14:11 UTC, Kim0914 approved these changes
고생많으셨습니다 !

리뷰 반영해주신 것과 코멘트 모두 확인했습니다 ㅎㅎ
이만 approve 하겠습니다 :)

2023-10-01 14:35 UTC, merged