Feature/#107 이름으로 가게를 검색하는 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #180
Opened 2023-09-25 16:56 UTC by Kim0914

## 🔥 연관 이슈

close: #107 

## 📝 작업 요약
가게 검색 기능을 구현했습니다.

## 🔎 작업 상세 설명

MySql의 공간 함수를 사용하기 위해 `nativeQuery`를 사용했습니다.

JPQL을 사용하지 않은 이유는 SELECT절에서 공간 함수를 사용하기 위해서는 별도의 bean 설정을 추가해야합니다.
SELECT절은 properties에 설정된 dialect에 해당하는 함수를 실행시켜 ORM 매핑을 하는데, 공간 함수는 등록되어 있지 않습니다 !

가게 검색 시을 위해 작성한 쿼리는 아래와 같습니다.
가게 검색 시 필요한 데이터는 `가게 ID`, `가게 이름`, `사용자와의 거리`, `가게 리뷰 개수` 입니다 :)
```sql
SELECT 
      s.id as storeId, 
      s.store_name as storeName,
      ST_Distance_Sphere(ST_PointFromText(CONCAT('POINT(', :y, ' ', :x, ')'), 4326), s.coordinate) as distance,
      COUNT(r.id) as reviewCount                   
FROM Store s
LEFT JOIN Review r ON r.store_id = s.id
WHERE s.store_name LIKE CONCAT('%', :name, '%')
GROUP BY s.id
ORDER BY ST_Distance_Sphere(ST_PointFromText(CONCAT('POINT(', :y, ' ', :x, ')'), 4326), s.coordinate) ASC
LIMIT :size OFFSET 0
```

현재 가게 - 리뷰수를 관리하는 테이블이 없기 때문에 JOIN을 이용해 해당 가게의 리뷰 수를 계산합니다.
서브 쿼리를 사용하지 않은 이유는 MySQL에서 서브 쿼리의 성능이 좋지 않기 때문입니다.(5.7 이후에 개선되었다고 하나 그래도 좋지 않다고 함 !)

`LEFT JOIN`을 사용한 이유는 리뷰가 없는 가게 케이스가 존재할 수 있기 때문입니다.
일반 `JOIN`을 하게 되면 리뷰가 없는 가게는 조회를 하지 않습니다 !

- LEFT JOIN을 사용해 조회한 결과
![image](https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/68818952/16208663-b308-4230-90f1-9d72f28075d9)

- JOIN을 사용해 조회한 결과
![image](https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/68818952/f1ede06e-efcf-470d-9149-bb3518c4a00d)

* URL에 `search`를 담을지 말지 고민이 되었는데, 가게를 `조회`하는 성격보다 `검색`의 성격이 강하다고 생각해 `search`를 URL에 포함시켰습니다 !

* 검색 결과 최대 개수는 30개로 설정했습니다.

## 🌟 리뷰 요구 사항

쿼리를 제외하고는 간단한 조회입니다 :)

> 30분

2023-09-26 05:31 UTC, woo-chang requested changes
코드 잘 읽었습니다 🙇🏻‍♂️ 네이티브 쿼리부터 거리 계산까지 잘 구현해주셨네요 👍

몇 가지 컨벤션과 의견이 궁금한 부분에 대해 커멘트 남겨두었으니
확인해주시면 감사합니다 ㅎㅎ

2023-09-26 05:31 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
> +    class 가게를_조회할_때 {
조회에 대한 행동을 하나로 묶어주셨네요 😀

저는 지금까지 테스트해야할 메서드가 같은 경우에만 `@Nested`를 사용해서 묶도록 하고 있었습니다. 그 이유는 동일한 메서드에 대한 테스트를 묶어서 여러 가지 상황을 비교해볼 수 있다는 장점 때문이었습니다!

행동을 묶는 것도 좋은 방법이라고 생각합니다! 하지만 2가지 방법이 혼용되어있으면 나중에 헷갈릴 것 같아서 하나로 통일하면 좋을 것 같은데 어떤 방법이 좋을까요?

2023-09-26 05:31 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
> +                assertThat(responseStoreIds).containsExactly(storeA.getId(), storeB.getId(), storeD.getId());
조회할 때 특정 정렬 조건이 없으면 기본적으로 `ID`를 오름차순으로 가져오더라구요! 처음 저장하는 가게의 거리를 멀리 설정하여 저장 순서와 관계없이 거리 순으로 가져오는 것을 확인할 수 있도록 해보는건 어떨까요?

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +            @Param("size") int size);
여기도 `)`를 아래로 내리는건 어떨까요 :)

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +
개행이 들어가있어요 ㅎㅎ

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        validateName(name);
`Controller`에서 해당 검증이 수행되고 있는 것으로 확인했는데 한번 더 검증을 진행하는 이유가 있으신가요? 🤔

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponse.java
>  public class StoreSearchResponse implements StoreSearchQueryResponse {
해당 클래스를 구현하도록 하신 이유가 궁금합니다 ! 해당 의존성이 없어도 괜찮지 않을까라는 생각이 들었어요 :)

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +                .toList();
```java
List<StoreSearchResponse> searchResponses =
                         storeRepository.search(
                                 name,
                                 memberCurrentPoint.getX(),
                                 memberCurrentPoint.getY(),
                                 size
                         )
                         .stream()
                         .map(StoreSearchResponse::from)
                         .toList();
```
요런 비스무리하게 코드 컨벤션을 수정해보는건 어떨까요 ㅎㅎ

2023-09-26 05:31 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
>              List<StoreSearchQueryResponse> searchResponses = storeRepository.search(name, x, y, 10);
리뷰 개수도 잘 가져오는지에 대한 테스트도 추가되면 좋을 것 같아요 !

2023-09-26 05:31 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
> +        void 단어가_포함된_가게들을_사용자_위치에서_가까운_순으로_조회한다() {
`StoreTestPersister`를 사용해서 `given` 부분을 조금 간소화할 수 없을까요 :)

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
> +    @Operation(summary = "가게 검색 결과 조회",
첫 부분도 개행이 들어가면 좋을 것 같아요 ㅎㅎ

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
> +                    요청 예시: /v1/stores/search?name=김밥&x=123.5156&y=36.1425&size=15
꼼꼼한 설명 너무 좋은데요 👍👍

2023-09-26 05:31 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerTest.java
> +        void 사용자의_경도_값이_숫자가_아니면_400_응답을_반환한다(String x) throws Exception {
위도, 경도가 파라미터에 없는 경우에 대한 테스트도 있으면 더욱 체고 👍

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +            nativeQuery = true,
네이티브 쿼리 작성하시느라 고생하셨습니다 👍 직관적인 것 같으면서도 관리가 어렵다는 생각도 드는 것 같아요.

저도 동일하게 공간 함수를 사용하는 로직을 `Querydsl`로 작성해 보았는데, 확인해보시고 수정 가능한 부분이 있다면 수정해보는 건 어떨까요? 🤓

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +                        ST_Distance_Sphere(ST_PointFromText(CONCAT('POINT(', :y, ' ', :x, ')'), 4326), s.coordinate) as distance,
`4326` 상수를 `PointUtils`에서 관리하고 있는데 해당 값을 `getter`로 가져와서 사용하는 방법은 어떠신가요?

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +                        ST_Distance_Sphere(ST_PointFromText(CONCAT('POINT(', :y, ' ', :x, ')'), 4326), s.coordinate) as distance,
`CONCAT`없이 `POINT(:y, :x)`로 바로 해당 문자열을 만들 수는 없는건가요?!

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +                    LEFT JOIN review r ON r.store_id = s.id
리뷰 개수를 구할 수 있는 방법이 2가지가 떠오르는 것 같아요 ㅎㅎ
1. 리뷰 테이블과 조인해서 개수를 세는 방법
2. 가게 ID 목록 IN절을 통해 리뷰 테이블을 순회하면서 IN절에 있는 가게 리뷰 카운트를 세는 방법

2가지 방법 중 조인을 선택한 이유가 궁금합니다 !

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponses.java
> +public record StoreSearchResponses(
이 부분도 항상 고민되던 부분이었는데 `StoreSearchesResponse` vs `StoreSearchResponses`

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +            @Param("y") double y,
위도, 경도는 정밀도를 위해 `BigDecimal`을 사용하기로 했던 것 같은데 `double`을 사용한 이유가 있으신가요? 😀

요청에서는 `BigDecimal`을 사용하지만, `Point`에서 값을 얻을 때는 `double`을 사용해서 계속 헷갈리고 혼용되더라구요. 언제 BigDecimal을 써야할지, 언제 double을 써야할지 🥲

이 부분에 대해서도 같이 얘기해보고 결정하면 좋을 것 같아요 !

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponse.java
> +    private long reviewCount;
`example` 값도 설정해주면 좋을 것 같아요 :)

2023-09-26 05:31 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
> +                            5.검색 결과 수가 0이하인 경우
사용자 위치의 경도나 위도값이 없는 경우도 추가되면 좋을 것 같아요 !

2023-10-01 12:16 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
> +                assertThat(responseStoreIds).containsExactly(storeA.getId(), storeB.getId(), storeD.getId());
Good !

2023-10-01 12:16 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
> +    class 가게를_조회할_때 {
테스트는 메서드를 확인하는 과정이니 메서드 기준으로 묶어주는게 좋을 것 같네요 ㅎㅎ

2023-10-01 12:26 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        validateName(name);
이 부분 고민이 많이 되었는데, 키워드 기반 조회 기능라서 검증을 한번 더 넣어주는 것이 DB를 보호할 수 있다고 생각했었습니다 !

지금 또 생각해보면 검색 컨트롤러에서만 사용되기 때문에 굳이 라는 생각이 들긴 하네요 ㅎㅎ

2023-10-01 13:01 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
>              List<StoreSearchQueryResponse> searchResponses = storeRepository.search(name, x, y, 10);
굿굿 좋아요 !

2023-10-01 13:05 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponse.java
>  public class StoreSearchResponse implements StoreSearchQueryResponse {
인터페이스로 쿼리 결과를 받는 것을 구체 클래스가 받도록 명시해야할 것 같아서 구현하도록 했는데, 굳이 안해도 되겠네요 !

2023-10-01 13:17 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
> +        void 단어가_포함된_가게들을_사용자_위치에서_가까운_순으로_조회한다() {
적용했습니다 !!

2023-10-01 13:36 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerTest.java
> +        void 사용자의_경도_값이_숫자가_아니면_400_응답을_반환한다(String x) throws Exception {
추가했어욤 !

2023-10-02 11:29 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +            nativeQuery = true,
좋습니다 ㅎㅎ
QueryDsl 기반으로 변경완료했습니다 ~~ 중간에 컴파일 문제가 있어서 꽤 해맸는데,,, 
공간 함수와 같이 db에 종속되는 함수들은 nativeQuery가 더 편한 것 같기도 하네요 ㅎㅎ

2023-10-02 11:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +                        ST_Distance_Sphere(ST_PointFromText(CONCAT('POINT(', :y, ' ', :x, ')'), 4326), s.coordinate) as distance,
둘 다 반영완료 !

2023-10-02 11:37 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +            @Param("y") double y,
저도 말씀해주신 것과 동일한 고민이 들었는데요 !

현재 애플리케이션에서 `Point`객체를 사용하고 있고, DB에 질의를 하기 위해 좌표를 담기 위해서는 이 객체에서 꺼내서 써야합니다(`VerifiedCoordinate` 검증도 포함되어 있기 때문에).

**그래서 요청을 받고 애플리케이션 내에 담을 때 -> BigDecimal
좌표 값을 꺼내어 쓸 때 -> doublce**

이렇게 사용해야할 것 같아요.
조금 혼란스럽긴 한데, 좌표를 꺼내기 위해서 객체에 접근할 때 모두 double로 반환하고 있기 때문에 괜찮을 것 같다는 생각이 드네요 !

2023-10-02 11:46 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponses.java
> +public record StoreSearchResponses(
저는 후자를 주로 사용합니다 !

`StoreSearches`라는 의미가 검색을 여러번 했다는 의미가 있는 것 같아서 `StoreSearchResponses`를 사용합니다 !

가장 정확하게 하자면 `StoreSearchResponse`가 맞는 것 같아요 ㅎㅎ
하지만 단건 검색 결과를 담는 dto이기에 `StoreSearchResponses`가  복수개 있는 의미도 담을 수 있는 것 같아요 !

2023-10-02 11:49 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +                    LEFT JOIN review r ON r.store_id = s.id
쿼리 한 방으로 가져오고 싶고 서브 쿼리를 작성하지 않기 위해 JOIN을 선택했습니다 !

애플리케이션 단에서 List<Store> stores를 정제했다면 IN절을 사용했을 것 같아요 ㅎㅎ
말씀해주신 IN절을 사용한다면 아래의 흐름으로 조회된다고 생각하는데 맞을까요?!😀

`해당 이름을 가진 가게들 조회` -> `해당 가게들의 리뷰 수 조회` -> `각각의 결과를 dto로 감싸서 반환`

2023-10-02 11:50 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
> +                            5.검색 결과 수가 0이하인 경우
완료우

2023-10-02 13:57 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        validateName(name);
꼼꼼한 검증 너무 좋다고 생각해요 👍

레벨1, 2때 한창 하던 고민이 떠오르네요 ㅎㅎ 매개변수의 검증은 어디서 해야하고, 어디까지 해야하는가와 같은 고민을 하던게 엊그제 같은데 벌써 시간이 이렇게 지났네요.

현재 검증하고 있는 내용이 컨트롤러에서 진행하는 검증과 동일하기에 어색하다고 느껴진다고 생각해요. 아직 검색어에 대한 별다른 제약조건이 존재하지 않기 때문에 검증할 내용이 없어서 그런 것 같아요. 말씀해주신 것처럼 검색어 관련 요구사항이 추가된다면 해당 검증을 `Service` 계층에서 진행하는 것은 전혀 어색하지 않을 것 같아요!

따라서 현재는 중복되는 검증을 제거하고 추후에 제약조건이 생기면 검증을 진행하는게 어떨까요 ? 😎

2023-10-02 14:06 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +                    LEFT JOIN review r ON r.store_id = s.id
적어주신 흐름이 맞습니다 ㅎㅎ

MySQL 책에서는 고성능 애플리케이션에서는 다중 테이블 조인 대신 단일 테이블 쿼리를 실행 후 애플리케이션에서 조인을 수행하여 조인을 분리할 수 있다고 하더라구요. 1개의 쿼리가 여러 쿼리가 됨으로 낭비가 아닐까라는 생각이 들 수 있지만, 여러 개의 쿼리로 재구성함으로서 각각 쿼리에 대한 캐싱을 사용한다던지, 테이블 분리가 용이하다던지, 전체적인 트래픽과 메모리 사용량을 줄일 수 있다는 장점이 있다고 합니다.

사실 위와 같은 내용은 직접 맞아보지 않아서 몸소 와닿지 않는 장점들이긴 해서 지속적으로 운영하면서 알아가봐도 좋을 것 같아요 🥸

2023-10-02 14:08 UTC, woo-chang approved these changes
꼼꼼하게 수정 잘 해주셨네요 👍👍

다음으로 가시죠 😆

2023-10-02 14:26 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
> +        validateName(name);
Zoayo ~

2023-10-02 14:31 UTC, merged