Feature/#134 가게 리뷰 목록 조회 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #192
Opened 2023-10-09 13:10 UTC by Kim0914

## 🔥 연관 이슈

- close: #134

## 📝 작업 요약

가게 리뷰를 조회하는 기능입니다.

## 🔎 작업 상세 설명

특정 가게에 대한 리뷰를 조회합니다.

필터링 조건을 이용해 `친구들` 리뷰만 조회할 수 있습니다.

## 🌟 리뷰 요구 사항
* 클라이언트 측에서 `모든 리뷰`, `친구들` 화면에서 `lastReviewId`를 가지고 있을 수 있다고 하여 필터링 구분 없이 하나의 `lastReviewId`로 응답하게끔 구성했습니다.

* 가게 단건 조회(findById) 시 카테고리를 fetch join하도록 변경했습니다.
가게 리뷰 조회 기능에서는 가게가 1개 밖에 없어 lazy loading을 해도 성능상 큰 이슈는 없을 것 같긴 한데.. fetch join해도 카테고리 row 개수가 정말 작아서 큰 문제가 없지 않나 생각했어요. 그래서 우선 fetch join을 이용해 한번에 가져오도록 해놓았습니다 !

* 필터링 조건에 따라 동적으로 join이 발생합니다.
`ReviewFilter` Enum 객체의 값에 따라 join을 할지 말지 결정합니다.
처음 동적 join을 사용해보았는데, 관련해서 함께 봐주시면 감사하겠습니다 :)

> 30분

2023-10-11 07:12 UTC, woo-chang requested changes
안녕하세요 그레이 ! 다즐입니다 ㅎㅎ

동적으로 조인하는 부분 확인했습니다 !
잘 구현해주셔서 크게 수정할 부분은 없고
작고 소소한 커멘트와 몇 가지 질문 남겨두었으니 확인해주시면 감사합니다 🙇🏻‍♂️

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkQueryService.java
> +    }
`getBookmarkStoresByMember` 메서드를 활용해서 멤버의 모든 북마크한 가게 ID 목록을 구해서 각각 가게마다 조회 쿼리를 날리지 않는 방법도 있는데 각각 쿼리를 날리는 메서드를 구현하신 이유가 궁금합니다 🤓

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +    public StoreReviewResponse getReviewByStore(
일관성있게 복수형을 사용하는건 어떨까요?!

`getReviewByStore` -> `getReviewsByStore`

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkQueryService.java
> +    }
아 잘못 이해했어요 🤑

가게에 대한 리뷰 목록 조회라서 단건 조회로 해결할 수 있는 부분이네요 ㅎㅎ

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +        );
사소한 커멘트이지만 해당 메서드들은 개행 없이 붙여도 좋을 것 같은데 어떻게 생각하시나요?

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewContentResponse.java
> +public record StoreReviewContentResponse(
`Response`에 대한 `@Schema`도 작성해주시면 감사합니다 🙇🏻‍♂️

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewResponse.java
> +public record StoreReviewResponse(
여기도 `@Schema` 😀

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewResponse.java
> +        ReviewStoreResponse reviewStoreResponse,
이미 가게 정보를 알고 있는 상황으로 이해했는데 추가적으로 가게 정보를 주는 이유가 있으신가요?!

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewContentResponse.java
> +    public static StoreReviewContentResponse of(
다른 `record`와 일관성 있게 개행 한칸 주는건 어떤가요?!

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewResponse.java
> +    public static StoreReviewResponse of(
`ditto`

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewResponse.java
> +        ReviewStoreResponse reviewStoreResponse = getReviewStoreResponse(
저는 응답 객체를 생성할 때 `get`보다 `convert`를 선호하는 편입니다 !

일관성 있게 통일하면 좋을 것 같은데 어떤 것이 더 나으신가요?!

2023-10-11 07:12 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewServiceTest.java
> +                softly.assertThat(reviewPageInfo.lastId()).isEqualTo(reviewA.getId());
페이지 정보까지 꼼꼼하게 테스트해주셨네요 👍

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                    """
불필요한 공백이 있는 것 같아요 ㅎㅎ

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +    ResponseEntity<StoreReviewResponse> getReviewsByStore(
존재하지 않는 가게 ID로 요청할 경우 `404` 예외도 발생하지 않을까요? 🤓

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
> +    @EntityGraph(attributePaths = {"category"})
카테고리는 항상 존재하고 항상 함께 필요한 경우가 많기에 `fetch join` 하는 것이 좋은 선택인 것 같아요 ㅎㅎ

2023-10-11 07:12 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomServiceTest.java
> +                10);
마지막 `);` 개행해주시면 감사합니다 😊

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +            String filter,
`filter`를 `controller`에서 변환해주는 것과 `service`에서 변환해주는 것 중 후자를 선택하신 이유가 궁금해요 ㅎㅎ

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
> +                jpaQuery.where(
동적으로 조회하는 쿼리이군요 👍 배워갑니다 ~

2023-10-11 07:12 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
> +        void 친구_필터링이_있으면_팔로워_리뷰만_조회한다() {
`ALL`일 때 친구 리뷰와 친구가 아닌 리뷰 모두 조회하는 테스트도 있으면 좋을 것 같아요 🤓

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +            @RequestParam(name = "filter", defaultValue = "ALL") String filter,
여기서 바로 `Enum`으로 변환해주는 방법은 없을까요? 🤔

2023-10-11 07:12 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                    서버에서 허용하는 요청 파라미터 값 : FRIEND
`ALL`도 명시해주는게 좋은 것 같아요 !

2023-10-11 15:53 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewContentResponse.java
> +public record StoreReviewContentResponse(
헉 추가완료 !!

2023-10-11 15:56 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewResponse.java
> +        ReviewStoreResponse reviewStoreResponse = getReviewStoreResponse(
convert 좋네요 ㅎㅎ

2023-10-11 15:59 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +                    """
오잉 제 코드에서 안보이는데 ?!

2023-10-11 16:01 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomServiceTest.java
> +                10);
매의 눈 이시군요 ㅎㅎ

2023-10-11 16:08 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +            String filter,
필터링 키워드를 `VIEW`의 조건으로 볼 것이냐 `비즈니스 로직`으로 볼 것이냐의 차이인 것 같아요 !

저는 `ReviewFilter.FRIEND`의 name을 그대로 join 필터로 사용하고 있어서 필터링 키워드를 비즈니스 로직에 가깝다는 생각을 가지고 코드를 작성해서 서비스 계층에 두었습니다.

추가적으로 `BlameTarget` 과도 일관성을 맞추기 위해서 서비스 계층에 두었습니다 ㅎㅎ
또한 queryParam이 아니고 RequestBody로 전송된다고 하면 서비스 계층에서 꺼내어 enum 객체로 추출할 것 같기도 하네요 :)

2023-10-11 16:12 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
> +        void 친구_필터링이_있으면_팔로워_리뷰만_조회한다() {
좋아요 ~! 추가완료 ㅎㅎ

2023-10-11 16:20 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewResponse.java
> +        ReviewStoreResponse reviewStoreResponse,
생각해보니 굳이 전달해줄 필요가 없네요 !!

추가적으로 사용자 위치(경도, 위도)도 받을 필요가 없어서 함께 제거하겠습니다 ~

2023-10-11 16:27 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +            @RequestParam(name = "filter", defaultValue = "ALL") String filter,
컨트롤러는 filter 문자열을 정상적으로 받는지만 확인하고, Enum 객체의 변환 책임은 서비스에게 주고 싶었습니다 !

지난 코드리뷰 때 `BlameTarget`도 서비스 계층에서 변환하기로 했던 것 같아서 서비스 계층에서 변환하도록 했습니다 ~~

또다른 의견 있으시면 말씀해주세요 🙇🏻

2023-10-12 08:24 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
> +            });
테스트하고자 하는 부분이 1개라 `assertSoftly`를 사용하지 않아도 될 것 같아요 ㅎㅎ

2023-10-12 08:24 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
> +            String filter,
좋습니다 ㅎㅎ

2023-10-12 08:25 UTC, woo-chang approved these changes
반영하신 부분 확인했습니다 ㅎㅎ

매우매우 사소한 커멘트 남겼는데 호다닥 수정해주시면 감사합니다 🙇🏻‍♂️
approve 할께요 ~ 수고하셨습니다 !

2023-10-12 08:34 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
> +            });
반영 완룡

2023-10-12 08:49 UTC, merged