Feature/#200 리뷰 단건 조회 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #205
Opened 2023-12-21 07:40 UTC by Kim0914

## 🔥 연관 이슈

close: #200 

## 📝 작업 요약

리뷰 단건 조회 기능을 구현했습니다.

## 🔎 작업 상세 설명

리뷰 목록 조회하던 기능에서 동일한 응답으로 단건 조회를 응답하는 기능을 추가했습니다.

응답 객체인 ReviewResponse가 기존에 List<Review>를 이용해서 `of` 메서드로 반환하고 있어서, 단건 review를 이용한 `of` 메서드 오버로딩을 했습니다 !

기존 `ReviewResponse`와 응답 데이터가 동일하기 때문에 재사용하려고 오버로딩했는데 다른 의견 있으시면 말씀해주세요 ㅎㅎ

## 🌟 리뷰 요구 사항

오랜만에 기능을 작성해서 놓친 부분이 있을 수도 있을 것 같아요 😅
잘 부탁드립니당

> 10분

2023-12-22 08:46 UTC, woo-chang requested changes
수고하셨습니다 🙇🏻‍♂️
몇 가지 작은 코멘트 남겨두었으니 확인해주시면 감사합니다~

2023-12-22 08:46 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewRepository.java
> +    Optional<Review> findWithStoreAndMemberById(Long id);
`find~By` 사이에 추가적인 단어들이 들어가더라도 정상적으로 동작하는건가요?!

2023-12-22 08:46 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewRepositoryTest.java
> +        Review saveReview = reviewRepository.save(review);
`ReviewTestPersister`가 없어서 직접 생성해서 저장하신건가요?

있다면 사용하는 방향으로, 없다면 직접 구현해보는 것도 좋을 것 같다는 생각이 드는데 어떻게 생각하시나요 🤓

2023-12-22 08:46 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowRepository.java
> +    long countByFollowing(Member follower);
헉 기존에 팔로워 수를 조회하는 메서드가 없었나요? 🥲

오랜만이라서 가물가물하네요 .. 기존에는 어떻게 팔로워 수를 조회하는거죠 ㅎ.ㅎ

2023-12-22 08:46 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowRepository.java
> +    long countByFollowing(Member follower);
매개변수명을 `follower` -> `following`으로 수정하면 의미가 더욱 명확해질 것 같습니다!

2023-12-22 08:46 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +    public ResponseEntity<ReviewResponse> read(
`getReivew`와 같은 메서드명이 아닌 `read`라고 정하신 이유가 궁금해요 :)

2023-12-22 08:46 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +            summary = "단건 리뷰 주회",
주회는 누구인가요 ㅎㅎ

2023-12-23 14:18 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewRepositoryTest.java
> +        Review saveReview = reviewRepository.save(review);
앗 ㅋㅋㅋ 피움이랑 헷갈렸네요 ㅎㅎ
좋습니다 ~

2023-12-23 14:21 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewRepository.java
> +    Optional<Review> findWithStoreAndMemberById(Long id);
넵 ! 처음에는 ById 뒤에 의미를 들어내려고 작성했는데 이해를 못하더라구요 !
고래서 find~By 사이에 추가하고 테스트로 확인해보니 정상적으로 fetch join 되는 것 까지 확인했숨다 😆

2023-12-23 14:23 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowRepository.java
> +    long countByFollowing(Member follower);
ㅎㅎ 저도 이전에 어떻게 했었는지 쭉 찾아봤는데 기존에는 단건 조회 기능이 없이 `리뷰 목록 조회`가 있었고 목록 조회에 포함된 작성자들의 팔로워 수를 한번에 가져오는 쿼리로 조회하고 있었어요 (memberToFollowerDto..였나?) 🫢

그래서 추가했고 ! 매개변수는 수정할게용 ~

2023-12-23 14:26 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
> +    public ResponseEntity<ReviewResponse> read(
리뷰 cud를 보니 create, update, delete라서 순수한 단건조회니까 read라고 해야지 하고 했는데 다른 리뷰 조회(회원 리뷰, 북마크 리뷰, 팔로워 리뷰) 등은 `getReview...`로 되어 있네요!

조회는 통일성 있게 `getReview`로 맞출게요 ㅎㅎ

2023-12-23 14:27 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
> +            summary = "단건 리뷰 주회",
헉 🤫

2023-12-24 06:54 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewRepositoryTest.java
> +        Review saveReview = reviewRepository.save(review);
꾸준히 해야하는 이유가 여기서 나오네요 좋습니다~~

2023-12-24 06:54 UTC, woo-chang approved these changes
확인했습니다 ㅎㅎ

수고하셨어요 🙇🏻‍♂️👍

2023-12-24 14:07 UTC, merged