Feature/#211 리뷰 조회 친구 필터링에 사용자 리뷰를 포함시킨다.
Busan-Dinosaur/Foodbowl-Backend pull request #212
Opened 2024-02-14 14:35 UTC by Kim0914

## 🔥 연관 이슈

* close: #211 

## 📝 작업 요약

친구의 리뷰를 조회하는 경우 사용자가 작성한 리뷰도 확인할 수 있도록 했습니다 !

## 🔎 작업 상세 설명

기존에 리뷰 조회 시 innerJoin을 이용해 팔로워의 리뷰를 가져오던 로직을 다음과 같이 변경했습니다.

* 기존
```sql
return jpaQueryFactory.selectDistinct(review)
                .from(review)
                .innerJoin(follow).on(
                        review.member.id.eq(follow.following.id),
                        follow.follower.id.eq(followerId)
                )
                .where(
                        ltLastReviewId(lastReviewId),
                        containsPolygon(mapCoordinateBoundDto),
                        containsCategoryFilter(categoryType)
                )
                .orderBy(review.id.desc())
                .limit(pageSize)
                .fetch();
```
* 현재
```sql
return jpaQueryFactory.selectDistinct(review)
                .from(review)
                .leftJoin(follow).on(
                        review.member.id.eq(follow.following.id)
                )
                .where(
                        review.member.id.eq(followerId)
                                .or(memberFollowingEq(followerId)),
                        ltLastReviewId(lastReviewId),
                        containsPolygon(mapCoordinateBoundDto),
                        containsCategoryFilter(categoryType)
                )
                .orderBy(review.id.desc())
                .limit(pageSize)
                .fetch();

private BooleanExpression memberFollowingEq(Long followerId) {
        return follow.follower.id.eq(followerId)
                .and(review.member.id.eq(follow.following.id));
}
```
우선 join의 on절에서 `review.member.id.eq(follow.following.id)` 판단하는 로직을 where 절로 옮겼습니다.
on 절에서 판단하는 경우 select 조건에 사용자의 리뷰를 포함시킬 수 없었어요.
leftJoin을 사용한 이유는 팔로워 정보가 아예 없는 경우 사용자가 작성한 리뷰를 가져오기 위함입니다.
그래서 우선적으로 모든 리뷰와 followerId에 해당하는 팔로우 정보를 가져온 후 `사용자 리뷰 + 팔로워 리뷰`를 where 절에서 필터링 했습니다 🌱

요구사항이 추가됨에 따라 여러 상황이 발생할 수 있어서(**기본 조회인 경우**, **팔로워가 있지만 팔로워들의 리뷰가 없는 경우**, **팔로워가 아예 없는 경우**) 관련 테스트를 추가했는데 함께 봐주시면 감사하겠습니다 :D
 
## 🌟 리뷰 요구 사항
쿼리문 최적화 해보려고 이것 저것 시도하다가 여기 까지 왔는데요..ㅎㅎ
자꾸 쓰고 지우고 하다보니 어지러워진 것 같기도 하네요...
쿼리 개선할 부분(실행 계획은 확인했고 큰 이상 없었어요 !)은 없는지, 테스트 추가할 부분은 없는지 봐주시면 짱짱입니당

추가) memberFollowingEq 메서드 명이 참 아쉬운데 괜찮은 거 없을까요?! 🥺
> 20분

2024-02-16 07:23 UTC, woo-chang requested changes
잘 구현해주셔서 크게 수정사항은 없다고 생각됩니다!

다만 새롭게 추가된 요구사항이 리뷰에만 적용된 것으로 확인되는데, 가게 조회에도 내가 작성한 리뷰의 가게가 조회되도록 수정이 필요할 것 같습니다 :)

2024-02-16 07:23 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
> +        void 사용자의_팔로앙이_없는_경우에도_사용자의_리뷰는_조회된다() {
[오타] 사용자의 팔로앙 <<

2024-02-16 07:23 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
> +        void 친구_필터링이_있을_때_팔로워가_없어도_사용자_리뷰는_조회된다() {
꼼꼼한 테스트 너무 좋네요 👍

2024-02-17 03:27 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
> +        void 사용자의_팔로앙이_없는_경우에도_사용자의_리뷰는_조회된다() {
헉 수정완료 !

2024-02-17 03:57 UTC, Kim0914 commented
놓치고 넘어갈 뻔 했는디 추가했슴니다 ㅎㅎ 감사해욥

2024-02-17 06:35 UTC, woo-chang reviewed
가게 목록 조회도 빠르게 구현해주셨네요 ㅎㅎ

한 가지 궁금한 부분이 있어 리뷰로 남겼습니다.
이 부분만 해결되면 머지해도 될 것 같아요!

2024-02-17 06:35 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepository.java
> +                .and(review.member.id.eq(follow.following.id));
`leftJoin` 조건을 통해 같은 것들만 가져왔는데 리뷰 작성자와 다른 경우가 발생하나요?
해당 조건을 작성한 이유에 대해 알려주시면 감사합니다! 🤓

2024-02-17 06:35 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
> +                .and(review.member.id.eq(follow.following.id));
[비슷한 리뷰] 여기도 가게 목록 조회와 마찬가지로 동일한 궁금점입니다 !

2024-02-17 06:49 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepository.java
> +                .and(review.member.id.eq(follow.following.id));
ㅎㅎ 지금 다시 보니 중복 조건을 작성했네요? 🤔
이미 leftJoin에서 on 조건으로 명시했어서 where문에는 없어도 문제없네요 !
테스트도 완료했습니당. 굿굿

2024-02-17 06:55 UTC, woo-chang approved these changes
마지막까지 꼼꼼히 수정 수고하셨습니다 😍

2024-02-17 06:56 UTC, merged