Feature/#3 Post 테이블을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #26
Opened 2023-04-14 05:47 UTC by Kim0914

## 🔥 연관 이슈

close: #3

## 📝 작업 요약

- 카테고리 엔티티 생성
- 게시글 엔티티 생성
- 게시글 - 카테고리 매핑 엔티티 생성

## 🔎 작업 상세 설명

- @ManyToOne Lazy 로딩 설정
- Post의 Thumbnail cascade 설정
- category가 unique 인덱스 기준으로 오름차순으로 DB에 정렬되어, ID 기준으로 정렬해서 가져오는 메서드를 추가했습니다.

## 🌟 리뷰 요구 사항

> 10분

2023-04-14 06:39 UTC, woo-chang requested changes
꼼꼼히 작성하려고 했던 노력이 보이는 코드입니다! 수고하셨습니다 그레이 🔥

몇 가지 고민해볼 포인트와 궁금한 점에 대해 리뷰 남겼는데 확인해주시면 감사합니다 :)

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Category.java
> +    private Category(Long id, CategoryType categoryType) {
`@Builder`를 빼는 꼼꼼함 좋은데요

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Category.java
> +    @Column(name = "name", length = 45)
`unique` 설정도 해볼 수 있지 않을까요?

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/repository/CategoryRepository.java
> +    List<Category> findAll();
네이티브 쿼리를 통해 직접 쿼리를 작성하셨군요 👍

<img width="358" alt="Screenshot 2023-04-14 at 3 00 55 PM" src="https://user-images.githubusercontent.com/78212016/231954390-ad64d531-c64e-4643-ba8d-1ef94b6a4d44.png">

쿼리를 작성하지 않고 `JpaRepository`를 사용하는 것과 같이 메서드를 정의하면 알맞은 구현체를 자동으로 넣어줍니다! 해당 기능을 활용해보셔도 좋을 것 같아요 :)

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY)
일대일 관계는 양쪽이 서로 하나의 관계만 가질 때 사용한다고 합니다.
예를 들어 회원은 단 하나의 사물함만 사용하고, 사물함도 하나의 회원에 의해서만 사용되는 경우가 있습니다.

`Member`와 `Post`의 관계에서 본다면,
멤버는 여러 게시글을 작성할 수 있고, 게시글은 하나의 회원에 의해서만 작성됩니다.

이런 경우 어떤 연관관계를 사용해야할까요? 🤔

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY)
여기도 마찬가지로 가게는 여러 게시글에 참조될 수 있고, 게시글은 하나의 가게에 대한 정보만 작성합니다.

위와 동일하게 고민해보셔도 좋을 것 같습니다!

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @Lob
`@Lob` 어노테이션은 어떤 역할을 하는지 설명해주시면 감사합니다 :)

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    private LocalDateTime updatedAt;
`@CreatedDate`와 마찬가지로 업데이트 시 자동으로 시간을 업데이트 시켜주는 어노테이션에 대해 찾아보셔도 좋을 것 같아요!

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +        this.updatedAt = LocalDateTime.now();
업데이트 시 시간을 자동으로 설정하게 되는 어노테이션을 사용하게 되면 빌더에서 해당 코드가 제거되어도 좋겠네요 :)

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/PostCategory.java
> +    private Long id;
일관성 있게 `@Column`을 작성해주는건 어떨까요?

2023-04-14 06:39 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
필요한 `cascade`만 사용하지 않고 `ALL`을 사용한 이유가 궁금합니다!

2023-04-14 07:47 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Category.java
> +    @Column(name = "name", length = 45)
넵 ~~

2023-04-14 07:57 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Category.java
> +    private Category(Long id, CategoryType categoryType) {
궁금한게 여기서 id를 넣어주는건 어플리케이션에서 `CategoryType`의 id를 `Category`와 동일하게하는거 같은데 id에 `@GeneratedValue` 필요한건가요??

어플리케이션에서 `Category`를 쓰는 상황이 `Post`를 생성할 때일거 같은데
`Post`를 생성하는 시점에 `Category`의 id가 이미 생성되있는거 아닌가요???

2023-04-14 08:59 UTC, This2sho reviewed
생각을 정말 많이하신거 같아요 고생하셨습니다 그레이 🙀

저도 몇 가지 고민해볼 포인트와 궁금한 점에 대해 리뷰 남겼는데 확인해주시면 감사합니다 :)

2023-04-14 08:59 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY)
연관관계 설정이 제일 어려운거 같습니다 ㅠㅠ

2023-04-14 08:59 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/PostCategory.java
> +    private Long id;
동의합니당 👏

2023-04-14 08:59 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @Lob
저도 궁금합니다~!

2023-04-14 08:59 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
저도 cascade를 사용할 때 ALL만 사용했는데 궁금하네요!
그리고 Thumbnail 에 `orphanRemoval` 를 설정할지도 같이 말해보면 좋을거 같아요

2023-04-14 09:23 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY)
`@ManyToOne`과 `@OneToOne`을 단방향 관계에서 바라보니 헷갈리는 점이 많네요 ㅜ
말씀해주신대로 `@ManyToOne`이 맞습니다 !
반영하겠습니당

2023-04-14 11:35 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @Lob
`@Lob`은 varchar로 표현할 수 있는 최대(255)이상의 길이를 저장하고 싶은 경우 사용합니다. (**L**arge **Ob**ject)

현재 Post 테이블의 컬럼 타입이 LONGTEXT로 선언되어 있어서 @Lob을 사용했는데, 
LONGTEXT 타입은 최대 4GB의 크기까지 저장할 수 있어서 성능에 큰 영향을 끼치 때문에 신중하게 고려해서 사용해야 한다고 합니다 !

varchar 타입으로 선언시 최대 21,844자까지 사용가능하고 varchar 타입이 부족하다고 판단되면 TEXT 타입으로 선언해도 충분할 것 같습니다 :ㅇ

두 분 의견 주시면 감사하겠습니다 😄

2023-04-14 11:40 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +        this.updatedAt = LocalDateTime.now();
반영했습니당

2023-04-14 11:49 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Category.java
> +    private Category(Long id, CategoryType categoryType) {
생각하지 못한 부분인데 캐치해주셔서 감사합니다 !
카테고리 엔티티 자체를 생성하지 않기 때문에 PK 설정으로 굳이 `@GeneratedValue` 사용할 필요가 없다고 생각합니다.
또한 임의로 ID를 직접 만들어서 매핑하고 있기 때문에 더욱 필요 없을 것 같다고 생각합니다 ㅎㅎ

현재 Role 클래스도 동일하게 작성되어 있는데 변경이 필요한 경우 함께 변경하면 좋을 것 같습니다 ~

2023-04-14 12:13 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
Thumbnail 객체는 Post 객체의 생명주기와 일치`(PERSIST, REMOVE, MERGE 등등.. )`한다고 생각해서 ALL을 사용했습니다.
두 분은 어떻게 사용하시나요 ? ㅎㅎ 궁금합니다 ~

---
`orphanRemoval`은 부모 - 자식 관계에서 **부모 엔티티에서 자식 엔티티의 참조가 사라졌을 때 DB에 delete 쿼리가 자동으로 날라가도록** 합니다. 예를 들면 Team과 Member의 관계에서 다음과 같은 경우에요 !
```java
// 연관관계 추가
team.addMember(member1);
team.addMember(member2);

// 해제
team.deleteMember(member1);
```
Member가 Team 이외의 다른 곳에서 사용되지 않는다면 DB에서도 삭제되어야겠죠?! (참조 관계가 해제되면 자동으로 delete 쿼리가 발생합니다)
만약 DB에 삭제되지 않고 존재한다면 고아 객체가 되어버립니다 !

현재 Post - Thumbnail OneToOne 관계에서는 `post.getThumbnail = null;`이 실행되어야 orphanRemoval이 작동할 것 같다고 생각되는데, 해당 코드는 실행되지 않을 것(정상적인 로직이 아님)이라고 생각해서 추가하지는 않았습니다 !
**제가 놓치고 있는 부분이 있을 수도 있어서 함께 생각해주시죠 😀**

자식 엔티티를 명시적으로 삭제하거나, 자식 엔티티의 생명주기 동작을 부모 엔티티와 별도로 제어하고 싶다면 추가해도 좋을 것 같습니다 !!

2023-04-15 05:24 UTC, woo-chang reviewed
잘 작성해주신 것 같아요 👍

수정 시간 어노테이션 확인만 마지막으로 부탁드릴께요 :)

2023-04-15 05:24 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @Column(name = "content", length = 2000)
`@Lob`을 제거하고 길이를 명시적으로 수정해주셨네요! 혹시 게시글 내용은 몇 자 정도가 최대로 적당할까요? 🤔

gpt에 검색했을 경우 보통 4000자로 지정한다고 하는데 4000자도 적어보이는 것 같고 ... 적정선을 모르겠네요

2023-04-15 05:24 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @LastModifiedDate
잘 찾아서 적용해주셨네요 👍

아마 해당 어노테이션을 사용하는 Entity는 `@EntityListeners(AuditingEntityListener.class)` 어노테이션을 붙여주지 않으면 동작하지 않는 것으로 알고 있는데 테스트 해보는건 어떨까요?

2023-04-15 05:24 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Category.java
> -    @GeneratedValue(strategy = GenerationType.IDENTITY)
혹시 잘못해서 저장되는 로직이 수행되면 어떻게 ID가 부여되나요? 🤔

2023-04-15 05:30 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
말씀해주신대로 게시글과 썸네일의 생명주기는 일치한다고 생각합니다 좋은 의견 감사합니다 👍

---

`orphanRemoval`를 설명해주신 것과 같이 게시글에 썸네일이 없어질 경우가 없을 것 같아 적용하지 않아도 된다는 의견에 설득당했습니다! 각 기능을 잘 이해하고 사용하시는 것 같아 너무 많이 배워갑니다 🔥

2023-04-15 05:52 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Category.java
> -    @GeneratedValue(strategy = GenerationType.IDENTITY)
저는 `Category` 엔티티의 설계 의도를 애플리케이션에서 생성하지 않고, 추가되는 Category가 있으면 개발자가 직접 추가해주는 것이라고 이해했습니다 ! 
왜냐하면 현재 **Category는 애플리케이션에서는 CRUD를 하지 않고, DB 초기화할 때 insert**만 해주기 때문입니다.
그래서 애플리케이션 내부에서 Category가 CRUD 동작이 발생한다면, 의도되지 않은 동작이라고 생각하는데 어떻게 처리하는 것이 좋을까용?🧐

2023-04-15 05:54 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @LastModifiedDate
현재 BaseEntity를 상속하고 있고 BaseEntity에 해당 에노테이션이 설정되어 있습니다 ㅎㅎ
테스트 해본 결과 정상적으로 작동함을 확인했습니다 !

2023-04-15 06:41 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @Lob
제 생각은 `@Column(columnDefinition = "TEXT")` 사용해서 TEXT 타입으로 사용해도 충분할거 같습니다!!

2023-04-15 06:56 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
그렇군요. 몰랐던 부분인데 알아갑니다 👍

2023-04-16 14:21 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/post/entity/Post.java
> +    @Column(name = "content", length = 2000)
4000자 정도면 괜찮지 않을까라는 생각도 드는 것 같습니다 ㅎㅎ
보통 한 문단에 300 ~ 400자 정도 작성된다고 하는데 SNS의 성격을 띄는 애플리케이션 특징 상 4000자 정도면 괜찮지 않을까 생각이 듭니다 !

2023-04-19 04:56 UTC, woo-chang approved these changes
많이 배워갈 수 있었습니다 수고하셨습니다 👍👍

2023-04-19 05:01 UTC, This2sho commented
변경 사항 확인했습니다. 고생하셨어요👍👏

2023-04-19 05:02 UTC, This2sho approved these changes
변경 사항 확인했습니다. 고생하셨어요👍👏

2023-04-19 06:08 UTC, merged