Feature/#12 사진 저장 기능을 구현한다.
Busan-Dinosaur/Foodbowl-Backend pull request #55
Opened 2023-05-03 18:09 UTC by This2sho

## 🔥 연관 이슈

close: #11 , #12 

## 📝 작업 요약

사진 저장 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 하나의 이미지, 여러 이미지를 저장후 생성된 이미지의 경로(DirectoryName + UUID + 확장자)를 반환하게 구현하였습니다.
- 이미지 타입을 나눈 이유는 저장되는 경로, 리사이징이 필요할 경우 사이즈를 담기위해 사용하였습니다.

## 🌟 리뷰 요구 사항

> 15분

2023-05-04 04:25 UTC, woo-chang requested changes
수고하셨습니다 👍

라이브러리는 오래된 버전이라 사용하지 않는 것이 좋을 것 같아 직접 구현해보고 비교해보는 것도 좋을 것 같습니다 🙇🏻‍♂️ 구현 후 올려주시면 다시 리뷰하도록 하겠습니다!

2023-05-04 04:25 UTC, woo-chang commented on build.gradle
> +    implementation 'org.imgscalr:imgscalr-lib:4.2'
2012년에 나온 라이브러리인데 사용해도 괜찮을까요?

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageType.java
> +    PHOTO("/photo/", false, -1, -1),
```suggestion
public enum ImageType {

    PHOTO("/photo/", false, -1, -1);
```
첫줄은 개행해주는 것이 어떨까요?

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return storedImagesPaths;
`stream`으로 처리해보는건 어떨까요? 🤔

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +            throw new FileNotFoundException("파일이 존재하지 않습니다.");
예외를 처리하는 핸들러가 필요할 것 같습니다!

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        String storeFileName = createStoreFileName(originalFilename);
```suggestion
        String storeFilename = createStoreFilename(originalFilename);
```
`file`의 메서드처럼 `createStoreFilename`으로 가는건 어떠신가요?

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        String ext = extractExt(originalFilename);
```suggestion
        String extention = extractExtention(originalFilename);
```
`ext`를 처음 봤을 때는 의미가 와닿지 않았습니다 🥲 명확하게 드러내는건 어떠신가요?

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        String ext = extractExt(originalFilename);
파일의 확장자가 필요한 이유가 궁금합니다!

`jpeg`, `png` 중 하나를 정해두고 들어오는 모든 이미지는 `jpeg`, `png` 중 하나의 형식으로 저장되도록 하면 확장자를 알지 않아도 괜찮을 것 같다는 생각이 듭니다.

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return originalFilename.substring(dotIndex + 1);
`.`이나 `1`과 같은 값은 상수로 관리해보는건 어떨까요? 의미를 드러낼 수 있는 변수명까지 사용한다면 더 가독성 좋은 코드가 될 것 같습니다!

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +            throw new FileNotFoundException("파일이 존재하지 않습니다.");
`MultipartFile`이 이미지가 아닌 경우에 대한 예외 처리도 있으면 좋아보입니다 👍

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +            image = resizeImage(image, imageType.getWidth(), imageType.getHeight());
```suggestion
            BufferedImage resizeImage = resizeImage(image, imageType.getWidth(), imageType.getHeight());
```
새 변수에 할당해주면 좋을 것 같습니다!

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    }
진짜 너무 편리한 기능이네요 👍👍

근데 너무 오래된 라이브러리라 사용에 있어 고민이 되는 부분이긴 합니다..

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    private String fileDir;
추가적인 파일 경로를 주신 이유가 궁금합니다!

2023-05-04 04:25 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    public void deleteImageFiles(List<String> paths) {
`imagePaths`로 변수 이름을 명확하게 나타내는건 어떨까요?

2023-05-04 04:25 UTC, woo-chang commented on src/main/resources/config/application.yml
> +  dir: foodbowl-res
private `application.yml`로 옮겨도 좋을 것 같습니다!

2023-05-04 13:57 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        for (String path : paths) {
위에서 stream 적용한다면 여기도 적용할 수 있겠군요 !

2023-05-04 13:59 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/ImageUtilsTest.java
> +        trash.add(path);
trash.add, trash.addAll이 모든 테스트에서 사용되고 있는데
어떤 용도로 사용되고 있는지 궁금합니다 !

2023-05-04 13:59 UTC, Kim0914 reviewed
고생하셨습니다 호이 ~~

우창씨가 거의 다 리뷰 남겨줘서 저는 궁금한 점만 남겼습니다 !

2023-05-08 10:45 UTC, This2sho commented on build.gradle
> +    implementation 'org.imgscalr:imgscalr-lib:4.2'
이슈를 보니 버그가 좀 있긴하네요..!!

2023-05-08 10:47 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageType.java
> +    PHOTO("/photo/", false, -1, -1),
좋습니다!

2023-05-08 10:53 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return storedImagesPaths;
```java
return files.stream()
            .map(file -> {
                try {
                    return storeImageFile(imageType, file);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }).collect(Collectors.toList());
```

stream을 사용하면 예외처리를 람다식 안에서 해줘야 하네요 🥲
어느 부분이 더 나으신가요??!

2023-05-08 11:03 UTC, This2sho commented on src/main/resources/config/application.yml
> +  dir: foodbowl-res
테스트 터질거 같아서 public에 올렸는데 수정하겠습니다!

2023-05-12 10:54 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +            throw new FileNotFoundException("파일이 존재하지 않습니다.");
`MultipartFile`이 아닌경우 인자로 들어올 수 있나요??

2023-05-12 10:55 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        String storeFileName = createStoreFileName(originalFilename);
`FileName`인줄 알았는데 `Filename` 이네용!!

2023-05-12 10:57 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +            image = resizeImage(image, imageType.getWidth(), imageType.getHeight());
좋습니다!

2023-05-12 10:58 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    }
그러게요..! 서버 단에서 리사이징을 잘안하는거 같아서
우선, 다음 커밋때 라이브러리 빼고 구현해보겠습니다!

2023-05-12 10:59 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    private String fileDir;
파일 경로는 저장되는 서버(환경)에 따라 달라질거 같아서 설정 파일에서 관리하고 싶었습니다!

2023-05-12 11:01 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    public void deleteImageFiles(List<String> paths) {
좋습니다!

2023-05-12 11:11 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        for (String path : paths) {
stream의 forEach() 나 peek() 같은 경우 주로 print 용도로 알고 있어서
대신 Iterable의 foreEach()를 적용해보겠습니다!

2023-05-12 11:13 UTC, This2sho commented on src/test/java/org/dinosaur/foodbowl/domain/photo/ImageUtilsTest.java
> +        trash.add(path);
사진을 직접 저장하는 로직이라 실제 저장되고 있습니다.
test가 끝난 후 생성된 파일을 지워주기 위해 이름을 담아두는 용도로 사용했습니다.

2023-05-12 18:02 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return storedImagesPaths;
stream을 사용하지 않는 것이 좋을듯 합니다 !

2023-05-12 18:05 UTC, Kim0914 approved these changes
고생많으셨습니다 ~
크게 수정할 요소는 없는 것 같아 approve 하겠습니다 !
짧게 남긴 코멘트만 확인 부탁드려요 ㅎㅎ

2023-05-12 18:05 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return files.stream()
stream 내부의 map에서 람다식을 통해 예외가 발생하는 부분은 stream의 목적성과 어긋나는 것 같습니다 !!
번거로우시지만 다시 forEach로 가는건 어떨까용?

2023-05-12 18:05 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/photo/PhotoUtilsTest.java
> +    private final List<String> trash = new LinkedList<>();
줄 바꿈 !

2023-05-13 10:20 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return files.stream()
좋습니다!

2023-05-13 12:00 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return storedImagesPaths;
저도 그레이 의견에 동의합니다!

2023-05-13 12:02 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +            throw new FileNotFoundException("파일이 존재하지 않습니다.");
이미지가 아닌 비디오나 문서 같은 데이터도 `MultipartFile`로 들어올 수 있는 것으로 알고 있습니다!

2023-05-13 12:53 UTC, woo-chang reviewed
추상 클래스를 활용하여 중복 코드를 제거하였고 전체적으로 깔끔해진 코드를 잘 작성해주신 것 같습니다 👍

세세한 부분에서 수정이 필요한 부분이 있어 한번 더 코멘트 남겼습니다! 확인 부탁드릴께요 🙇🏻‍♂️

2023-05-13 12:53 UTC, woo-chang commented on build.gradle
> +    implementation 'org.imgscalr:imgscalr-lib:4.2'
사용하지 않는 의존성은 제거하면 좋을 것 같아요 :)

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    protected String fileDir = "foodbowl-res";
`res`는 무슨 의미인지 알 수 있을까요?

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        String ext = extractExt(originalFilename);
위의 리뷰가 처리되지 않은 것 같아서 답변 부탁드립니다!

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return originalFilename.substring(dotIndex + 1);
여기도 답변 부탁드릴께요!

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        }
다른 곳은 null 검증을 안하는데 여기만 되어있는 것 같습니다. 여기만 진행하는 이유가 궁금합니다!

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/PhotoUtils.java
> +        return path;
`fullPath`가 반환되어야 하지 않나요?

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ThumbnailUtils.java
> +        }
높이만 `450`보다 큰 경우는 어떻게 처리되는지 궁금합니다!

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    protected String fileDir = "foodbowl-res";
`@Value`를 사용하는만큼 디폴트 값은 지정하지 않는게 어떨까요?

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    public List<String> storeImageFiles(List<MultipartFile> files) throws IOException {
해당 클래스에서 발생하는 `IOException`은 `FoodbowlException`으로 수정해서 넘겨서 `ContollerAdvice`에서 처리할 수 있도록 해주는건 어떨까요?

2023-05-13 12:53 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/PhotoUtils.java
> +        String originalFilename = file.getOriginalFilename();
처음 들어온 파일명의 길이가 너무 긴 경우도 예외 처리 해주면 좋을 것 같아요 :)

2023-05-13 12:53 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/photo/ThumbnailUtilsTest.java
> +    }
저장되어 있는 사진의 크기가 의도한대로 저장되어 있는지도 확인해보는건 어떨까요?

2023-05-13 13:24 UTC, This2sho commented on build.gradle
> +    implementation 'org.imgscalr:imgscalr-lib:4.2'
앗.. 사용하는 부분만 제거하고
의존성을 까먹었네요! 감사합니다 👍

2023-05-13 13:25 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    protected String fileDir = "foodbowl-res";
> `res`는 무슨 의미인지 알 수 있을까요?
`res`는 `resources` 의미로 사용하였습니다!

2023-05-13 13:28 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    protected String fileDir = "foodbowl-res";
> `@Value`를 사용하는만큼 디폴트 값은 지정하지 않는게 어떨까요?

Spring 을 사용하지 않고 테스트하고 싶어서 디폴트 값을 지정했는데
혹시 추천하시는 다른 방법이 있을까요

2023-05-15 12:08 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        String ext = extractExt(originalFilename);
> 파일의 확장자가 필요한 이유가 궁금합니다!
> 
> `jpeg`, `png` 중 하나를 정해두고 들어오는 모든 이미지는 `jpeg`, `png` 중 하나의 형식으로 저장되도록 하면 확장자를 알지 않아도 괜찮을 것 같다는 생각이 듭니다.

들어오는 이미지 파일들의 확장자를 검사하려면 확장자를 알아야하지 않을까요..?!

2023-05-15 18:32 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        return originalFilename.substring(dotIndex + 1);
리뷰를 놓쳤네요 🥲 
좋습니다! 👍

2023-05-15 18:32 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    public List<String> storeImageFiles(List<MultipartFile> files) throws IOException {
좋습니다 👍

2023-05-15 18:32 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/PhotoUtils.java
> +        String originalFilename = file.getOriginalFilename();
녬! 근데 어차피 UUID로 변경되는데 들어오는 파일명의 길이가 중요한가요??

2023-05-15 18:32 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/PhotoUtils.java
> +        return path;
`fullPath`는 `fileDir(실제 저장 경로)`  + `이미지 타입(중간 디렉토리)` + `UUID` + `확장자`로 이루어 져있는데 `fileDir`은 변경 가능성이 있을거 같아서 `fileDir`을 제외한 path만 반환하도록 했습니다.

2023-05-15 18:45 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ThumbnailUtils.java
> +        }
세로만 엄청 긴 사진이 올수도 있겠군요! 👍

2023-05-15 19:19 UTC, This2sho commented on src/test/java/org/dinosaur/foodbowl/domain/photo/ThumbnailUtilsTest.java
> +    }
좋습니다!

2023-05-15 19:20 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +        }
필요없을 거 같습니다! 🥲

2023-05-16 04:56 UTC, woo-chang reviewed
수고하셨습니다 🙇🏻‍♂️ 끝이 보이는군요

마지막 리뷰만 수정되면 approve 하겠습니다 ~~

2023-05-16 04:56 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    protected String fileDir = "foodbowl-res";
```suggestion
public ImageUtils(@Value("${file.dir}") String fileDir) {
    this.fileDir = fileDir;
}
```
요렇게하면 생성자로도 값을 넣어줄 수 있습니다!

2023-05-16 04:56 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    protected String fileDir = "foodbowl-res";
`bucket/photo`, `bucket/thumbanil`
```
ㄴ src
ㄴ bucket
    ㄴ photo
    ㄴ thumbnail
```

2023-05-16 04:56 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    }
생각해보니 `UUID`로 할거라 이름 길이는 검증할 필요가 없을 것 같습니다 .. ! 🥲

2023-05-16 04:56 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    public static final int MAX_FILE_NAME = 15;
띄워쓰기 한 칸 해줘도 좋을 것 같아요 :)

2023-05-16 04:56 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/exception/ErrorStatus.java
> +    //ImageUtils code: 5xxx
```suggestion
    //Image code: 5xxx
```

2023-05-16 04:56 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/exception/ErrorStatus.java
> +    IMAGE_INVALID_NAME_LENGTH(HttpStatus.BAD_REQUEST, String.format("파일이름이 %s자를 초과합니다.", ImageUtils.MAX_FILE_NAME),
삭제해도 좋을 것 같아요 :)

2023-05-16 11:35 UTC, This2sho commented on src/main/java/org/dinosaur/foodbowl/domain/photo/ImageUtils.java
> +    public static final int MAX_FILE_NAME = 15;
이제 필요없어져서 삭제하겠습니다! 😉

2023-05-16 14:24 UTC, woo-chang approved these changes
정말 수고하셨습니다 🙇🏻‍♂️

많은 리뷰로 저도 배워갈 수 있었습니다 👍

2023-05-16 14:24 UTC, woo-chang approved these changes
정말 수고하셨습니다 🙇🏻‍♂️

많은 리뷰로 저도 배워갈 수 있었습니다 👍

2023-05-16 14:24 UTC, merged