Feature/#91 회원 조회 기능 변경
Busan-Dinosaur/Foodbowl-Backend pull request #93
Opened 2023-07-31 16:10 UTC by Kim0914

## 🔥 연관 이슈

close: #91 

## 📝 작업 요약

- ArgumentResolver에서 Member를 반환하도록 변경했습니다.

## 🔎 작업 상세 설명

- Member 객체의 introduce 필드가 Member 테이블에는 introduction으로 설정되어 있어서 `introduction`으로 통일했습니다.
- ArgumentResolver의 정상 동작을 확인하기 위해 HealthCheckController를 테스트했습니다.
- 테스트에서 Fixture와 Support의 사용 여부가 확실하지 않아, 우선적으로 메서드 내부에서 객체를 생성했습니다.
- 각 계층별 테스트를 위한 상위 객체를 생성했습니다. 네이밍을 패키지 구조와 동일하게 가져가도록 했는데 확인 부탁해요 !
- 커밋 메세지에 이슈 번호를 잘못 남겼습니다 😂 익스큐즈 부탁해요 ㅎㅎ

## 🌟 리뷰 요구 사항

> 10분

2023-08-01 05:00 UTC, woo-chang requested changes
전체적으로 깔끔하게 잘 작성해주셨네요 :)

2023-08-01 05:00 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/member/domain/Member.java
> +    private String introduction;
꼼꼼하게 잘 바꿔주셨네요 감사합니다 🙇🏻‍♂️ 👍🏻

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/PersistenceTest.java
> +))
`@Import`를 사용하는 방법도 있는데 해당 방법으로 `JpaConfig`를 포함시킨 이유가 궁금합니다!

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/PersistenceTest.java
> +public class PersistenceTest {
어노테이션을 만드는 방법도 존재하는데 클래스로 만들어서 상속을 선택한 이유가 궁금합니다! 😄

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +@SuppressWarnings("NonAsciiCharacters")
<img width="985" alt="스크린샷 2023-08-01 오후 1 47 39" src="https://github.com/Busan-Dinosaur/Foodbowl-Backend/assets/78212016/ad92cbe2-6864-407e-b71e-9a3c4d675870">

해당 어노테이션은 전역적으로 설정해줄 수 있는 방법이 없어 각 클래스마다 붙여줘야하는 번거로움이 있더라구요 🥲

코드를 실행하는데 있어 큰 문제가 발생할 여지가 있는 부분도 아니기에 인텔리제이 설정으로 `warning`이 안뜨도록 하는 방법도 있던데 해당 어노테이션을 제거하고 인텔리제이 설정을 바꿔보는 방법은 어떨까요?

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +    void 서버_상태가_정상이면_200_반환() throws Exception {
테스트명은 한글로 작성하는걸로 할까요?! 한글로 작성하는게 직관적인 것 같기는 합니다 😀

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
해당 어노테이션은 어노테이션이나 상속받는 클래스에 올려 전역적으로 설정할 수 있는데 위로 올리는건 어떨까요?!

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +    private MockMvc mockMvc;
기본적으로 제공하는 `MockMvc`를 사용하면 SpringSecurity같은 필터나 ArgumentResolver, ExceptionHandler를 가져오지못해 해당 동작들을 확인할 수 없는 것으로 알고 있는데(잘못 알고 있을수도 있음), 제대로 동작하나요?

ArgumentResolver의 값을 제대로 가져왔는지 확인하는 테스트가 없어서 ArgumentResolver가 동작하지 않았을 수도 있겠다라는 생각이 들었습니다 🤔

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +    private MockMvc mockMvc;
추가적으적 `RestAssuredMockMvc`도 존재하던데 어떤 것을 사용하면 좋을지도 얘기해보면 좋을 것 같아요 :)

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +                .andDo(print());
`RestDocs` 안쓰니까 테스트가 편안 ☺️

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +                .willReturn(Optional.of(member));
`line break` 때문에 개행하신건지 컨벤션적으로 개행하신건지 궁금해요~

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +    void 사용자_인증이_정상이면_200_반환() throws Exception {
멤버값이 정상적으로 반환되었는지에 대한 테스트가 있으면 좋을 것 같아요 :)

2023-08-01 05:00 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepositoryTest.java
> +                .build();
기존의 `TestHelper` 괜찮았나요? 괜찮았다면 사용하는게 좋을 것 같네요 ㅎㅎ

2023-08-01 05:38 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepositoryTest.java
> +                .build();
`EntityTestPersister` !!

2023-08-02 00:47 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/PersistenceTest.java
> +))
JpaConfig와 연관된 빈들을 한번에 가져오려고 사용했는데, 현재 JpaConfig와 관련된(상속하는) 빈들이 없기 때문에 `@Import`로 충분할 것 같네요 ㅎㅎ

2023-08-02 00:48 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/PersistenceTest.java
> +public class PersistenceTest {
공통된 부분을 필드로 가질 수 있고, 공통 메서드도 정의할 수 있기 때문에 상속을 선택했습니다 ~

2023-08-02 00:50 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +@SuppressWarnings("NonAsciiCharacters")
인텔리제이에서 설정으로 해결하면 다른 사람이 저희 코드를 pull 받아서 사용할 때 해당 설정을 하지 않았다면 warning이 발생하겠죠?!
그래서 어노테이션을 붙여주는 방법이 더 나은 것 같습니다 !

2023-08-02 00:50 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +    private MockMvc mockMvc;
동작하는 부분 함께 확인했습니다 ~

2023-08-02 00:50 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +                .willReturn(Optional.of(member));
넵 ㅎㅎ

2023-08-02 00:50 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
> +    void 사용자_인증이_정상이면_200_반환() throws Exception {
반영 완 !

2023-08-02 00:54 UTC, Kim0914 commented
수정사항 반영했습니다 ~~

코드를 다시 보는데 `HealthCheckService`가 왜 필요한지 의문이 들더라구요 ㅎㅎ
그냥 `good`을 전달만 하고 있는 것 같은데 서비스 계층을 둔 이유가 궁금하네요 !

2023-08-02 05:37 UTC, closed without merging

2023-08-02 05:52 UTC, Kim0914 commented
브랜치 명 수정으로 인한 [PR 재오픈](https://github.com/Busan-Dinosaur/Foodbowl-Backend/pull/94)