Feature/#87 애플 로그인 기능을 구현한다
Busan-Dinosaur/Foodbowl-Backend pull request #95
Opened 2023-08-03 13:48 UTC by woo-chang

## 🔥 연관 이슈

close: #87

## 📝 작업 요약

🍏 애플 로그인 기능을 구현하였습니다 🍎

## 🔎 작업 상세 설명

- 애플 로그인 진행 시 이미 회원가입한 회원이라면 회원 정보를 바탕으로 토큰을 생성 후 반환합니다.
- 애플 로그인 진행 시 처음 회원가입한 회원이라면 랜덤 닉네임으로 회원 정보를 저장 후 토큰을 생성하여 반환합니다.
- 애플 로그인 로직
  1. 클라이언트에서 애플 서버로 로그인하여 애플 토큰을 받아옵니다.
  2. 해당 토큰을 서버로 전송합니다.
  3. 서버에서는 애플 서버로부터 퍼블릭 키 목록을 받습니다.
  4. 퍼블릭 키 목록 중 애플 토큰을 해독할 수 있는 퍼블릭 키를 찾아서 키를 생성합니다.
  5. 애플 토큰을 해독하여 사용자 정보를 추출합니다.
  6. 사용자 정보를 바탕으로 회원가입을 진행합니다.
  7. 회원가입된 회원 정보를 바탕으로 서버에 인증할 수 있는 토큰을 생성하여 반환합니다.

## 🌟 리뷰 요구 사항

> 1시간
> 위의 로직을 따라가면서 리뷰해주시면 감사합니다 :)

2023-08-07 13:30 UTC, Kim0914 requested changes
애플 로그인의 황제 다즐씨
야무지게 구현 잘 해주셨네요 ㅎㅎ
궁금한 부분과 생각해볼만한 부분 코멘트로 남겼어요 😎
고생많았습니다 !!

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthController.java
> +public class AuthController implements AuthControllerDocs {
스웨거 설정때문에 어쩔 수 없는 것 같긴한데, Docs 컨트롤러를 implements 한다는게 애매한 것 같네요 ㅜㅜ

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/FoodbowlApplication.java
> +@ConfigurationPropertiesScan
패키지 경로를 설정하지 않으면 기본으로 어떤 경로가 들어가나요?!

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +        PlatformUser platformUser = appleOAuthUserProvider.extractPlatformUser(appleLoginRequest.appleToken());
`PlatformUser` 라는 네이밍이 잘 와닿지 않는 것 같아요.
어떤 의미를 담고 있나요?

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +                        accessToken,
accessToken은 발급한 이후에 저장할 필요가 없을 것 같은데 accessToken을 저장하는 이유가 궁금합니다 !

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +                    String nickname = nicknameGenerator.generate();
여기서 닉네임을 서버에서 직접 생성하는 목적이 임의의 닉네임을 설정해주기 위함인가요?ㅎㅎ

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/NicknameGenerator.java
> +@Component
`NicknameGenerator`가 빈 객체로 등록되어야 하는 이유가 궁금합니다 !

MemberRepository 의존성을 주입받기 위함이라고 보이는 것 같은데, 정적 팩토리 메서드를 사용해도 충분하지 않을까요?

닉네임의 중복을 확인하기 위함이라면 닉네임을 생성하는 객체가 해당 기능을 수행하는게 맞을지, 서비스 계층에서 수행하는 것이 맞을지에 대한 생각도 궁금하네요 😁

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/apple/ApplePublicKeyGenerator.java
> +            throw new IllegalStateException("유효하지 않은 애플 키입니다.", exception);
요기는 커스텀 예외 형식을 사용하지 않은 이유가 있을까요?!

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerDocs.java
> +                    responseCode = "500",
`IllegalStateException`이 발생했을 때 internalServerError를 발생시키는 과정에서 500이 발생할 수 있는거죠?!

500 서버 에러를 내려주는 이유가 궁금합니다 !

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.internalServerError()
500번대 예외를 내려주는 것을 의도한건지 궁금합니다 !

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/presentation/jwt/JwtAuthenticationFilter.java
> +        if (accessToken.isPresent()) {
위 `jwtAuthorizationExtractor.extractAccessToken(request)`을 가져올 때 `orElseThrow`로 처리할 수 있을 것 같은데 이렇게 구현한 이유가 궁금합니다 !

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/presentation/jwt/JwtAuthorizationExtractor.java
> +        return splitAuth.length == 2 ? Optional.of(splitAuth[TOKEN_INDEX]) : Optional.empty();
2 값도 매직 넘버로 빼면 좋을 것 같아요 ~

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/util/EncryptUtils.java
> +            throw new IllegalStateException("존재하지 않는 알고리즘입니다.", e);
여기도 커스텀 예외를 사용하지 않은 이유가 궁금합니다 ~

2023-08-07 13:30 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/global/presentation/security/CustomAuthenticationEntryPoint.java
> +public class CustomAuthenticationEntryPoint implements AuthenticationEntryPoint {
이 클래스의 역할이 궁금합니다 ㅎㅎ
코드 상으로 보면 401 상태코드를 응답에 담아주고 있는 것 같네요 !

2023-08-07 13:30 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/auth/application/AuthServiceTest.java
> +            Claims claims = jwtTokenProvider.extractClaims(saveAccessToken).get();
위에서 남긴 리뷰 중에 accessToken을 저장하는 부분에 따라 변경될 수 있는 부분이네요 !

2023-08-07 13:30 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/auth/application/NicknameGeneratorTest.java
> +class NicknameGeneratorTest extends IntegrationTest {
NicknameGenerator 테스트를 보면 빈으로 등록해서 사용하기 보다, 순수 도메인으로 설계한 후에 해당 로직을 검증하는게 더 자연스러워보여요 !

빈으로 등록해야만 하는 객체라면 현재 테스트를 유지해야겠네요 🙃

2023-08-07 13:30 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/auth/application/apple/ApplePublicKeyGeneratorTest.java
> +                "1JiU4l3YCeT4o0gVmxGTEK1IXR-Ghdg5Bzka12tzmtdCxU00ChH66aV-4HRBjF1t95IsaeHeDFRgmF0lJbTDTqa6_VZo2hc0zTiUAsGLacN6slePvDcR1IMucQGtPP5tGhIbU-HKabsKOFdD4VQ5PCXifjpN9R-1qOR571BxCAl4u1kUUIePAA
ㅋㅋㅋ 괴상한 문자열이네요 🥹

2023-08-07 13:30 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepositoryTest.java
> +            assertThat(findMember).isNotEmpty();
`isPresent`로 한번에 assertThat으로 검증해도 되겠네요 !

2023-08-07 13:30 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/test/PersistenceTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = Persister.class))
`@ComponentScan(basePackages = "org.dinosaur.foodbowl.persister")`로 스캔 대상 패키지를 지정할 수도 있는데 `@Persister `어노테이션을 만들어서 이 방법을 사용하신 이유가 궁금합니닷 !

2023-08-08 06:14 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthController.java
> +public class AuthController implements AuthControllerDocs {
Swagger 어노테이션을 분리하고 Swagger Docs를 위한 Controller를 나타내기 위한 클래스명입니다 🥲

구현한다는 입장에서 조금 애매한 것 같은데 혹시 더 좋은 방법이 있을까요?!

2023-08-08 06:20 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/FoodbowlApplication.java
> +@ConfigurationPropertiesScan
해당 어노테이션이 적용되어 있는 곳을 기준으로 하위 패키지에 대한 탐색을 진행할 것 같습니다!

`@ConfigurationProperty`를 사용하기 위한 어노테이션이었는데, 해당 기능을 사용하지 않아 위의 어노테이션은 제거하도록 리팩토링 하였습니다. 놓치고 지나갔었던 부분인데 질문해주신 덕분에 찾을 수 있었네요! 감사합니다 🙇🏻‍♂️

2023-08-08 06:22 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +        PlatformUser platformUser = appleOAuthUserProvider.extractPlatformUser(appleLoginRequest.appleToken());
`Apple Server`가 가지고 있는 유저의 정보를 가지고 있는 객체입니다! 확장성을 고려하여 다른 `OAuth`가 추가되더라도 공용으로 사용할 수 있게 네이밍을 지어봤는데 의미가 잘 와닿지 않으신가요?

혹시 더 좋은 네이밍이 있다면 추천해주시면 감사합니다 :)

2023-08-08 06:48 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +                        accessToken,
각각의 토큰이 탈취당했을 때 상황을 고려해보았습니다!

1. access token만 탈취당하면 짧은 유효시간으로 인해 빠르게 인증을 무효화시킬 수 있습니다.
2. refresh token만 탈취당했을 때 서버에서 refresh token 정보만 가지고 있으면 토큰을 탈취한 악성 유저는 access token을 무한으로 발급받을 수 있습니다.
2-1. 따라서 access token과 refresh token 데이터를 묶어서 저장할 필요가 있습니다. 이를 위한 방법으로 2가지를 생각해 보았습니다.
```
{
  userId : refreshToken
}
```

2023-08-08 07:00 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +                        accessToken,
갑자기 든 생각은 access token을 value로 둔다면 토큰을 갱신할 때마다 refresh token의 value도 갱신이 필요할 것 같다는 생각도 드네요 🤔

2023-08-08 07:07 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +                    String nickname = nicknameGenerator.generate();
맞습니다! 처음 로그인한 회원은 임의의 닉네임으로 회원가입하도록 되어 있습니다 :)

2023-08-08 07:52 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/NicknameGenerator.java
> +@Component
`NicknameGenerator`를 빈으로 등록한 이유는 `MemberRepository` 의존성을 주입받기 위함이 맞습니다!

중복 검증을 닉네임 생성 메서드 안에서 해야한다고 생각했으나, 검증 로직은 서비스 계층에서 수행하는 것이 맞는 것 같아 로직을 옮기게 되었고 그에 따라 `MemberRepository` 의존성이 필요하지 않은 `NicknameGenerator`는 정적 팩터리 메서드로 수정하였습니다 :)

감사합니다 배워갑니다 🙇🏻‍♂️

2023-08-08 08:01 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/apple/ApplePublicKeyGenerator.java
> +            throw new IllegalStateException("유효하지 않은 애플 키입니다.", exception);
클라이언트 요청에 의해 예외가 발생하는 것이 아닌 서버에서 알고리즘을 잘못 설정했거나, 애플 키를 잘못 가져와서 키를 만드는 경우 발생하는 에러를 처리하기 위해 `IllegalStateException`을 사용했습니다! 서버의 상태에 의한 에러라서 기존의 에러를 활용하고자 했습니다.

이런 경우에도 커스텀 예외를 만들어서 처리하는게 좋을까요? 😄

2023-08-08 08:01 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerDocs.java
> +                    responseCode = "500",
맞습니다! 서버 상태가 잘못된 경우이기에 500 에러가 발생할 수 있는 상황을 문서화하였습니다 :)

2023-08-08 08:02 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.internalServerError()
https://github.com/Busan-Dinosaur/Foodbowl-Backend/pull/95#discussion_r1286754847

동일한 내용이라 링크로 대체하겠습니다 ㅎㅎ

2023-08-08 08:08 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/presentation/jwt/JwtAuthenticationFilter.java
> +        if (accessToken.isPresent()) {
필터에서 발생하는 예외를 처리하기 위해서는 별도의 필터를 만들어주어야 했던 것 같습니다! `SecurityContext`에 인증 객체만 존재하지 않으면 필터가 끝날 때 자동으로 예외를 발생시켜주기에 토큰이 유효하지 않거나, 토큰이 존재하지 않을 때 예외를 터뜨리기보다는 컨텍스트에 인증 객체를 넣지 않는 방법을 선택하였습니다.

인증 객체가 컨텍스트에 존재하지 않으면 필터는 `CustomAuthenticationEntryPoint`로 향하게 되고, 거기서 예외에 대한 처리를 진행하게 됩니다. 인증과 관련된 모든 상황을 `EntryPoint`에서 예외 처리하고자 예외를 던지지 않았습니다 😃

2023-08-08 12:33 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/util/EncryptUtils.java
> +            throw new IllegalStateException("존재하지 않는 알고리즘입니다.", e);
https://github.com/Busan-Dinosaur/Foodbowl-Backend/pull/95#discussion_r1286754847

여기도 동일한 내용이라 링크로 대체하겠습니다 ㅎㅎ

2023-08-08 12:34 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/global/presentation/security/CustomAuthenticationEntryPoint.java
> +public class CustomAuthenticationEntryPoint implements AuthenticationEntryPoint {
모든 필터를 다 거쳤음에도 `SecurityContext`에 인증 정보가 존재하지 않으면

해당 포인트로 오게 되고 `401` 상태를 반환하게 됩니다 :)

2023-08-08 12:35 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/auth/application/NicknameGeneratorTest.java
> +class NicknameGeneratorTest extends IntegrationTest {
순수 도메인으로 설계한 후 테스트도 수정 완료하였습니다 :)

2023-08-08 12:39 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepositoryTest.java
> +            assertThat(findMember).isNotEmpty();
이 부분 잘 이해하지 못했는데 코드로 다시 한번 설명부탁드려도 될까요 🤔

2023-08-08 12:42 UTC, woo-chang commented on src/test/java/org/dinosaur/foodbowl/test/PersistenceTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = Persister.class))
어노테이션을 통해 해당 클래스가 어떤 역할을 하는 클래스인지에 대한 정보를 코드 레벨로 담으려고 했습니다! 그렇기에 컴포넌트 스캔 시에도 패키지 정보보다는 해당 어노테이션 정보를 바탕으로 스캔할 수 있도록 설정하였습니다 😃

혹시 패키지로 컴포넌트 스캔을 했을 때 얻을 수 있는 다른 이점이 존재하나요? 해당 방법을 사용해야하는 이유가 궁금합니다!

2023-08-08 13:39 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthController.java
> +public class AuthController implements AuthControllerDocs {
음... 곰곰히 생각을 해봤는데 오히려 `AuthControllerDocs`가 제일 베스트인 것 같기도 하네요 ㅎㅎ

`AuthControllerDocs`는 진짜 스웨거 설정만 있기 때문에, 다른 사람이 보더라도 docs 관련 설정이네? 하고 이해할 수 있을 것 같다는 생각이 드네요 🙃

인터페이스를 사용하는 방법 말고 찾아봐도 뾰족한 아이디어가 없네요..
현재가 최선인 것 같기도 합니다 !

2023-08-08 13:41 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +        PlatformUser platformUser = appleOAuthUserProvider.extractPlatformUser(appleLoginRequest.appleToken());
저희 서비스에서 애플 로그인 이외에는 (기획적으로) 추가될 OAuth가 없을 것 같은데 직관적으로 `AppleUser`가 더 좋지 않을까요? 😀

현재 코드에서도 `AppleUser`를 대입해서 보면 훨씬 명확한 것 같아요 !

2023-08-08 13:55 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/apple/ApplePublicKeyGenerator.java
> +            throw new IllegalStateException("유효하지 않은 애플 키입니다.", exception);
저는 커스텀 예외를 도입하기로 했다면, 일관되게 커스텀 예외를 적용하는게 좋지 않을까 생각합니다.

`SERVER-101`, `SERVER-102`의 경우에는 코드에 따른 예외 상황(메세지)이 여러가지일 것 같아요. 
예측할 수 없는 `SERVER-100`의 경우에는 일관되게 `알 수 없는 서버 에러가 발생했습니다.`로 응답하는 것과는 다르게요 !

저희가 커스텀 예외(클래스에 따른 코드, 메세지) 형식을 가져가기로 했으니, 모든 예외에 대해서는 일관되게 적용해야할 것 같아요.

`ServerException`을 두고 코드, 메세지로 구분하는 방법은 어떤가요?!
굳이?라고 생각할 수 있지만, 커스텀 예외를 도입했을 때 마주할 수 있는 단점이라고도 생각해요 ㅎㅎ

2023-08-08 14:01 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepositoryTest.java
> +            assertThat(findMember).isNotEmpty();
```suggestion
           assertThat(memberRepository.findBySocialTypeAndSocialId(socialType, socialId)).isPresent();
```

이 뜻이었습니다 !!

크게 중요한 부분은 아니라서 ㅎㅎ 넘어가도 괜찮아요 ~

2023-08-08 14:03 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/test/PersistenceTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = Persister.class))
현재 구조에서 패키지로 컴포넌트 스캔을 했을 때 얻을 수 있는 이점은 딱히 없습니다 ㅎㅎ
`Persister`가 모두 같은 패키지에 있기 때문에, 작성해주신 부분과 동일하게 동작할 것 같아요 !

만약 이 패키지에 다른 빈 객체들도 존재한다면, 쓸모없는 빈들이 등록되는 이슈가 있을 것 같네요 ~
그런 상황에서는 작성해주신 대로 명확하게 어노테이션이 있는 빈들만 가져올 수 있겠네요 😀

단순한 궁금증이었습니다 ~ 좋아요 !

2023-08-08 16:06 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/member/domain/vo/Nickname.java
> +        if (!matcher.matches()) {
matcher 생성해서 사용하기 👍

2023-08-09 00:50 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +        PlatformUser platformUser = appleOAuthUserProvider.extractPlatformUser(appleLoginRequest.appleToken());
좋은 의견 감사합니다 :) 현재로서는 다른 `OAuth`로의 확장 계획이 없기에 `AppleUser`로 수정하였습니다~

2023-08-09 01:02 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/apple/ApplePublicKeyGenerator.java
> +            throw new IllegalStateException("유효하지 않은 애플 키입니다.", exception);
설득 당했습니다! 커스텀 예외를 적용하였기에 해당 상황에서도 일관되게 커스텀 예외를 적용하는 것이 좋을 것 같네요 ㅎㅎ

`ServerException` 커스텀 예외를 생성하고 수정하도록 하였습니다 :)

2023-08-09 12:28 UTC, Kim0914 commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +                        accessToken,
저는 토큰을 사용하는 이유 중 가장 큰 이유가 stateless라고 생각해요 !

그래서 토큰을 발급함과 동시에 서버의 영역에서 떠나게되고, 클라이언트가 전달해주는 토큰을 가지고 토큰을 검증하는 역할을 서버에서 가져가죠 ! 여기서 토큰이 탈취되었을 때, 보안 이슈가 발생할 수 있다는 점이 존재한다고 생각하는데 이 보안 이슈를 막기 위해서 등장한 것이 refresh token이라고 생각합니다 ㅎㅎ

accessToken의 유효시간을 짧게 가져가서 탈취되더라도, 토큰을 탈취한 악의적인 사용자가 사용할 수 있는 기간을 짧게 해버리죠.

accessToken을 서버에서 저장한다면 세션을 사용하는 방법과 큰 차이를 느끼지 못한다고 생각해요.

마지막으로 댓글을 남겨주신 부분도 생각해볼 필요가 있을 것 같습니다. Refresh Token을 가지고 토큰 재발행을 하면 기존의 refresh token은 유지하되 accessToken은 새롭게 전달해야할 것 같아요 !
아니면 토큰 재발행을 할 때 RefreshToken도 함께 새로 발급해버릴 수도 있을 것 같아요. 이러면 RefreshToken의 탈취 위험을 좀 더 막을 수 있다는 장점?도 떠오르네요 !

결론적으로, 저는 1번 방법이 토큰을 사용하는 목적과도 부합하고, accessToken에서 userId를 추출해 rt값을 조회할 수 있는 자연스러운 방법이라고 생각합니다.

2023-08-09 12:30 UTC, woo-chang commented on src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
> +                        accessToken,
토큰 사용이유인 `stateless`를 간과하고 있었네요 :)

기술을 사용할 때 기술을 사용해야하는 이유에 대해 다시 한번 고민해볼 수 있었어요. 말씀해주신 것처럼 1번 방법이 토큰을 사용하는 목적과 가장 부합하다고 생각하여 1번 방법으로 수정 완료하였습니다 ㅎㅎ

2023-08-09 12:34 UTC, Kim0914 approved these changes
리뷰 반영주신 부분 확인했습니다 !

코멘트 남기면서 많이 배웠네요 :)
중요한 로그인 기능을 구현하시느라 고생했어요 !

conflict나는 부분있는데 이 부분만 해결해주시면 되겠네요 😉

2023-08-09 12:34 UTC, Kim0914 commented on src/test/java/org/dinosaur/foodbowl/domain/auth/application/AuthServiceTest.java
>          void 등록된_회원이라면_토큰_정보를_반환한다() {
테스트 굿 !

2023-08-09 13:36 UTC, merged